[fc] Repository: plone.scale
Branch: refs/heads/master
Date: 2022-05-16T16:22:44+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.scale/commit/9e831316407afd0dfe69e0c55e55dd752cd1cd96

Pre scale: store non-random uid to prepare space for a scale.

Do not generate the scale yet.
Only generate it when a visitor calls the url of the unique scale.

Note: contains various print statements for debugging.

Files changed:
A news/57.feature
M plone/scale/scale.py
M plone/scale/storage.py
Repository: plone.scale

Branch: refs/heads/master
Date: 2022-05-17T19:09:41+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.scale/commit/cd5788615dd56d8ab55268300e1d25922997d5b2

Add pre_scale and get_or_generate to IImageScaleStorage interface.

Files changed:
M plone/scale/storage.py
Repository: plone.scale

Branch: refs/heads/master
Date: 2022-05-17T21:54:03+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.scale/commit/b299e3d30dddddaa3ff994c7b952afc275872ce7

We need the modified time in the hash.

Otherwise you get the same hash for the same parameters even if the image is different.

Files changed:
M plone/scale/storage.py
M plone/scale/tests/test_storage.py
Repository: plone.scale

Branch: refs/heads/master
Date: 2022-05-17T22:24:30+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.scale/commit/f2134335af4347a856182bb1e091f9a274bcf1ab

Allow width and height to be None in _calculate_all_dimensions.

Should not happen in practice I guess, but helps for plone.namedfile tests.
Just return the original dimensions, and we are fine.

Files changed:
M plone/scale/scale.py
M plone/scale/storage.py
Repository: plone.scale

Branch: refs/heads/master
Date: 2022-05-17T22:44:31+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.scale/commit/ab11dbd65eb2a6f87bb8831d48408fe8111d3b45

Merge branch 'master' into pre-scale

Files changed:
A news/55.bugfix
M plone/scale/storage.py
M plone/scale/tests/test_storage.py
Repository: plone.scale

Branch: refs/heads/master
Date: 2022-05-17T23:05:33+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.scale/commit/24d350851beb0f6640fd2a632308495476be712b

Add mimetype with pre=True

Files changed:
M plone/scale/storage.py
Repository: plone.scale

Branch: refs/heads/master
Date: 2022-05-18T09:59:04+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.scale/commit/1f3937c653d0ad4843b049841db82dfa3874678b

Set data=None instead of placeholder=True.

We were not yet using placeholder anywhere, only checking the data key.

Files changed:
M plone/scale/storage.py
Repository: plone.scale

Branch: refs/heads/master
Date: 2022-05-18T10:06:55+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.scale/commit/d59de5a2cc3779a6f58d8194e6cfe7c6d0440428

unhash: remove the "modified" parameter that we added in the hash method.

We want the original parameters only.

Files changed:
M plone/scale/storage.py
Repository: plone.scale

Branch: refs/heads/master
Date: 2022-05-18T13:06:14+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.scale/commit/1691dade855750a977bbf28c4dc34700348e37bd

get_or_generate: return outdated scales.

Files changed:
M plone/scale/storage.py
Repository: plone.scale

Branch: refs/heads/master
Date: 2022-05-18T13:35:25+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.scale/commit/b18da865ccbab6f87218447a30aac7425442846f

Add tests for pre_scale and get_or_generate.

Files changed:
M plone/scale/tests/test_storage.py
Repository: plone.scale

Branch: refs/heads/master
Date: 2022-05-18T14:19:59+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.scale/commit/282b6e14992ee54967923380efe28010bf6eae4f

Hash the modified time in the uid, not in the hashed key of parameters.

Files changed:
M plone/scale/storage.py
Repository: plone.scale

Branch: refs/heads/master
Date: 2022-05-18T16:29:22+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.scale/commit/d3546c4c9bbf597580ca32c8057288b89086051d

Let the hash method be the same as it originally was.

I changed something, later backed it out, but not exactly to the original.
Looks strange when reviewing.

Files changed:
M plone/scale/storage.py
Repository: plone.scale

Branch: refs/heads/master
Date: 2022-05-18T16:32:03+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.scale/commit/f2adcc83fa413aa0d13867a73bcb2f64803f2e70

Explain the new uid structure.

Files changed:
M plone/scale/storage.py
Repository: plone.scale

Branch: refs/heads/master
Date: 2022-05-18T16:41:42+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.scale/commit/8e2ab3d4aa3486b80d6681e0cddce12650496bee

Document the change.

Files changed:
M README.rst
M news/57.feature
Repository: plone.scale

Branch: refs/heads/master
Date: 2022-05-19T00:15:32+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.scale/commit/4c1790db266a42b4cd94df8c592f3ffc68e6cbd0

Changed prints to logger.debug.

This fixes plone.formwidget.namedfile doctests. :-)

Files changed:
M plone/scale/storage.py
Repository: plone.scale

Branch: refs/heads/master
Date: 2022-05-20T17:02:13+03:00
Author: MrTango (MrTango) <md@derico.de>
Commit: https://github.com/plone/plone.scale/commit/821fdb67ab9ff646e35527ab773b58d551a4de31

prevent duplicate modified key in hash call

Files changed:
M plone/scale/storage.py
Repository: plone.scale

Branch: refs/heads/master
Date: 2022-05-23T21:48:44+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.scale/commit/35772ffbaf028d690ceb70bb645dd02024e130f6

In pre_scale call scaling_factory.get_original_value.

Otherwise we pre-register a scale for a field that is not there.
Sample error:

```
http://localhost:8080/Plone/@@ajax-search
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 167, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 376, in publish_module
  Module ZPublisher.WSGIPublisher, line 271, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 68, in call_object
  Module Products.CMFPlone.browser.search, line 288, in __call__
  Module Products.CMFPlone.browser.search, line 303, in get_image_tag
  Module plone.memoize.volatile, line 74, in replacement
  Module plone.namedfile.scaling, line 601, in tag
  Module plone.namedfile.scaling, line 583, in tag
  Module plone.namedfile.scaling, line 539, in scale
  Module plone.namedfile.scaling, line 61, in __init__
AttributeError: 'RequestContainer' object has no attribute 'image'
```

This is what causes a test failure in this test:

```
$ bin/test --all -s Products.CMFPlone -m test_robot -t 'Simple Livesearch'
```

Files changed:
M plone/scale/interfaces.py
M plone/scale/storage.py
M plone/scale/tests/test_storage.py
Repository: plone.scale

Branch: refs/heads/master
Date: 2022-05-24T08:46:02+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.scale/commit/bacac4940625596aab489669a91fb5da0513df5c

Merge branch 'master' into pre-scale

This fixes cropping.

Files changed:
A news/53.bugfix
M plone/scale/scale.py
M plone/scale/tests/test_scale.py
Repository: plone.scale

Branch: refs/heads/master
Date: 2022-05-24T09:04:44+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.scale/commit/7dc3736c20b8d956c792d6db20250b53413bc1b1

Pass fieldname to get_original_value.

Otherwise it depends on having self.fieldname, which is not set here.
Then it falls back to IPrimaryFieldInfo.
In case of a news item with lead image, this does not find anything.

Files changed:
M plone/scale/interfaces.py
M plone/scale/storage.py
Repository: plone.scale

Branch: refs/heads/master
Date: 2022-05-24T09:13:22+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.scale/commit/d0d409dad2ab090193a494efa01e5d42ed0c4cf4

Fix get_original_value in tests.

Files changed:
M plone/scale/tests/test_storage.py
Repository: plone.scale

Branch: refs/heads/master
Date: 2022-06-09T09:50:14+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.scale/commit/ba783751b4e8514d18e4a865c3f840082a5165df

Give ScaledDimensions an init method.

Set initial values for all properties there.
From review comment https://github.com/plone/plone.scale/pull/57/files#r893129424

Files changed:
M plone/scale/scale.py
Repository: plone.scale

Branch: refs/heads/master
Date: 2022-06-09T13:18:28+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.scale/commit/258731910a35f37056a2097d7607e35db964fad1

Merge pull request #57 from plone/pre-scale

Pre scale: store non-random uid to prepare space for a scale.

Files changed:
A news/57.feature
M README.rst
M plone/scale/interfaces.py
M plone/scale/scale.py
M plone/scale/storage.py
M plone/scale/tests/test_storage.py