[fc] Repository: plone.app.theming
Branch: refs/heads/master
Date: 2025-09-24T22:00:37+02:00
Author: Johannes Raggam (thet) <thetetet@gmail.com>
Commit: https://github.com/plone/plone.app.theming/commit/0ace51dc2adb75909b123924c8cbc3be4ace36c0

Expose the ``IClassicUISchema`` registry setting ``use_ajax_main_template`` in the theming control panel.

Files changed:
A news/+ajax_marker.feature.rst
M setup.py
M src/plone/app/theming/browser/controlpanel.pt
M src/plone/app/theming/browser/controlpanel.py
Repository: plone.app.theming

Branch: refs/heads/master
Date: 2025-09-24T22:31:18+02:00
Author: Johannes Raggam (thet) <thetetet@gmail.com>
Commit: https://github.com/plone/plone.app.theming/commit/e90f451fb3ca748341471debac122f03b59a6772

Drop compatibility with Plone 6.1.

The new IClassicUISchema.use_ajax_main_template setting needs latest plone.base
4.0.0a1 which is part of CMFPlone 6.2.

Files changed:
A news/+plone62.breaking.rst
M .github/workflows/test-matrix.yml
M setup.py
M tox.ini
Repository: plone.app.theming

Branch: refs/heads/master
Date: 2025-09-25T10:17:29+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.theming/commit/59257725ca84801442d53a7735d5ad1c6841f5a3

Fix test matrix: Plone 6.2 only.

Files changed:
M .github/workflows/test-matrix.yml
M .meta.toml
M pyproject.toml
M tox.ini
Repository: plone.app.theming

Branch: refs/heads/master
Date: 2025-09-25T10:29:15+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.theming/commit/a9302bcb525aa4fa8329800d9f51668cbee65a81

Use mxdev to pull in Products.CMFPlone master.

Otherwise you get a test failure:

```
  File "/home/runner/work/plone.app.theming/plone.app.theming/src/plone/app/theming/browser/controlpanel.py", line 223, in update
    self.use_ajax_main_template = use_ajax_main_template
  File "/home/runner/work/plone.app.theming/plone.app.theming/src/plone/app/theming/browser/controlpanel.py", line 113, in set_use_ajax_main_template
    self.classicui_settings.use_ajax_main_template = value
  File "/home/runner/work/plone.app.theming/plone.app.theming/.tox/py313-plone62/lib/python3.13/site-packages/plone/registry/recordsproxy.py", line 47, in __setattr__
    raise AttributeError(name)
AttributeError: use_ajax_main_template
```

This is needed until we have a 6.2 alpha release.

Files changed:
A mx.ini
A requirements.txt
M .meta.toml
M MANIFEST.in
M tox.ini
Repository: plone.app.theming

Branch: refs/heads/master
Date: 2025-09-25T10:59:27+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.theming/commit/cb2a3bd4712847a047ab3936e3c24f576d5eb3c3

Do not use the CMFPlone source in the circular and release-check tox envs.

Files changed:
M tox.ini
Repository: plone.app.theming

Branch: refs/heads/master
Date: 2025-09-25T12:23:00+02:00
Author: Johannes Raggam (thet) <thetetet@gmail.com>
Commit: https://github.com/plone/plone.app.theming/commit/224b1c261e6c7f8a013e7684599c4b031af68be9

Merge pull request #265 from plone/ajax_marker

Expose the ``IClassicUISchema`` registry setting ``use_ajax_main_template`` in the theming control panel.

Files changed:
A mx.ini
A news/+ajax_marker.feature.rst
A news/+plone62.breaking.rst
A requirements.txt
M .github/workflows/test-matrix.yml
M .meta.toml
M MANIFEST.in
M pyproject.toml
M setup.py
M src/plone/app/theming/browser/controlpanel.pt
M src/plone/app/theming/browser/controlpanel.py
M tox.ini