[fc] Repository: plone.releaser
Branch: refs/heads/master
Date: 2023-09-01T18:48:27+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/5d85a1fe667c69153cf12e2267d31df407f9f572

Test buildout CheckoutsFile.

Files changed:
A plone/releaser/tests/input/checkouts.cfg
M plone/releaser/buildout.py
M plone/releaser/tests/test_buildout.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-09-01T18:48:27+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/7b546ebd7c467d26c8365acadfa1c0812a595591

Test updating mxdev.ini, fixing some corner cases.

Files changed:
A plone/releaser/tests/input/mxdev.ini
M plone/releaser/pip.py
M plone/releaser/tests/test_pip.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-09-01T22:17:45+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/75594aa5cabdee207f7af9d09a0371b2165c1a86

Make buildout.Source.create_from_string a classmethod.

Test it.

Files changed:
M plone/releaser/buildout.py
M plone/releaser/tests/test_buildout.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-09-01T22:34:54+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/b1e7e3d6fe1c32117e33b7d0c8c9da60bce59600

Removed no longer working pulls command that I have never used.

Removed `PyGithub` and `keyring` dependencies that was only used for this.
Removed `Source.path` property that was only used for this.

Traceback when you try the `pulls` command:

```
$ bin/manage pulls
Traceback (most recent call last):
  File "/Users/maurits/community/plone-coredev/6.0/bin/manage", line 69, in &lt;module&gt;
    sys.exit(plone.releaser.manage.manage())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.releaser/plone/releaser/manage.py", line 271, in __call__
    parser.dispatch()
  File "/Users/maurits/shared-eggs/cp311/argh-0.28.1-py3.11.egg/argh/helpers.py", line 54, in dispatch
    return dispatch(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurits/shared-eggs/cp311/argh-0.28.1-py3.11.egg/argh/dispatching.py", line 179, in dispatch
    for line in lines:
  File "/Users/maurits/shared-eggs/cp311/argh-0.28.1-py3.11.egg/argh/dispatching.py", line 290, in _execute_command
    for line in result:
  File "/Users/maurits/shared-eggs/cp311/argh-0.28.1-py3.11.egg/argh/dispatching.py", line 273, in _call
    result = function(*positional, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.releaser/plone/releaser/manage.py", line 94, in pulls
    g = Github(client_id=client_id, client_secret=client_secret)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Github.__init__() got an unexpected keyword argument 'client_id'
```

Files changed:
A news/56.bugfix
M plone/releaser/buildout.py
M plone/releaser/manage.py
M setup.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-09-01T23:37:51+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/01adec7cf2aed968b2288f4f049b33eed7eac9a1

Source: support path and egg options.

Then the docs and mockup sources can get parsed.

Files changed:
M plone/releaser/buildout.py
M plone/releaser/tests/test_buildout.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-09-07T22:13:36+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/1fd616bec66ae43b4abcded02b06ec068533d9fa

Test SourcesFile, add contains and get, and repr/eq on Source.

Files changed:
A plone/releaser/tests/input/sources.cfg
M plone/releaser/buildout.py
M plone/releaser/tests/test_buildout.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-09-07T22:22:06+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/fecdf8ad3cf2da80a143c8ead1506c44b9c63fd2

Let VersionsFile inherit from UserDict, and use data instead of versions.

Closer to the others.

Files changed:
M plone/releaser/buildout.py
M plone/releaser/tests/test_buildout.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-09-07T22:24:14+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/92a57599c5d0d7f2be82caa26cd45d532a479083

Let ConstraintsFile inherit from UserDict, and use data instead of constraints.

Closer to the others.

Files changed:
M plone/releaser/pip.py
M plone/releaser/tests/test_pip.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-09-07T22:49:08+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/6d0eda4ce593dbc2db30b3be14e8cdcac8a5e44f

Add base.BaseFile as basis for most pip/buildout files.

These classes were using lots of very similar methods.

Files changed:
A plone/releaser/base.py
M plone/releaser/buildout.py
M plone/releaser/pip.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-09-07T22:51:27+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/7101bc9321e5073d8921e89b6ab0e98e14a40e99

news snippet

Files changed:
M news/56.bugfix
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-09-07T22:58:10+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/42a5b36f3ebe44974b922c259076e1751e2190e8

Use self.path more, instead of self.file_location.

Files changed:
M plone/releaser/buildout.py
M plone/releaser/pip.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-09-14T00:48:41+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/58d0a22181b598bcee8e7c509bcebea0804b81be

Merge pull request #56 from plone/maurits-more-tests

Improve and test sources. Share code.

Files changed:
A news/56.bugfix
A plone/releaser/base.py
A plone/releaser/tests/input/checkouts.cfg
A plone/releaser/tests/input/mxdev.ini
A plone/releaser/tests/input/sources.cfg
M plone/releaser/buildout.py
M plone/releaser/manage.py
M plone/releaser/pip.py
M plone/releaser/tests/test_buildout.py
M plone/releaser/tests/test_pip.py
M setup.py