Do not generate dependent releaser scripts on Python 3.6.
Needed to fix the hopefully last problems on Jenkins node 4 with Python 3.6, which seems to have no locale setting.
See https://github.com/plone/buildout.coredev/issues/642#issuecomment-597008272

Sample traceback (local):

```
While:
  Installing releaser.
Traceback (most recent call last):
  File "/Users/maurits/community/plone-coredev/py3/lib/python3.6/site-packages/zc/buildout/buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "/Users/maurits/community/plone-coredev/py3/lib/python3.6/site-packages/zc/buildout/buildout.py", line 817, in install
    installed_files = self[part]._call(recipe.install)
  File "/Users/maurits/community/plone-coredev/py3/lib/python3.6/site-packages/zc/buildout/buildout.py", line 1603, in _call
    return f()
  File "/Users/maurits/shared-eggs/cp36m/zc.recipe.egg-2.0.7-py3.6.egg/zc/recipe/egg/egg.py", line 263, in install
    relative_paths=self._relative_paths,
  File "/Users/maurits/community/plone-coredev/py3/lib/python3.6/site-packages/zc/buildout/easy_install.py", line 1219, in scripts
    _distutils_script(spath, sname, contents, initialization, rpsetup)
  File "/Users/maurits/community/plone-coredev/py3/lib/python3.6/site-packages/zc/buildout/easy_install.py", line 1346, in _distutils_script
    return _create_script(contents, dest)
  File "/Users/maurits/community/plone-coredev/py3/lib/python3.6/site-packages/zc/buildout/easy_install.py", line 1384, in _create_script
    f.write(contents)
UnicodeEncodeError: 'ascii' codec can't encode character '\xa9' in position 96: ordinal not in range(128)
```

This is while generating the `bin/rst2html5.py` script, which fails because it contains this text:

    Copyright: © 2015 Günter Milde.