[fc] Repository: plone.volto
Branch: refs/heads/main
Date: 2021-12-25T17:23:01-08:00
Author: Ross Patterson (rpatterson) <me@rpatterson.net>
Commit: https://github.com/plone/plone.volto/commit/1d4f927dc7a5ddef73799af505e98732a6f8954e

test(settings): Isolation w/ frontend_domain None

Workaround a test fixture isolation issue where the `IVoltoSettings.frontend_domain`
setting has a value of `None` by changing the `plone.volto.patches.construct_url` patch
to properly handle that value.

I found under local development that there were errors in the
`plone.restapi.tests.test_services_users` tests when running the whole suite with `$
./bin/test -s plone.restapi` but not when running only those tests with `$ ./bin/test -s
plone.restapi -m plone.restapi.tests.test_services_users`:

    Failure in test test_add_anon_user_sends_properties_are_saved (plone.restapi.tests.test_services_users.T
    Current directory is /home/rpatterson/src/plone/volto/api/
    estUsersEndpoint)
    Traceback (most recent call last):
      File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
        yield
      File "/usr/lib/python3.9/unittest/case.py", line 592, in run
        self._callTestMethod(testMethod)
      File "/usr/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
        method()
      File "/home/rpatterson/src/plone/volto/api/src/plone.restapi/src/plone/restapi/tests/test_services_users.py", line 242, in test_add_anon_user_sends_properties_are_saved
        self.assertEqual(201, response.status_code)
      File "/usr/lib/python3.9/unittest/case.py", line 837, in assertEqual
        assertion_func(first, second, msg=msg)
      File "/usr/lib/python3.9/unittest/case.py", line 830, in _baseAssertEqual
        raise self.failureException(msg)
    AssertionError: 201 != 500

        457/555 (82.3%)

    Failure in test test_add_user_with_sendPasswordRest_sends_email (plone.restapi.tests.test_services_users.TestUsersEndpoint)
    Traceback (most recent call last):
      File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
        yield
      File "/usr/lib/python3.9/unittest/case.py", line 592, in run
        self._callTestMethod(testMethod)
      File "/usr/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
        method()
      File "/home/rpatterson/src/plone/volto/api/src/plone.restapi/src/plone/restapi/tests/test_services_users.py", line 204, in test_add_user_with_sendPasswordRest_sends_email
        self.assertEqual(201, response.status_code)
      File "/usr/lib/python3.9/unittest/case.py", line 837, in assertEqual
        assertion_func(first, second, msg=msg)
      File "/usr/lib/python3.9/unittest/case.py", line 830, in _baseAssertEqual
        raise self.failureException(msg)
    AssertionError: 201 != 500

        460/555 (82.9%)

    Failure in test test_anonymous_requires_enable_self_reg (plone.restapi.tests.test_services_users.TestUsersEndpoint)
    Traceback (most recent call last):
      File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
        yield
      File "/usr/lib/python3.9/unittest/case.py", line 592, in run
        self._callTestMethod(testMethod)
      File "/usr/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
        method()
      File "/home/rpatterson/src/plone/volto/api/src/plone.restapi/src/plone/restapi/tests/test_services_users.py", line 809, in test_anonymous_requires_enable_self_reg
        self.assertEqual(201, response.status_code)
      File "/usr/lib/python3.9/unittest/case.py", line 837, in assertEqual
        assertion_func(first, second, msg=msg)
      File "/usr/lib/python3.9/unittest/case.py", line 830, in _baseAssertEqual
        raise self.failureException(msg)
    AssertionError: 201 != 500

        464/555 (83.6%)

    Failure in test test_anonymous_without_enable_user_pwd_choice_sends_mail (plone.restapi.tests.test_services_users.TestUsersEndpoint)
    Traceback (most recent call last):
      File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
        yield
      File "/usr/lib/python3.9/unittest/case.py", line 592, in run
        self._callTestMethod(testMethod)
      File "/usr/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
        method()
      File "/home/rpatterson/src/plone/volto/api/src/plone.restapi/src/plone/restapi/tests/test_services_users.py", line 822, in test_anonymous_without_enable_user_pwd_choice_sends_mail
        self.assertEqual(201, response.status_code)
      File "/usr/lib/python3.9/unittest/case.py", line 837, in assertEqual
        assertion_func(first, second, msg=msg)
      File "/usr/lib/python3.9/unittest/case.py", line 830, in _baseAssertEqual
        raise self.failureException(msg)
    AssertionError: 201 != 500

        495/555 (89.2%)

    Failure in test test_user_requests_password_sends_password_via_mail (plone.restapi.tests.test_services_users.TestUsersEndpoint)
    Traceback (most recent call last):
      File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
        yield
      File "/usr/lib/python3.9/unittest/case.py", line 592, in run
        self._callTestMethod(testMethod)
      File "/usr/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
        method()
      File "/home/rpatterson/src/plone/volto/api/src/plone.restapi/src/plone/restapi/tests/test_services_users.py", line 601, in test_user_requests_password_sends_password_via_mail
        self.assertEqual(response.status_code, 200)
      File "/usr/lib/python3.9/unittest/case.py", line 837, in assertEqual
        assertion_func(first, second, msg=msg)
      File "/usr/lib/python3.9/unittest/case.py", line 830, in _baseAssertEqual
        raise self.failureException(msg)
    AssertionError: 500 != 200

Trying to get good debugging information from those failures was quite the chore, I
think we need a better `pdb.post_mortem()` story when using the
`plone.testing.z2.ZSERVER_FIXTURE` layer.  I ended up modifying
`ZPublisher.WSGIPublisher.publish_module(...)` locally to wrap the `_publish(...)` call
in a `try` clause with `pdb.post_mortem()` in the `except` block.

At any rate, the most important issue here is obviously some sort of isolation issue.
We should prioritize working towards a reality in which a test never passes, fails, or
errors because of *how* it was run.  The more tests become a nest of special
incantations, known issues, rubber chicken waving, and other lore passed around between
developers (inevitably the more senior developers), the more they are experienced as a
dogmatic obstacle to development that developers hate instead of a tool that makes
writing code more efficient and less uncertain that developers love.  Having said that,
I haven't yet put into the time to chase down the core isolation issue.

In the meantime, the "symptom" exception behind these specific errors does seem like it
comes from a case the code should handle.  Specifically, I assume the intention here was
to use the `default` argument to `getattr(...)` to avoid an empty value.  In the case
when all the tests are run, however, this setting has a value of `None` which defeats
this purpose:

    AttributeError: 'NoneType' object has no attribute 'endswith'

     - Expression: "python:view.construct_url(reset['randomstring'])+'?userid='+member.getUserName()"
     - Filename:   ... ne/browser/login/templates/registered_notify_template.pt
     - Location:   (line 21: col 48)
     - Source:     ... python:view.construct_url(reset['randomstring'])+'?userid='+member.getUserName() ...
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     - Arguments:  template: &lt;Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at 0x7f6ea01581c0&gt;
                   options: {'member': &lt;Products.PlonePAS.tools.memberdata.MemberData object at 0x7f6e9f415580&gt;, 'reset': {'randomstring': '6ef4c60fae43411394ea738744708126', 'expires': datetime.datetime(2022, 1, 1, 19, 34, 25, 661749), 'userid': 'howard'}, 'email': 'howard.zinn@example.com', 'charset': 'utf-8'}
                   args: ()
                   nothing: None
                   modules: &lt;Products.PageTemplates.ZRPythonExpr._SecureModuleImporter object at 0x7f6ea73d7df0&gt;
                   request: &lt;WSGIRequest, URL=http://localhost:42255/plone/@users&gt;
                   view: &lt;Products.Five.browser.metaconfigure.SimpleViewClass from ./eggs/Products.CMFPlone-5.2.6-py3.9.egg/Products/CMFPlone/browser/login/templates/registered_notify_template.pt object at 0x7f6e9f6928b0&gt;
                   context: &lt;RegistrationTool at /plone/portal_registration&gt;
                   views: &lt;Products.Five.browser.pagetemplatefile.ViewMapper object at 0x7f6e9f77ab50&gt;
                   here: &lt;RegistrationTool at /plone/portal_registration&gt;
                   container: &lt;RegistrationTool at /plone/portal_registration&gt;
                   root: &lt;Application at &gt;
                   traverse_subpath: []
                   user: &lt;SpecialUser 'Anonymous User'&gt;
                   default: &lt;DEFAULT&gt;
                   repeat: &lt;Products.PageTemplates.engine.RepeatDictWrapper object at 0x7f6e8ef27840&gt;
                   loop: {}
                   target_language: None
                   translate: &lt;function BaseTemplate.render.&lt;locals&gt;.translate at 0x7f6e8ea423a0&gt;
                   attrs: {}
                   lt: '&lt;'
                   gt: '&gt;'
                   member: &lt;Products.PlonePAS.tools.memberdata.MemberData object at 0x7f6e9f415580&gt;
                   reset: {'randomstring': '6ef4c60fae43411394ea738744708126', 'expires': datetime.datetime(2022, 1, 1, 19, 34, 25, 661749), 'userid': 'howard'}
                   email_from_name: None
                   fullname: 'Howard Zinn'

So this fix seems appropriate regardless of the isolation issue.

Files changed:
M CHANGES.rst
M src/plone/volto/patches.py
Repository: plone.volto

Branch: refs/heads/main
Date: 2021-12-28T14:40:35-08:00
Author: Ross Patterson (rpatterson) <me@rpatterson.net>
Commit: https://github.com/plone/plone.volto/commit/c2d79db8046e6f09c37be358187133c052d0c927

fix(deps): Missing direct dependency/requirement

Files changed:
M setup.py
Repository: plone.volto

Branch: refs/heads/main
Date: 2022-01-20T17:03:41+01:00
Author: Víctor Fernández de Alba (sneridagh) <sneridagh@gmail.com>
Commit: https://github.com/plone/plone.volto/commit/fd0c031af76e6dad25a89ef386bf4c90eb82e181

Merge branch 'main' into test-fix-frontend-domain-none

Files changed:
A src/plone/volto/content.py
A src/plone/volto/default_homepage/__init__.py
A src/plone/volto/default_homepage/default.py
A src/plone/volto/default_homepage/demo.py
A src/plone/volto/default_homepage/lrf.py
A src/plone/volto/locales/es/LC_MESSAGES/plone.volto.po
A src/plone/volto/locales/eu/LC_MESSAGES/plone.volto.po
A src/plone/volto/profiles.zcml
A src/plone/volto/profiles/default/types/Collection.xml
A src/plone/volto/profiles/default/types/Event.xml
A src/plone/volto/profiles/default/types/News_Item.xml
M .gitignore
M CHANGES.rst
M README.rst
M base.cfg
M setup.py
M src/plone/volto/configure.zcml
M src/plone/volto/coresandbox/example.py
M src/plone/volto/dependencies.zcml
M src/plone/volto/interfaces.py
M src/plone/volto/patches.py
M src/plone/volto/profiles/default/metadata.xml
M src/plone/volto/profiles/default/types.xml
M src/plone/volto/profiles/default/types/Document.xml
M src/plone/volto/setuphandlers.py
M src/plone/volto/tests/test_setup.py
M src/plone/volto/upgrades.py
M src/plone/volto/upgrades.zcml
M src/plone/volto/vocabularies/subject.py
D src/plone/volto/profiles/default/types/Plone_Site.xml
Repository: plone.volto

Branch: refs/heads/main
Date: 2022-01-21T17:43:35+01:00
Author: Víctor Fernández de Alba (sneridagh) <sneridagh@gmail.com>
Commit: https://github.com/plone/plone.volto/commit/df86ae7f5de0149db4faccb5367c2f1bc6a9cf6a

Merge pull request #39 from plone/test-fix-frontend-domain-none

test(settings): Isolation w/ frontend_domain None

Files changed:
M CHANGES.rst
M setup.py
M src/plone/volto/patches.py