[fc] Repository: plone.app.theming
Branch: refs/heads/master
Date: 2020-06-10T23:05:22+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.theming/commit/64f4fec7bdae01dad8e715fca357b47397bf1e44

Added test for saving the advanced control panel.

This should help surface some `WrongType`  exceptions.

Files changed:
M src/plone/app/theming/tests/test_controlpanel.py
Repository: plone.app.theming

Branch: refs/heads/master
Date: 2020-06-10T23:07:58+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.theming/commit/865d37bda7dc73af66c196637a067be80bbaf884

Revert "Do not call processInputs."

This reverts commit dd4f7fc15d1d7ec890780b1f64ad433efaf4fb9e.

Files changed:
M src/plone/app/theming/browser/controlpanel.py
M src/plone/app/theming/browser/mapper.py
Repository: plone.app.theming

Branch: refs/heads/master
Date: 2020-06-10T23:17:02+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.theming/commit/12e382fa754fbf8f9e32698a697ce5021c9b4505

Import processInputs conditionally.

Files changed:
M src/plone/app/theming/browser/controlpanel.py
M src/plone/app/theming/browser/mapper.py
Repository: plone.app.theming

Branch: refs/heads/master
Date: 2020-06-10T23:21:40+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.theming/commit/e6d07c7000189a8844038325b72cdb61b1c1cf64

Do not make a string from custom_css.

The field is SourceText, which is unicode on Python 2, and str on Python 3.
So on Python 2, creating a string of it results in a WrongType error.
See https://github.com/plone/plone.app.theming/issues/183

Files changed:
M src/plone/app/theming/browser/controlpanel.py
Repository: plone.app.theming

Branch: refs/heads/master
Date: 2020-06-10T23:28:43+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.theming/commit/9c64d46bf54ebf5259a8ccf400d329991a2cb70a

Revert "fix hostnameBlacklist (Theming ControlPanel) in Py3"

This reverts commit d6db78dbb930837c296aae87cea16bacde391a9b.

No longer needed after calling processInputs.

Files changed:
M src/plone/app/theming/browser/controlpanel.pt
M src/plone/app/theming/browser/controlpanel.py
Repository: plone.app.theming

Branch: refs/heads/master
Date: 2020-06-10T23:38:32+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.theming/commit/5cb479cb9e8ed343de15ce48ba35853fb8d1e0fd

Added changelog entry for #183 fix.

Files changed:
A news/183.bugfix
Repository: plone.app.theming

Branch: refs/heads/master
Date: 2020-06-11T10:11:25+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.theming/commit/a360731d9a56f506480a1146965ac1299f0d82e7

Added upgrade step to reload the theming registry.

Otherwise when you upgrade from Plone 5.2.1, and try to save the theming control panel, you get an error:

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 359, in publish_module
  Module ZPublisher.WSGIPublisher, line 262, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module plone.app.theming.browser.controlpanel, line 65, in __call__
  Module plone.app.theming.browser.controlpanel, line 215, in update
  Module plone.registry.recordsproxy, line 59, in __setattr__
AttributeError: custom_css_timestamp
```

Files changed:
M src/plone/app/theming/configure.zcml
M src/plone/app/theming/profiles/default/metadata.xml
Repository: plone.app.theming

Branch: refs/heads/master
Date: 2020-06-11T20:31:42+02:00
Author: Maurits van Rees (mauritsvanrees) <m.van.rees@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.theming/commit/fdbb576850211748bf523d04dfb6382f36bfa08a

Merge pull request #184 from plone/maurits/issue-183-save-advanced-controlpanel-wrongtype

Call processInputs when available, fixing WrongType

Files changed:
A news/183.bugfix
M src/plone/app/theming/browser/controlpanel.pt
M src/plone/app/theming/browser/controlpanel.py
M src/plone/app/theming/browser/mapper.py
M src/plone/app/theming/configure.zcml
M src/plone/app/theming/profiles/default/metadata.xml
M src/plone/app/theming/tests/test_controlpanel.py