[fc] Repository: plone.distribution
Branch: refs/heads/main
Date: 2025-04-05T10:38:24-03:00
Author: Érico Andrei (ericof) <ericof@gmail.com>
Commit: https://github.com/plone/plone.distribution/commit/193dbbcba7e6f77aa4dd026ea14d8ae846e6f5a3

Add package attribution to Distribution class (Fixes #114) (#115)

* Add package attribution to Distribution class (Fixes #114)

* Add attribute to class

* build-system: restrict to setuptools&lt;77.

This avoids an error while releasing:

```
InvalidDistribution: Metadata is missing required fields: Name, Version
```

Alternatively, we would need to update `constraints.txt` to use Plone 6.0-dev (or 6.1-dev), which has a newer version pin for `twine`:
`twine` 6.1.0+ can handle the metadata generated by setuptools 77.

O, now with still twine 5, I get an error when running `twine check` using Python 3.13:

```
  File "/Users/maurits/community/plone-coredev/6.2/src/plone.distribution/.tox/release-check/lib/python3.13/site-packages/twine/commands/check.py", line 16, in &lt;module&gt;
    import cgi
ModuleNotFoundError: No module named 'cgi'
```

On 3.13 you need `legacy-cgi`.  Maybe twine 5 was missing this dependency?  But when using the latest twine it is fine.
So let's use 6.0-dev so that we get the correct twine version...

---------

Co-authored-by: Maurits van Rees &lt;maurits@vanrees.org&gt;

Files changed:
A news/114.feature
M CHANGES.md
M constraints.txt
M pyproject.toml
M src/plone/distribution/core.py
M src/plone/distribution/metaconfigure.py
M tests/api/test_api_distribution.py