[fc] Repository: Products.CMFFormController
Branch: refs/heads/master
Date: 2020-02-12T11:12:00+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFFormController/commit/a9263705366fb4fedb1aee51c4c47e24ff570241

Fixed DeprecationWarning for InitializeClass.

"InitializeClass is deprecated. Please import from AccessControl.class_init."
Works now with Zope 5

Files changed:
A news/22.bugfix
M Products/CMFFormController/BaseControllerPageTemplate.py
M Products/CMFFormController/ControllerBase.py
M Products/CMFFormController/ControllerPageTemplate.py
M Products/CMFFormController/ControllerState.py
M Products/CMFFormController/FSControllerBase.py
M Products/CMFFormController/FSControllerPageTemplate.py
M Products/CMFFormController/FSControllerPythonScript.py
M Products/CMFFormController/FSControllerValidator.py
M Products/CMFFormController/FormAction.py
M Products/CMFFormController/FormController.py
M Products/CMFFormController/FormValidator.py
M Products/CMFFormController/Script.py
M Products/CMFFormController/exportimport/formcontroller.py
M setup.py
Repository: Products.CMFFormController

Branch: refs/heads/master
Date: 2020-02-12T11:15:41+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFFormController/commit/e568f29244a43d37fcdb41fbcca4a31263f9e4a6

Fixed AttributeError: 'dict_keys' object has no attribute 'sort' on Python 3.

Fixes https://github.com/plone/Products.CMFFormController/issues/21

Files changed:
A news/21.bugfix
M Products/CMFFormController/FormController.py
Repository: Products.CMFFormController

Branch: refs/heads/master
Date: 2020-02-14T14:25:50+01:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/Products.CMFFormController/commit/38bcf1b82f65253264dfe853d6029c0b9ecbb89e

Merge pull request #23 from plone/maurits-zope5-compat

Fixed Zope 5 and Python 3 compatibility

Files changed:
A news/21.bugfix
A news/22.bugfix
M Products/CMFFormController/BaseControllerPageTemplate.py
M Products/CMFFormController/ControllerBase.py
M Products/CMFFormController/ControllerPageTemplate.py
M Products/CMFFormController/ControllerState.py
M Products/CMFFormController/FSControllerBase.py
M Products/CMFFormController/FSControllerPageTemplate.py
M Products/CMFFormController/FSControllerPythonScript.py
M Products/CMFFormController/FSControllerValidator.py
M Products/CMFFormController/FormAction.py
M Products/CMFFormController/FormController.py
M Products/CMFFormController/FormValidator.py
M Products/CMFFormController/Script.py
M Products/CMFFormController/exportimport/formcontroller.py
M setup.py