Downgrade pip, upgrade setuptools.
With `pip>=22.2` that we have been using, buildout fails to check the python-requires of a package, so you may get incompatible versions.
See https://github.com/buildout/buildout/issues/613
A fix is underway, but that can take a while.
So downgrade pip to 21.
Do try the latest setuptools.

The error you get is:

```
$ bin/buildout
Requires-Python support missing.

Traceback (most recent call last):
  File "/Users/maurits/community/plone-coredev/6.0/lib/python3.10/site-packages/zc/buildout/patches.py", line 52, in patch_PackageIndex
    from pip._internal.index.collector import HTMLPage
ImportError: cannot import name 'HTMLPage' from 'pip._internal.index.collector' (/Users/maurits/shared-eggs/cp310/pip-22.2-py3.10.egg/pip/_internal/index/collector.py)
```

Buildout *does* continue after that, but as said: it is missing the python-requires functionality.