[fc] Repository: plone.rest
Branch: refs/heads/master
Date: 2021-02-10T15:49:52+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.rest/commit/8d1ed68254ed2513b7bc02bee9dce71408d4f616

Explicitly make allow_credentials required in CORS policy.

This was the default for Bool fields until and including zope.schema 6.0.1.
In 6.1.0 this changed.
Since we have a default in the field definition, it does not look like any changes are needed for people using `plone.rest`.

Without this, we get errors like this on Jenkins with Plone coredev 6:

```
$ bin/test -s plone.rest
...
  File "/Users/maurits/shared-eggs/cp38/zope.configuration-4.4.0-py3.8.egg
/zope/configuration/config.py", line 869, in finish
    actions = self.handler(context, **args)
zope.configuration.xmlconfig.ZopeXMLConfigurationError:
File "/Users/maurits/community/plone-coredev/6.0/src/plone.rest/src/plone/rest/testing.zcml", line 163.2-167.6
    TypeError: cors_policy_directive() missing 1 required positional argument: 'allow_credentials'
```

See https://github.com/zopefoundation/zope.schema/issues/104#issuecomment-776747141

Files changed:
A news/104.bugfix
M src/plone/rest/zcml.py
Repository: plone.rest

Branch: refs/heads/master
Date: 2021-02-10T17:48:27+01:00
Author: Maurits van Rees (mauritsvanrees) <m.van.rees@zestsoftware.nl>
Commit: https://github.com/plone/plone.rest/commit/cc8e7b3e6e3711b5a5c8138103881380f06746a6

Merge pull request #115 from plone/maurits/allow-credentials-required

Explicitly make allow_credentials required in CORS policy.

Files changed:
A news/104.bugfix
M src/plone/rest/zcml.py