[fc] Repository: plone.dexterity
Branch: refs/heads/master
Date: 2022-07-01T10:46:54+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.dexterity/commit/ab903884fff5c021a37982952b60686e94da95a1

Tests; fix AttributeError: 'Dummy' object has no attribute 'contentIds'.

In coredev, when you run `bin/test -u`, all is well.
When you run `bin/test -s plone.dexterity`, with or without `-u`, one test fails:

```
Error in test testAddContentToContainer_preserves_existing_id (plone.dexterity.tests.test_utils.TestUtils)
Traceback (most recent call last):
  File "/Users/maurits/.pyenv/versions/3.10.4/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/maurits/.pyenv/versions/3.10.4/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/Users/maurits/.pyenv/versions/3.10.4/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.dexterity/plone/dexterity/tests/test_utils.py", line 83, in testAddContentToContainer_preserves_existing_id
    item = addContentToContainer(container, item, checkConstraints=False)
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.dexterity/plone/dexterity/utils.py", line 175, in addContentToContainer
    name = INameChooser(container).chooseName(name, object)
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.content/plone/app/content/namechooser.py", line 55, in chooseName
    return self._findUniqueName(name, obj)
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.content/plone/app/content/namechooser.py", line 64, in _findUniqueName
    if not check_id(name, required=1):
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.content/plone/app/content/namechooser.py", line 104, in do_Plone_check
    return check_id(obj, newid, required=required, contained_by=parent)
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.base/src/plone/base/utils.py", line 412, in check_id
    result = _check_for_collision(contained_by, id, **kwargs)
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.base/src/plone/base/utils.py", line 476, in _check_for_collision
    if portal and cid in portal.contentIds():
AttributeError: 'Dummy' object has no attribute 'contentIds'
```

So the portal here is a Dummy from our tests.  No idea why there is a difference in how we run the tests, especially without layers.
Anyway, fixed by adding a `contentIds` method to our Dummy class, returning an empty list.

Files changed:
M plone/dexterity/tests/case.py
Repository: plone.dexterity

Branch: refs/heads/master
Date: 2022-07-01T11:27:00+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.dexterity/commit/79e127bd762c7b53081e26779d5d6387b233a0ea

Removed Plone 5.2 related classifiers.

Files changed:
M setup.py
Repository: plone.dexterity

Branch: refs/heads/master
Date: 2022-07-01T13:02:28+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.dexterity/commit/2825faaba3f48dcf56b0462780185fbfc0449bed

Add Makefile and code-analysis github action.

This uses the plone/code-quality docker image.  Really fast after the first run.
On Mac: `brew install --cask docker`, then start Docker Desktop, or have it start always in the background or something.

I made it easy: you can only do `make format` and `make lint`.
There is only one gh-actions job, which runs each linter in a separate step.

I did not want to create a pre-commit hook, but you could.

Files changed:
A .github/workflows/code-analysis.yml
A Makefile
M pyproject.toml
Repository: plone.dexterity

Branch: refs/heads/master
Date: 2022-07-01T13:05:44+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.dexterity/commit/b8511931dee94d4bcae6ccdf0cc4081c1d0d8cf3

Ran 'make format'

Files changed:
M plone/dexterity/browser/add.py
M plone/dexterity/browser/base.py
M plone/dexterity/browser/configure.zcml
M plone/dexterity/browser/edit.py
M plone/dexterity/browser/fti.py
M plone/dexterity/configure.zcml
M plone/dexterity/content.py
M plone/dexterity/fti.py
M plone/dexterity/interfaces.py
M plone/dexterity/meta.zcml
M plone/dexterity/schema.py
M plone/dexterity/tests/case.py
M plone/dexterity/tests/schemata.py
M plone/dexterity/tests/test.xml
M plone/dexterity/tests/test_behavior.py
M plone/dexterity/tests/test_content.py
M plone/dexterity/tests/test_factory.py
M plone/dexterity/tests/test_fti.py
M plone/dexterity/tests/test_primary.py
M plone/dexterity/tests/test_schema.py
M plone/dexterity/tests/test_schema_cache.py
M plone/dexterity/tests/test_security.py
M plone/dexterity/tests/test_utils.py
M plone/dexterity/tests/test_views.py
M plone/dexterity/tests/test_webdav.py
Repository: plone.dexterity

Branch: refs/heads/master
Date: 2022-07-01T13:07:33+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.dexterity/commit/ca4a8df883cdf35e5e4159d206667279fafb6ebd

Removed BBB Py 2.7 import with bare except.

Files changed:
M plone/dexterity/filerepresentation.py
Repository: plone.dexterity

Branch: refs/heads/master
Date: 2022-07-01T13:12:52+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.dexterity/commit/67c95d914561cee787d3aafc174905eae7617f1b

Removed unused imports.

'make lint' now finishes without error.

Files changed:
M plone/dexterity/browser/edit.py
M plone/dexterity/schema.py
M plone/dexterity/tests/case.py
M plone/dexterity/tests/test_webdav.py
Repository: plone.dexterity

Branch: refs/heads/master
Date: 2022-07-01T13:18:32+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.dexterity/commit/971009083c7a833edacb1b4a8778a995f00618cf

pyupgrade --py37-plus

Files changed:
M plone/__init__.py
M plone/dexterity/__init__.py
M plone/dexterity/bbb.py
M plone/dexterity/behavior.py
M plone/dexterity/browser/__init__.py
M plone/dexterity/browser/add.py
M plone/dexterity/browser/base.py
M plone/dexterity/browser/edit.py
M plone/dexterity/browser/fti.py
M plone/dexterity/browser/traversal.py
M plone/dexterity/browser/view.py
M plone/dexterity/content.py
M plone/dexterity/events.py
M plone/dexterity/exportimport.py
M plone/dexterity/factory.py
M plone/dexterity/filerepresentation.py
M plone/dexterity/fti.py
M plone/dexterity/i18n.py
M plone/dexterity/interfaces.py
M plone/dexterity/primary.py
M plone/dexterity/schema.py
M plone/dexterity/tests/__init__.py
M plone/dexterity/tests/case.py
M plone/dexterity/tests/schemata.py
M plone/dexterity/tests/test_behavior.py
M plone/dexterity/tests/test_content.py
M plone/dexterity/tests/test_content_integration.py
M plone/dexterity/tests/test_exportimport.py
M plone/dexterity/tests/test_factory.py
M plone/dexterity/tests/test_fti.py
M plone/dexterity/tests/test_primary.py
M plone/dexterity/tests/test_schema.py
M plone/dexterity/tests/test_schema_cache.py
M plone/dexterity/tests/test_security.py
M plone/dexterity/tests/test_synchronize.py
M plone/dexterity/tests/test_utils.py
M plone/dexterity/tests/test_views.py
M plone/dexterity/tests/test_webdav.py
M plone/dexterity/utils.py
M setup.py
Repository: plone.dexterity

Branch: refs/heads/master
Date: 2022-07-01T13:19:13+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.dexterity/commit/8bda96d957ed0958b98aba24a47b7c89067f1397

make format

Files changed:
M plone/dexterity/browser/traversal.py
M plone/dexterity/content.py
M plone/dexterity/tests/test_webdav.py
Repository: plone.dexterity

Branch: refs/heads/master
Date: 2022-07-01T13:31:05+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.dexterity/commit/271e73e0685e0f799cbd8a74dc613f584d395aaf

Removed six and mock.

Files changed:
M plone/dexterity/content.py
M plone/dexterity/exportimport.py
M plone/dexterity/filerepresentation.py
M plone/dexterity/fti.py
M plone/dexterity/schema.py
M plone/dexterity/tests/case.py
M plone/dexterity/tests/test_content.py
M plone/dexterity/tests/test_factory.py
M plone/dexterity/tests/test_fti.py
M plone/dexterity/tests/test_primary.py
M plone/dexterity/tests/test_schema.py
M plone/dexterity/tests/test_schema_cache.py
M plone/dexterity/tests/test_security.py
M plone/dexterity/tests/test_utils.py
M plone/dexterity/tests/test_views.py
M plone/dexterity/tests/test_webdav.py
M plone/dexterity/utils.py
M setup.py
Repository: plone.dexterity

Branch: refs/heads/master
Date: 2022-07-01T13:50:01+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.dexterity/commit/1d04c30ac43f5de08f6b1be5dbb8b258c9086ee6

HAS_WEBDAV is always True in Zope 5.

Removed the conditional code.
Removed `bbb.py`, which was only used internally.

Files changed:
M plone/dexterity/browser/traversal.py
M plone/dexterity/filerepresentation.py
M plone/dexterity/tests/test_webdav.py
D plone/dexterity/bbb.py
Repository: plone.dexterity

Branch: refs/heads/master
Date: 2022-07-01T13:50:27+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.dexterity/commit/f91bb33bd3d7407e456892eb3891bd17f5278019

Removed conditional import of IContentType from zope.app.content.

Always use our own interface.

Files changed:
M plone/dexterity/interfaces.py
Repository: plone.dexterity

Branch: refs/heads/master
Date: 2022-07-01T13:52:13+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.dexterity/commit/b9ddfcbc43cc187228f97acf534cc8f749750240

Removed unneeded zope.location dependency.

Files changed:
M setup.py
Repository: plone.dexterity

Branch: refs/heads/master
Date: 2022-07-01T13:54:41+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.dexterity/commit/abb9e38ec50a86374dc3be0fd8d0e593d89d2b7f

Require at least Python 3.7.

Files changed:
M setup.py
Repository: plone.dexterity

Branch: refs/heads/master
Date: 2022-07-01T13:56:37+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.dexterity/commit/e8326a72ca3e0f686d2fae8b10b5aa748ab29c4e

Avoid DeprecationWarning for IConstrainTypes.

Files changed:
M plone/dexterity/content.py
M plone/dexterity/tests/test_content.py
Repository: plone.dexterity

Branch: refs/heads/master
Date: 2022-07-01T14:14:27+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.dexterity/commit/b2edb91b276e4c9f9b8df7997380d884eb29aef8

Bootstrap 5 button classes in add/edit.

Files changed:
M plone/dexterity/browser/add.py
M plone/dexterity/browser/edit.py
Repository: plone.dexterity

Branch: refs/heads/master
Date: 2022-07-01T14:16:33+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.dexterity/commit/fca366d9627ebcee9aff3515bad0355c5788e568

add news snippets

Files changed:
A news/161.breaking.1
A news/161.breaking.2
A news/161.bugfix
Repository: plone.dexterity

Branch: refs/heads/master
Date: 2022-07-01T23:30:05+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.dexterity/commit/6ab1f7ee9c5e5ca128452abc134fecb0c2ee9557

Merge pull request #168 from plone/maurits-modernize

Modernize, remove outdated code, add code-analysis checks

Files changed:
A .github/workflows/code-analysis.yml
A Makefile
A news/161.breaking.1
A news/161.breaking.2
A news/161.bugfix
M plone/__init__.py
M plone/dexterity/__init__.py
M plone/dexterity/behavior.py
M plone/dexterity/browser/__init__.py
M plone/dexterity/browser/add.py
M plone/dexterity/browser/base.py
M plone/dexterity/browser/configure.zcml
M plone/dexterity/browser/edit.py
M plone/dexterity/browser/fti.py
M plone/dexterity/browser/traversal.py
M plone/dexterity/browser/view.py
M plone/dexterity/configure.zcml
M plone/dexterity/content.py
M plone/dexterity/events.py
M plone/dexterity/exportimport.py
M plone/dexterity/factory.py
M plone/dexterity/filerepresentation.py
M plone/dexterity/fti.py
M plone/dexterity/i18n.py
M plone/dexterity/interfaces.py
M plone/dexterity/meta.zcml
M plone/dexterity/primary.py
M plone/dexterity/schema.py
M plone/dexterity/tests/__init__.py
M plone/dexterity/tests/case.py
M plone/dexterity/tests/schemata.py
M plone/dexterity/tests/test.xml
M plone/dexterity/tests/test_behavior.py
M plone/dexterity/tests/test_content.py
M plone/dexterity/tests/test_content_integration.py
M plone/dexterity/tests/test_exportimport.py
M plone/dexterity/tests/test_factory.py
M plone/dexterity/tests/test_fti.py
M plone/dexterity/tests/test_primary.py
M plone/dexterity/tests/test_schema.py
M plone/dexterity/tests/test_schema_cache.py
M plone/dexterity/tests/test_security.py
M plone/dexterity/tests/test_synchronize.py
M plone/dexterity/tests/test_utils.py
M plone/dexterity/tests/test_views.py
M plone/dexterity/tests/test_webdav.py
M plone/dexterity/utils.py
M pyproject.toml
M setup.py
D plone/dexterity/bbb.py