Fixed pin for pip on Py2, and typing on Py 3.
The Zope 4.6.3 release pins pip at 21.1.1, which is incompatible with Python 2.
And it pins typing on all Python versions, but pip cannot install it on Py 3.5+.
Which is fine, but my tox release setup cannot deal with it, because it tries to let pip download packages, but it fails.

Error in 'tox -c release/tox.ini -e downloads2':

```
ERROR: Could not find a version that satisfies the requirement pip==21.1.1 (from -r constraints.txt (line 198)) (from versions: 0.2, 0.2.1, 0.3, 0.3.1, 0.4, 0.5, 0.5.1, 0.6, 0.6.1, 0.6.2, 0.6.3, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.8.2, 0.8.3, 1.0, 1.0.1, 1.0.2, 1.1, 1.2, 1.2.1, 1.3, 1.3.1, 1.4, 1.4.1, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 6.0, 6.0.1, 6.0.2, 6.0.3, 6.0.4, 6.0.5, 6.0.6, 6.0.7, 6.0.8, 6.1.0, 6.1.1, 7.0.0, 7.0.1, 7.0.2, 7.0.3, 7.1.0, 7.1.1, 7.1.2, 8.0.0, 8.0.1, 8.0.2, 8.0.3, 8.1.0, 8.1.1, 8.1.2, 9.0.0, 9.0.1, 9.0.2, 9.0.3, 10.0.0b1, 10.0.0b2, 10.0.0, 10.0.1, 18.0, 18.1, 19.0, 19.0.1, 19.0.2, 19.0.3, 19.1, 19.1.1, 19.2, 19.2.1, 19.2.2, 19.2.3, 19.3, 19.3.1, 20.0, 20.0.1, 20.0.2, 20.1b1, 20.1, 20.1.1, 20.2b1, 20.2, 20.2.1, 20.2.2, 20.2.3, 20.2.4, 20.3b1, 20.3, 20.3.1, 20.3.2, 20.3.3, 20.3.4)
ERROR: No matching distribution found for pip==21.1.1 (from -r constraints.txt (line 198))
ERROR: InvocationError for command /Users/maurits/community/plone-coredev/py3/release/.tox/downloads2/bin/pip download -r constraints.txt --dest dist (exited with code 1)
```

Error in 'tox -c release/tox.ini -e downloads3':

```
ERROR: Could not find a version that satisfies the requirement typing==3.10.0.0 (from versions: 3.5.0b1, 3.5.0, 3.5.0.1, 3.5.1.0, 3.5.2.2, 3.5.3.0, 3.6.1, 3.6.2, 3.6.4, 3.6.6, 3.7.4, 3.7.4.1, 3.7.4.3)
ERROR: No matching distribution found for typing==3.10.0.0
ERROR: InvocationError for command /Users/maurits/community/plone-coredev/py3/release/.tox/downloads3/bin/pip download -r constraints.txt --dest dist (exited with code 1)
```