[fc] Repository: plone.autoinclude
Branch: refs/heads/main
Date: 2025-02-26T22:59:53+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.autoinclude/commit/523f8444ee800df2c2cdc0b7822a23587666fe22

Fix importing module with when module name differs from project name.

This can easily happen with `setuptools` 75.8.1, though maybe 75.8.2 fixes it.
Fixes https://github.com/plone/plone.autoinclude/issues/25

Files changed:
A news/25.bugfix
M src/plone/autoinclude/loader.py
Repository: plone.autoinclude

Branch: refs/heads/main
Date: 2025-02-26T22:59:53+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.autoinclude/commit/477f81ff5219bbeccf61528cdf543d019bd7e13e

Tox: do not set SETUPTOOLS_USE_DISTUTILS=stdlib in Buildout test env.

This was an old workaround for 'TypeError: dist must be a Distribution instance' on GHA.

Now suddenly this old workaround causes an error, on Python 3.12+:

```
$ tox -e buildout
buildout: commands_pre[0]&gt; python -m pip list
Package     Version
----------- -------
packaging   24.2
pip         25.0.1
setuptools  75.8.0
wheel       0.45.1
zc.buildout 4.0
buildout: commands_pre[1]&gt; .tox/buildout/bin/buildout -nc /Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude/buildout.cfg buildout:directory=/Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude/.tox/buildout
/Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude/.tox/buildout/lib/python3.12/site-packages/_distutils_hack/__init__.py:53: UserWarning: Reliance on distutils from stdlib is deprecated. Users must rely on setuptools to provide the distutils module. Avoid importing distutils or import setuptools first, and avoid setting SETUPTOOLS_USE_DISTUTILS=stdlib. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(
Traceback (most recent call last):
  File "/Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude/.tox/buildout/bin/buildout", line 5, in &lt;module&gt;
    from zc.buildout.buildout import main
  File "/Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude/.tox/buildout/lib/python3.12/site-packages/zc/buildout/__init__.py", line 21, in &lt;module&gt;
    import setuptools
  File "/Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude/.tox/buildout/lib/python3.12/site-packages/setuptools/__init__.py", line 24, in &lt;module&gt;
    from . import logging, monkey
  File "/Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude/.tox/buildout/lib/python3.12/site-packages/setuptools/logging.py", line 5, in &lt;module&gt;
    from . import monkey
  File "/Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude/.tox/buildout/lib/python3.12/site-packages/setuptools/monkey.py", line 13, in &lt;module&gt;
    import distutils.filelist
ModuleNotFoundError: No module named 'distutils'
```

Files changed:
M tox.ini
Repository: plone.autoinclude

Branch: refs/heads/main
Date: 2025-02-26T22:59:53+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.autoinclude/commit/7230122b825b6ce4a6674098b5004536e856aac0

Remove upper setuptools bound in test-packages.

This shows that the fix in our `loader.py` works.

Files changed:
M test-packages/ExampleCamelCase/pyproject.toml
M test-packages/example.addon/pyproject.toml
M test-packages/example.basetestpackage/pyproject.toml
M test-packages/example.different/pyproject.toml
M test-packages/example.different2/pyproject.toml
M test-packages/example.metaoverrides/pyproject.toml
M test-packages/example.multipleeps/pyproject.toml
M test-packages/example.plone-dash-addon/pyproject.toml
M test-packages/example.ploneaddon/pyproject.toml
M test-packages/example.ploneintegration/pyproject.toml
M test-packages/example.zopeaddon/pyproject.toml
M test-packages/example.zopeintegration/pyproject.toml
M test-packages/namespaceexample.native/pyproject.toml
M test-packages/namespaceexample.pkgutilns/pyproject.toml
Repository: plone.autoinclude

Branch: refs/heads/main
Date: 2025-02-27T10:14:10+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.autoinclude/commit/0b73ec64db02e4c32456493e5ea0e8f91dd37b8b

Merge pull request #30 from plone/maurits-issue-25-project-versus-module-name

Fix issue 25: project versus module name

Files changed:
A news/25.bugfix
M src/plone/autoinclude/loader.py
M test-packages/ExampleCamelCase/pyproject.toml
M test-packages/example.addon/pyproject.toml
M test-packages/example.basetestpackage/pyproject.toml
M test-packages/example.different/pyproject.toml
M test-packages/example.different2/pyproject.toml
M test-packages/example.metaoverrides/pyproject.toml
M test-packages/example.multipleeps/pyproject.toml
M test-packages/example.plone-dash-addon/pyproject.toml
M test-packages/example.ploneaddon/pyproject.toml
M test-packages/example.ploneintegration/pyproject.toml
M test-packages/example.zopeaddon/pyproject.toml
M test-packages/example.zopeintegration/pyproject.toml
M test-packages/namespaceexample.native/pyproject.toml
M test-packages/namespaceexample.pkgutilns/pyproject.toml
M tox.ini