[fc] Repository: plone.restapi
Branch: refs/heads/master
Date: 2021-11-23T07:25:51+01:00
Author: Wesley Barroso Lopes (wesleybl) <wesleybl@gmail.com>
Commit: https://github.com/plone/plone.restapi/commit/a2e5343338429fa3680044682fd5177035ba6d2f

Fix random failures in tests (#1270)

* Fix random failure in test_serialize_to_json_collection_include_items

When we don't have the sort_on parameter, it's not guaranteed that the
search result will always come in the same order. This was causing the
test to fail randomly. So we sort the titles before comparing the
result.

This fixes the error:

AssertionError: 'Document 2' != 'Document 1'

* Fix random failure in test_querystringsearch_complex

When we don't have the sort_on parameter, it's not guaranteed that the
search result will always come in the same order. This was causing the
test to fail randomly. So we add the sort_on parameter to ensure that
the result always comes in the same order.

This fixes the error:

AssertionError: 'Test Document 8' != 'Test Document 4'

Files changed:
M src/plone/restapi/tests/test_serializer.py
M src/plone/restapi/tests/test_services_querystringsearch.py