[fc] Repository: Products.CMFPlone
Branch: refs/heads/master
Date: 2026-03-23T21:46:23+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/2e3f3e7c1dfffd84c31ce0dc5ea621ca0e8094b9

MigrationTool: use @security.protected.

Less verbose.

Files changed:
M src/Products/CMFPlone/MigrationTool.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2026-03-23T23:39:53+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/7be82bc50500182005d2f5c6792bb11321c2672a

MigrationTool: make AddonList a utility.

Set `MigrationTool.profile`, default `Products.CMFPlone:plone`.
Add `MigrationTool.package_name` property method, taking the package name from the profile, so default `Products.CMFPlone`.

Files changed:
A news/4155.feature.md
M src/Products/CMFPlone/MigrationTool.py
M src/Products/CMFPlone/configure.zcml
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2026-03-23T23:39:54+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/e6a64d499594c6091c23d19848a7ede46510c0dc

MigrationTool: split 'upgrade' into multiple methods.

Files changed:
M src/Products/CMFPlone/MigrationTool.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2026-03-24T09:10:27+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/10b6588cb0bcdd02eda401c9814ac5bbe367c603

Define MigrationTool.setup property to get portal_setup.

Sometimes the acquisition chain is basically empty, and no tool can be found.  So use getSite.

Files changed:
M src/Products/CMFPlone/MigrationTool.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2026-03-24T09:29:44+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/7f82dddcc40289e6fb2b997699e9f15c0f7d36a2

Change `MigrationTool.profile` to a property method.

This returns the base profile id that was set in the `portal_setup` tool.  By default this would be `Products.CMFPlone:plone`.
With this, it should not be needed for `plone.distribution` to explicitly set `portal_migration.profile` as thought earlier.

Files changed:
M news/4155.feature.md
M src/Products/CMFPlone/MigrationTool.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2026-03-24T09:29:44+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/53a6362fa45d35afbefd1886bff917a39006c6e4

Fix MigrationTool.coreVersionsList.

You would get:

```
AttributeError: 'dict_items' object has no attribute 'sort'
```

But this method is not actually used in core Plone.

Files changed:
M src/Products/CMFPlone/MigrationTool.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2026-03-24T09:33:20+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/06fd09fb251d11b8de55a60ec177cea950ea355d

MigrationTool: use importlib.metadata.version.

Instead of `distribution("Zope").version` we can just call `version("Zope")`.
I imported `version as `dist_version` because we already use a `version` variable in some places.

Files changed:
M src/Products/CMFPlone/MigrationTool.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2026-03-24T09:39:31+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/ddbd218c133c82c79db9a6331b17e84d77b589a8

MigrationTool.coreVersions: only try Pillow.

For historical reasons we first tried `PIL`, then `PILwoTK`, then `Pillow`, then `_imaging`.
But these days only `Pillow` is enough.

Let's not fail when the package is not there.  Maybe someone wants to have a go at removing Pillow and using Thumbor instead.

Files changed:
M src/Products/CMFPlone/MigrationTool.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2026-03-24T10:16:16+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/0f645b01899c509f73d7a83c22ed62de2b9f8753

Remove handling of MigrationTool._version.

This seems to be support from an age before we were using GenericSetup profiles.

Files changed:
M src/Products/CMFPlone/MigrationTool.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2026-03-24T10:26:52+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/b47d837d614b4be6a605f28685fd978accaa6407

MigrationTool.getSoftwareVersion: return version of self.package_name.

Clarify some comments in a few methods that get or set versions.

Files changed:
M src/Products/CMFPlone/MigrationTool.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2026-03-24T10:55:51+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/0cdf6aeee275d5e3007878d5c6b2145023126ef4

In `MigrationTool.coreVersions` return `core_package` and `core_version`.

If `core_package` is not `Products.CMFPlone`, show this version in the overview control panel.

Files changed:
M news/4155.feature.md
M src/Products/CMFPlone/MigrationTool.py
M src/Products/CMFPlone/controlpanel/browser/overview.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2026-03-24T11:10:15+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/a7f84a4f76a69c19ad1b5086422e7b7892edae4e

MigrationTool.addon_list: fall back to addon list of CMFPlone.

Files changed:
M src/Products/CMFPlone/MigrationTool.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2026-03-24T11:42:31+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/7f42524cc8080ca8f9e5db799acf0641a20713d9

Add-on utility: add optional pre_addon_list.

The utility must have an `addon_list` property and optionally may have a `pre_addon_list`, which gets upgraded before the base profile upgrade.

Files changed:
M news/4155.feature.md
M src/Products/CMFPlone/MigrationTool.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2026-03-24T11:55:43+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/170b6dda3c0ecf30cfa9acb5e349d574add67cbf

Remove TestPortalCreation.testInstanceVersion

`portal_migration._version` is no longer set.

Files changed:
M src/Products/CMFPlone/tests/testPortalCreation.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2026-03-24T13:33:18+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/aa5faf9b47683efe9be74e767ffb0cfa51ae02cc

Add tests for MigrationTool changes.

Files changed:
M src/Products/CMFPlone/tests/testMigrationTool.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2026-03-24T13:42:34+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/e52fec1e934c5bd2b849d23b63733d0a01cc190f

MigrationTool: show core package also on plone-upgrade page.

Files changed:
M src/Products/CMFPlone/browser/templates/plone-upgrade.pt
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2026-03-24T16:12:10+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/fb16754c3801b592fa68ebe4f7721e3080bb0c63

Merge branch 'master' into maurits-migration-tool

Files changed:
A news/4059.bugfix.md
M src/Products/CMFPlone/profiles/default/actions.xml
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2026-03-24T16:31:17+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/833b626afe49d5048170665d4d9178bd2cafc13a

CP overview: more f-strings.

Files changed:
M src/Products/CMFPlone/controlpanel/browser/overview.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2026-03-24T16:34:55+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/3cd55407ca097585fd3d0ded8ef70be0cd7da189

Use new IAddonList from plone.base.

This needs https://github.com/plone/plone.base/pull/115

Files changed:
M src/Products/CMFPlone/MigrationTool.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2026-03-25T09:58:41+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@py76.be>
Commit: https://github.com/plone/Products.CMFPlone/commit/7e956df1b29894f0a97f6e5a39920c1826eb3ffb

Merge branch 'master' into maurits-migration-tool

Files changed:
A news/+contentbrowser_update.bugfix.md
M src/Products/CMFPlone/tests/robot/test_edit.robot
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2026-03-25T10:19:26+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@py76.be>
Commit: https://github.com/plone/Products.CMFPlone/commit/d8ef124194ff934dab6d36185c8c0b37501b1544

Merge pull request #4295 from plone/maurits-migration-tool

Refactor migration tool to need less subclassing

Files changed:
A news/4155.feature.md
M src/Products/CMFPlone/MigrationTool.py
M src/Products/CMFPlone/browser/templates/plone-upgrade.pt
M src/Products/CMFPlone/configure.zcml
M src/Products/CMFPlone/controlpanel/browser/overview.py
M src/Products/CMFPlone/tests/testMigrationTool.py
M src/Products/CMFPlone/tests/testPortalCreation.py