Temporarily pin back zope.interface to 5.5.2.
Or maybe do this permanently for Plone 6.0.
But it should only break for old code that no longer works anyway, using 'implements' and 'directlyProvides'.

See https://jenkins.plone.org/job/plone-6.0-python-3.11/527/testReport/junit/plone/portlets/uisupport_txt/

```
File "/home/jenkins/.buildout/eggs/cp311/plone.portlets-2.3.3-py3.11.egg/plone/portlets/uisupport.txt", line 19, in uisupport.txt
Failed example:
    from zope.interface import implements, Interface, directlyProvides
Exception raised:
    Traceback (most recent call last):
      File "/srv/python3.11/lib/python3.11/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest uisupport.txt[1]>", line 1, in <module>
        from zope.interface import implements, Interface, directlyProvides
    ImportError: cannot import name 'implements' from 'zope.interface' (/home/jenkins/.buildout/eggs/cp311/zope.interface-6.0-py3.11-linux-x86_64.egg/zope/interface/__init__.py)
----------------------------------------------------------------------
File "/home/jenkins/.buildout/eggs/cp311/plone.portlets-2.3.3-py3.11.egg/plone/portlets/uisupport.txt", line 50, in uisupport.txt
Failed example:
    directlyProvides(left, IFoo1)
Exception raised:
    Traceback (most recent call last):
      File "/srv/python3.11/lib/python3.11/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest uisupport.txt[20]>", line 1, in <module>
        directlyProvides(left, IFoo1)
    NameError: name 'directlyProvides' is not defined
```