requirements-test.txt: add three more packages.
Latest test run [failed](https://github.com/plone/buildout.coredev/actions/runs/17673021245/job/50228698148):

    ModuleNotFoundError: No module named 'plone.classicui'

Which is correct, because this package was not yet installed.