[fc] Repository: plone.namedfile
Branch: refs/heads/master
Date: 2022-07-14T12:32:40+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/1f14d3168183d05dcf00a0772f2e1e0025ba08b7

Get title from ImageScale class.

Prevents a traceback:

```
  File "/Users/maurits/clients/zeelandia/plone60/var/cache/e7f22b3d94223db6a4dc52ff402b3a33.py", line 184, in render
    __value = _static_4510349056('python',

    "scale.scale('image', scale='large').tag(css_class='img-responsive', alt='Alt')",

    econtext=econtext)(_static_4510348768(econtext, __zt_tmp))
  File "/Users/maurits/shared-eggs/cp39/zope.tales-5.1-py3.9.egg/zope/tales/pythonexpr.py", line 73, in __call__
    return eval(self._code, vars)
  File "&lt;string&gt;", line 1, in &lt;module&gt;
File "/Users/maurits/clients/zeelandia/plone60/develop/plone.namedfile/plone/namedfile/scaling.py", line 128, in tag
    title = self.context.Title()
AttributeError: 'SimpleViewClass from /Users/maurits/clients/zeelan' object has no attribute 'Title'
```

This is when generating a tag and you do not pass an explicit `alt` and `title`.
You could override this in special cases, but we try the following now, which should fit most use cases:

- First try `self.context.Title()` like before. This should work on all content items.
- Then try `self.context.title`, which may work for tiles with a title field, and also for most other items.
- Fall back to an empty string. I think most people prefer an empty alt or title instead of a missing image tag, or an error rendering the tile.

Files changed:
A news/128.bugfix
M plone/namedfile/scaling.py
M plone/namedfile/tests/test_scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-07-14T15:42:25+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/f851f654707d695337419196b7b7c76ee06825af

Merge pull request #129 from plone/maurits-custom-title

Get title from ImageScale class.

Files changed:
A news/128.bugfix
M plone/namedfile/scaling.py
M plone/namedfile/tests/test_scaling.py