[fc] Repository: plone.app.contenttypes Branch: refs/heads/master Date: 2016-04-12T13:43:14+02:00 Author: Martin Opstad Reistadbakk (martior) <martior@gmail.com> Commit: https://github.com/plone/plone.app.contenttypes/commit/7c2bd943f310be07d076ad3f74c39eb3735b2e2c
Encode the absolute_target_url as utf-8 string

This is to make sure url can be converted to string lower in the stack. If not you can get errors like:
Traceback (innermost last): 
Module ZPublisher.Publish, line 138, in publish 
Module ZPublisher.mapply, line 77, in mapply 
Module ZPublisher.Publish, line 48, in call_object 
Module plone.app.contenttypes.browser.link_redirect_view, line 56, in __call__ 
Module ZPublisher.HTTPResponse, line 609, in redirect 
Module ZPublisher.HTTPResponse, line 331, in setHeader 
Module ZPublisher.HTTPResponse, line 134, in _scrubHeader 
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 37: ordinal not in range(128)

Files changed:
M plone/app/contenttypes/browser/link_redirect_view.py
Repository: plone.app.contenttypes
Branch: refs/heads/master
Date: 2016-04-12T14:01:04+02:00
Author: Martin Opstad Reistadbakk (martior) <martior@gmail.com>
Commit: https://github.com/plone/plone.app.contenttypes/commit/bd7aa4b7f2419bd32d48db14a8d0c9c5e6976d89

Update CHANGES.rst

Files changed:
M CHANGES.rst
Repository: plone.app.contenttypes
Branch: refs/heads/master
Date: 2016-05-21T15:41:43+02:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/plone.app.contenttypes/commit/93c077f34adee3e331863c3da9e8e0a601106163

Merge pull request #345 from Blaastolen/master

Encode the absolute_target_url as utf-8 string

Files changed:
M CHANGES.rst
M plone/app/contenttypes/browser/link_redirect_view.py