[fc] Repository: Products.PortalTransforms Branch: refs/heads/master Date: 2015-08-04T13:32:39-05:00 Author: vangheem (vangheem) <vangheem@gmail.com> Commit: https://github.com/plone/Products.PortalTransforms/commit/95611534c94d24c0e5b2ee02b414b746ef21fbcd
fix error mis-configured transforms would cause:
  "AttributeError: 'NoneType' object has no attribute 'items'"

Files changed:
M CHANGES.rst
M Products/PortalTransforms/Transform.py
Repository: Products.PortalTransforms
Branch: refs/heads/master
Date: 2015-08-04T14:59:18-05:00
Author: Nathan Van Gheem (vangheem) <vangheem@gmail.com>
Commit: https://github.com/plone/Products.PortalTransforms/commit/810f6fd37354bd82d114d07ea49252efde9e5edc

Merge pull request #9 from plone/mis-configured-transforms-error

fix error mis-configured transforms would cause

Files changed:
M CHANGES.rst
M Products/PortalTransforms/Transform.py