[fc] Repository: Products.CMFEditions
Branch: refs/heads/master
Date: 2018-09-14T12:43:57+02:00
Author: Philip Bauer (pbauer) <bauer@starzel.de>
Commit: https://github.com/plone/Products.CMFEditions/commit/43f62f9f247217286b635957c1fbb32aff45e0eb

start migrating tests away from PloneTestCase

Files changed:
M Products/CMFEditions/StandardModifiers.py
M Products/CMFEditions/tests/DummyTools.py
M Products/CMFEditions/tests/base.py
M Products/CMFEditions/tests/test_ArchivistTool.py
M Products/CMFEditions/tests/test_ContentTypes.py
M Products/CMFEditions/tests/test_CopyModifyMergeRepositoryTool.py
M Products/CMFEditions/tests/test_IntegrationTests.py
M Products/CMFEditions/tests/test_KeepLastNVersionsTool.py
M Products/CMFEditions/tests/test_ModifierRegistryTool.py
M Products/CMFEditions/tests/test_ZVCStorageTool.py
M Products/CMFEditions/tests/test_versions_history_form.py
Repository: Products.CMFEditions

Branch: refs/heads/master
Date: 2018-09-14T12:43:57+02:00
Author: Philip Bauer (pbauer) <bauer@starzel.de>
Commit: https://github.com/plone/Products.CMFEditions/commit/3c7d2f23e5d7f0acd1d22fe17e1975b7e423b264

finish porting away from PloneTestCase

Files changed:
A Products/CMFEditions/testing.py
M Products/CMFEditions/tests/base.py
M Products/CMFEditions/tests/large_file_modifiers.txt
M Products/CMFEditions/tests/test_ATContentTypes.py
M Products/CMFEditions/tests/test_ATReferences.py
M Products/CMFEditions/tests/test_CopyModifyMergeRepositoryTool.py
M Products/CMFEditions/tests/test_doctests.py
Repository: Products.CMFEditions

Branch: refs/heads/master
Date: 2018-09-14T12:43:57+02:00
Author: Philip Bauer (pbauer) <bauer@starzel.de>
Commit: https://github.com/plone/Products.CMFEditions/commit/f8a98482cd01837bd73db6d73e3e907a29344073

do not run webdav_history.txt in py3 since it breaks following tests with:
ZODB.POSException.ConnectionStateError: Shouldn't load state for Products.PluggableAuthService.PluggableAuthService.PluggableAuthService 0x3984317ff5f25a28 when the connection is closed

Files changed:
M Products/CMFEditions/tests/test_doctests.py
Repository: Products.CMFEditions

Branch: refs/heads/master
Date: 2018-09-14T12:43:57+02:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/Products.CMFEditions/commit/6640143829e36d927b9b493120923c57f0e7664f

isort/formatting/security decorators

Files changed:
M Products/CMFEditions/ArchivistTool.py
M Products/CMFEditions/CopyModifyMergeRepositoryTool.py
M Products/CMFEditions/KeepLastNVersionsTool.py
M Products/CMFEditions/ModifierRegistryTool.py
M Products/CMFEditions/Modifiers.py
M Products/CMFEditions/Permissions.py
M Products/CMFEditions/ReferenceFactoriesTool.py
M Products/CMFEditions/StandardModifiers.py
M Products/CMFEditions/StorageMigrationSupport.py
M Products/CMFEditions/UniqueIdHandlerTool.py
M Products/CMFEditions/ZVCStorageTool.py
M Products/CMFEditions/__init__.py
M Products/CMFEditions/browser/__init__.py
M Products/CMFEditions/browser/utils.py
M Products/CMFEditions/browser/views.py
M Products/CMFEditions/exportimport/repository.py
M Products/CMFEditions/interfaces/IArchivist.py
M Products/CMFEditions/interfaces/IModifier.py
M Products/CMFEditions/interfaces/IRepository.py
M Products/CMFEditions/interfaces/IStorage.py
M Products/CMFEditions/interfaces/__init__.py
M Products/CMFEditions/setuphandlers.py
M Products/CMFEditions/skins/CMFEditions/checkUpToDate.py
M Products/CMFEditions/skins/CMFEditions/createTestHierarchy.py
M Products/CMFEditions/skins/CMFEditions/migrateStorage.py
M Products/CMFEditions/skins/CMFEditions/saveasnewversion.py
M Products/CMFEditions/subscriber.py
M Products/CMFEditions/tests/DummyTools.py
M Products/CMFEditions/tests/base.py
M Products/CMFEditions/tests/test_ATContentTypes.py
M Products/CMFEditions/tests/test_ATReferences.py
M Products/CMFEditions/tests/test_ArchivistTool.py
M Products/CMFEditions/tests/test_ContentTypes.py
M Products/CMFEditions/tests/test_CopyModifyMergeRepositoryTool.py
M Products/CMFEditions/tests/test_IntegrationTests.py
M Products/CMFEditions/tests/test_KeepLastNVersionsTool.py
M Products/CMFEditions/tests/test_ModifierRegistryTool.py
M Products/CMFEditions/tests/test_ZVCStorageTool.py
M Products/CMFEditions/tests/test_doctests.py
M Products/CMFEditions/tests/test_versions_history_form.py
M Products/CMFEditions/utilities.py
M setup.py
Repository: Products.CMFEditions

Branch: refs/heads/master
Date: 2018-09-14T12:43:57+02:00
Author: David Glick (davisagli) <david@glicksoftware.com>
Commit: https://github.com/plone/Products.CMFEditions/commit/84cbccb670ce20f1c1c873d424e5d645df504ef9

Fix decorators

Files changed:
M Products/CMFEditions/CopyModifyMergeRepositoryTool.py
Repository: Products.CMFEditions

Branch: refs/heads/master
Date: 2018-09-14T12:43:57+02:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/Products.CMFEditions/commit/12ed660be3e709fec911a3a6d2251711f18af34c

InitializeClass was moved to AccessControl.class_init

Files changed:
M Products/CMFEditions/ArchivistTool.py
M Products/CMFEditions/CopyModifyMergeRepositoryTool.py
M Products/CMFEditions/KeepLastNVersionsTool.py
M Products/CMFEditions/ModifierRegistryTool.py
M Products/CMFEditions/Modifiers.py
M Products/CMFEditions/ReferenceFactoriesTool.py
M Products/CMFEditions/StandardModifiers.py
M Products/CMFEditions/ZVCStorageTool.py
Repository: Products.CMFEditions

Branch: refs/heads/master
Date: 2018-09-14T12:43:57+02:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/Products.CMFEditions/commit/d1a746125aee20acc2f60d673e77d2bfe3ea9673

setDefaultRoles is deprecated. addPermission from AccessControl.Permission is used.

Files changed:
M Products/CMFEditions/Permissions.py
Repository: Products.CMFEditions

Branch: refs/heads/master
Date: 2018-09-14T12:43:57+02:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/Products.CMFEditions/commit/28166aca1290229e544eae499b4a6715005144bb

fix setup metadata

Files changed:
M setup.py
Repository: Products.CMFEditions

Branch: refs/heads/master
Date: 2018-09-14T12:44:26+02:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/Products.CMFEditions/commit/6ff2790c9629eea6fce95040d49c92180d17f727

note changes

Files changed:
M CHANGES.rst
Repository: Products.CMFEditions

Branch: refs/heads/master
Date: 2018-09-14T14:22:04+02:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/Products.CMFEditions/commit/e8100eab51474156249d7bdd58aa640979afc2a9

make doctest files rst

Files changed:
A Products/CMFEditions/tests/large_file_modifiers.rst
A Products/CMFEditions/tests/webdav_history.rst
M Products/CMFEditions/tests/test_doctests.py
D Products/CMFEditions/tests/large_file_modifiers.txt
D Products/CMFEditions/tests/webdav_history.txt
Repository: Products.CMFEditions

Branch: refs/heads/master
Date: 2018-09-14T14:29:32+02:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/Products.CMFEditions/commit/23cfc299523ee9741b1b78917b7e407d69ec1ede

catch expections and so do not depend on actual output

Files changed:
M Products/CMFEditions/tests/large_file_modifiers.rst
Repository: Products.CMFEditions

Branch: refs/heads/master
Date: 2018-09-14T14:53:44+02:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/Products.CMFEditions/commit/68ec8be06604c7e5f6c9963f8eb9ec25f0d0dd95

create a simple folder

Files changed:
M Products/CMFEditions/tests/webdav_history.rst
Repository: Products.CMFEditions

Branch: refs/heads/master
Date: 2018-09-23T07:30:00+02:00
Author: Philip Bauer (pbauer) <bauer@starzel.de>
Commit: https://github.com/plone/Products.CMFEditions/commit/6623cc7683051646903f7ee9400bf484814a32c3

fix AT testlayer

Files changed:
M Products/CMFEditions/tests/test_ATContentTypes.py
M Products/CMFEditions/tests/test_ATReferences.py
Repository: Products.CMFEditions

Branch: refs/heads/master
Date: 2018-09-23T23:51:19+02:00
Author: ale-rt (ale-rt) <alessandro.pisa@gmail.com>
Commit: https://github.com/plone/Products.CMFEditions/commit/24b49343d625d679b3d34fbd9ba0896da6c07b6d

Fix sorting in Python3

Files changed:
M Products/CMFEditions/exportimport/repository.py
Repository: Products.CMFEditions

Branch: refs/heads/master
Date: 2018-10-02T16:29:03+02:00
Author: ale-rt (ale-rt) <alessandro.pisa@gmail.com>
Commit: https://github.com/plone/Products.CMFEditions/commit/2ffabb990ad852d96bb63f09d361ab147864a196

Fix registration wrongly removed without archetypes

Files changed:
M Products/CMFEditions/configure.zcml
Repository: Products.CMFEditions

Branch: refs/heads/master
Date: 2018-10-03T19:29:48+02:00
Author: Philip Bauer (pbauer) <bauer@starzel.de>
Commit: https://github.com/plone/Products.CMFEditions/commit/d9622eb6be5b986102b068a67c97ad79a8626483

Fix webdav test (TODO: DX has too many history entries and a weird return code)

Files changed:
M Products/CMFEditions/tests/webdav_history.rst
Repository: Products.CMFEditions

Branch: refs/heads/master
Date: 2018-10-04T00:16:07+02:00
Author: Philip Bauer (pbauer) <bauer@starzel.de>
Commit: https://github.com/plone/Products.CMFEditions/commit/478019c1842381dc2654afecdce3f24629b23dda

add teardown to prevent spill to other testlayers

Files changed:
M Products/CMFEditions/tests/webdav_history.rst
Repository: Products.CMFEditions

Branch: refs/heads/master
Date: 2018-10-10T23:18:05+02:00
Author: Peter Mathis (petschki) <peter.mathis@kombinat.at>
Commit: https://github.com/plone/Products.CMFEditions/commit/0d428162ee2ecdf6eb55a47da4b6066be38770d3

Merge branch 'master' into python3

and resolve conflicts

Files changed:
A news/.gitkeep
A news/60.feature
A pyproject.toml
M CHANGES.rst
M MANIFEST.in
M Products/CMFEditions/browser/configure.zcml
M Products/CMFEditions/browser/templates/version_file_view.pt
M Products/CMFEditions/browser/templates/version_image_view.pt
M Products/CMFEditions/browser/views.py
M setup.py
D .gitattributes
Repository: Products.CMFEditions

Branch: refs/heads/master
Date: 2018-10-17T11:26:41+02:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/Products.CMFEditions/commit/f378669628595b167cf3ea3a5a9938b1ae24878c

Merge pull request #58 from plone/python3

migrate tests away from PloneTestCase

Files changed:
A Products/CMFEditions/testing.py
A Products/CMFEditions/tests/large_file_modifiers.rst
A Products/CMFEditions/tests/webdav_history.rst
M CHANGES.rst
M Products/CMFEditions/ArchivistTool.py
M Products/CMFEditions/CopyModifyMergeRepositoryTool.py
M Products/CMFEditions/KeepLastNVersionsTool.py
M Products/CMFEditions/ModifierRegistryTool.py
M Products/CMFEditions/Modifiers.py
M Products/CMFEditions/Permissions.py
M Products/CMFEditions/ReferenceFactoriesTool.py
M Products/CMFEditions/StandardModifiers.py
M Products/CMFEditions/StorageMigrationSupport.py
M Products/CMFEditions/UniqueIdHandlerTool.py
M Products/CMFEditions/ZVCStorageTool.py
M Products/CMFEditions/__init__.py
M Products/CMFEditions/browser/__init__.py
M Products/CMFEditions/browser/utils.py
M Products/CMFEditions/browser/views.py
M Products/CMFEditions/configure.zcml
M Products/CMFEditions/exportimport/repository.py
M Products/CMFEditions/interfaces/IArchivist.py
M Products/CMFEditions/interfaces/IModifier.py
M Products/CMFEditions/interfaces/IRepository.py
M Products/CMFEditions/interfaces/IStorage.py
M Products/CMFEditions/interfaces/__init__.py
M Products/CMFEditions/setuphandlers.py
M Products/CMFEditions/skins/CMFEditions/checkUpToDate.py
M Products/CMFEditions/skins/CMFEditions/createTestHierarchy.py
M Products/CMFEditions/skins/CMFEditions/migrateStorage.py
M Products/CMFEditions/skins/CMFEditions/saveasnewversion.py
M Products/CMFEditions/subscriber.py
M Products/CMFEditions/tests/DummyTools.py
M Products/CMFEditions/tests/base.py
M Products/CMFEditions/tests/test_ATContentTypes.py
M Products/CMFEditions/tests/test_ATReferences.py
M Products/CMFEditions/tests/test_ArchivistTool.py
M Products/CMFEditions/tests/test_ContentTypes.py
M Products/CMFEditions/tests/test_CopyModifyMergeRepositoryTool.py
M Products/CMFEditions/tests/test_IntegrationTests.py
M Products/CMFEditions/tests/test_KeepLastNVersionsTool.py
M Products/CMFEditions/tests/test_ModifierRegistryTool.py
M Products/CMFEditions/tests/test_ZVCStorageTool.py
M Products/CMFEditions/tests/test_doctests.py
M Products/CMFEditions/tests/test_versions_history_form.py
M Products/CMFEditions/utilities.py
M setup.py
D Products/CMFEditions/tests/large_file_modifiers.txt
D Products/CMFEditions/tests/webdav_history.txt