Switch to Products.CMFCore branch 2.2 instead of trunk. Avoids ImportError: cannot import name minimalpath
svn path=/buildouts/plone-coredev/branches/4.0/; revision=32387