[fc] Repository: plone.restapi
Branch: refs/heads/master
Date: 2020-11-09T16:07:51+01:00
Author: Wesley Barroso Lopes (wesleybl) <wesleybl@gmail.com>
Commit: https://github.com/plone/plone.restapi/commit/ebef527a95cba82af777f1dba45a7bd4c482eda3

Fix tests in Travis (#1013)

* gitignore

* Pin virtualenv = 20.0.35

Fix:

    Error: The requirement ('virtualenv&gt;=20.0.35') is not allowed by
your [versions] constraint (20.0.26)
virtualenv = 20.0.35

See:

https://travis-ci.org/github/plone/plone.restapi/jobs/742090297#L251

* Pinn pep517 = 0.9.1

Fix:

    Error: The requirement ('pep517&gt;=0.9') is not allowed by your
[versions] constraint (0.8.2)

See:

https://travis-ci.org/github/plone/plone.restapi/jobs/742090298#L250

* Use virtualenv in Travis tests

After the requirement virtualenv&gt;=20.0.35, the version of virtualenv
installed in Python 2 of Travis  started to conflict with the version
required in the buildout.

Fix:

    ContextualVersionConflict: (virtualenv 16.1.0
(/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages),
Requirement.parse('virtualenv&gt;=20.0.35'), set(['build']))

See:

https://travis-ci.org/github/plone/plone.restapi/jobs/742109179#L270

* Pinn importlib-metadata = 2.0.0

Fix:

    Error: The requirement ('importlib-metadata&gt;=1') is not allowed by
your [versions] constraint (0.23)

See:

https://travis-ci.org/github/plone/plone.restapi/jobs/742116716

Files changed:
A news/1012.bugfix
M .gitignore
M .travis.yml
M plone-5.2.x.cfg