[fc] Repository: plone.app.contenttypes
Branch: refs/heads/master
Date: 2021-01-12T15:02:25+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.contenttypes/commit/bdd7bf1ca7a9e89bcfddcab274a2aeecee8869ba

migrate_datetimefield: do nothing when old value is None.

This fixes `AttributeError: 'NoneType' object has no attribute 'asdatetime'`.

Files changed:
A news/584.bugfix
M plone/app/contenttypes/migration/field_migrators.py