[fc] Repository: plone.autoinclude
Branch: refs/heads/main
Date: 2025-09-22T15:31:38+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.autoinclude/commit/d126b2142b070ca7e17affee61647cdc34c8d3bf

Fix tests with buildout 4, and add tests with buildout 5.

This is needed because we get more namespace packages.
Error in the [scheduled test](https://github.com/plone/plone.autoinclude/actions/runs/17890615198/job/50870454923#step:5:97):

```
ModuleNotFoundError: No module named 'zc.recipe.testrunner'
```

Files changed:
A buildout5.cfg
A news/+ec0e6475.tests.rst
M .github/workflows/tests.yml
M buildout.cfg
M tox.ini
Repository: plone.autoinclude

Branch: refs/heads/main
Date: 2025-09-25T10:07:55+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.autoinclude/commit/0c6ec9c5263f4a9149c4cf289f7b8655be2da197

Merge pull request #38 from plone/maurits-fix-buildout-tests

Fix tests with buildout 4, and add tests with buildout 5.

Files changed:
A buildout5.cfg
A news/+ec0e6475.tests.rst
M .github/workflows/tests.yml
M buildout.cfg
M tox.ini