Checkout Products.TinyMCE and use branch 1.3.x.
Seems good, as we were using 1.3.6 so far and 1.4.0 has been released
several months ago, so apparently we do not want it in Plone
4.3.x.

Also, with Products.TinyMCE master plone.app.widgets gets pulled in
and you run into errors running the buildout:

  While:
    Updating test.
  Error: There is a version conflict.
  We already have: plone.app.jquery 1.7.2
  but plone.app.widgets 1.7.1 requires 'plone.app.jquery>=1.8.0'.