GHA: do not run 'make test' on windows.
Running `make` works, so that is good to know.
But there are several [test failures](https://github.com/plone/buildout.coredev/actions/runs/15449045805/job/43486236797?pr=1020):

```
  Ran 1961 tests with 17 failures, 4 errors and 1 skipped in 1 minutes 15.319 seconds.
```

Let me paste the complete test output (long):

```
Run tests using ./run-tests.sh
Running zope-testrunner --auto-color --auto-progress --auto-path -u -s borg.localrole -s collective.monkeypatcher -s diazo -s five.customerize -s five.intid -s plone.alterego -s plone.api -s plone.app.caching -s plone.app.content -s plone.app.contentlisting -s plone.app.contentmenu -s plone.app.contentrules -s plone.app.contenttypes -s plone.app.customerize -s plone.app.dexterity -s plone.app.discussion -s plone.app.event -s plone.app.i18n -s plone.app.intid -s plone.app.iterate -s plone.app.layout -s plone.app.linkintegrity -s plone.app.locales -s plone.app.lockingbehavior -s plone.app.multilingual -s plone.app.portlets -s plone.app.querystring -s plone.app.redirector -s plone.app.registry -s plone.app.relationfield -s plone.app.testing -s plone.app.textfield -s plone.app.theming -s plone.app.upgrade -s plone.app.users -s plone.app.uuid -s plone.app.versioningbehavior -s plone.app.viewletmanager -s plone.app.vocabularies -s plone.app.widgets -s plone.app.workflow -s plone.app.z3cform -s plone.autoform -s plone.batching -s plone.behavior -s plone.base -s plone.browserlayer -s plone.cachepurging -s plone.caching -s plone.classicui -s plone.contentrules -s plone.dexterity -s plone.distribution -s plone.event -s plone.exportimport -s plone.folder -s plone.formwidget.namedfile -s plone.i18n -s plone.indexer -s plone.intelligenttext -s plone.keyring -s plone.locking -s plone.memoize -s plone.namedfile -s plone.outputfilters -s plone.portlet.collection -s plone.portlet.static -s plone.portlets -s plone.protect -s plone.registry -s plone.resource -s plone.resourceeditor -s plone.rest -s plone.restapi -s plone.rfc822 -s plone.scale -s plone.schema -s plone.schemaeditor -s plone.session -s plone.staticresources -s plone.stringinterp -s plone.subrequest -s plone.supermodel -s plone.testing -s plone.theme -s plone.transformchain -s plone.uuid -s plone.volto -s plone.z3cform -s plonetheme.barceloneta -s Products.CMFDiffTool -s Products.CMFDynamicViewFTI -s Products.CMFEditions -s Products.CMFPlacefulWorkflow -s Products.CMFPlone -s Products.CMFUid -s Products.DateRecurringIndex -s Products.DCWorkflow -s Products.ExtendedPathIndex -s Products.GenericSetup -s Products.isurlinportal -s Products.MimetypesRegistry -s Products.PlonePAS -s Products.PluggableAuthService -s Products.PluginRegistry -s Products.PortalTransforms -s Products.statusmessages -s Products.ZopeVersionControl -s repoze.xmliter
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.

Error in test test_transform_filename (diazo.tests.test_wsgi.TestXSLTMiddleware.test_transform_filename)
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\unittest\case.py", line 57, in testPartExecutor
    yield
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\unittest\case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\unittest\case.py", line 579, in _callTestMethod
    if method() is not None:
  File "D:\a\buildout.coredev\buildout.coredev\.venv\Lib\site-packages\diazo\tests\test_wsgi.py", line 180, in test_transform_filename
    os.unlink(filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmp7wemmb49'

Failure in test test_rebuild (plone.app.redirector.tests.test_storage.TestStorage.test_rebuild)
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\unittest\case.py", line 57, in testPartExecutor
    yield
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\unittest\case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\unittest\case.py", line 579, in _callTestMethod
    if method() is not None:
  File "D:\a\buildout.coredev\buildout.coredev\.venv\Lib\site-packages\plone\app\redirector\tests\test_storage.py", line 517, in test_rebuild
    self.assertTrue(time1 < new_time < time2)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\unittest\case.py", line 715, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

Failure in test test_storage_date (plone.app.redirector.tests.test_storage.TestStorage.test_storage_date)
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\unittest\case.py", line 57, in testPartExecutor
    yield
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\unittest\case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\unittest\case.py", line 579, in _callTestMethod
    if method() is not None:
  File "D:\a\buildout.coredev\buildout.coredev\.venv\Lib\site-packages\plone\app\redirector\tests\test_storage.py", line 123, in test_storage_date
    self.assertTrue(time1 < info[1] < time2)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\unittest\case.py", line 715, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

Failure in test test_storage_update_mixed (plone.app.redirector.tests.test_storage.TestStorage.test_storage_update_mixed)
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\unittest\case.py", line 57, in testPartExecutor
    yield
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\unittest\case.py", line 623, in run

Failure in test testDetectPersistentSubObjectChange (Products.ZopeVersionControl.tests.testVersionControl.VersionControlTestsWithCommits.testDetectPersistentSubObjectChange)
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\unittest\case.py", line 57, in testPartExecutor
    yield
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\unittest\case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\unittest\case.py", line 579, in _callTestMethod
    if method() is not None:
  File "D:\a\buildout.coredev\buildout.coredev\.venv\Lib\site-packages\Products\ZopeVersionControl\tests\testVersionControl.py", line 643, in testDetectPersistentSubObjectChange
    self.assertTrue(repository.isResourceChanged(folder2))
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\unittest\case.py", line 715, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

Failure in test testIsResourceChanged (Products.ZopeVersionControl.tests.testVersionControl.VersionControlTestsWithCommits.testIsResourceChanged)
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\unittest\case.py", line 57, in testPartExecutor
    yield
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\unittest\case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\unittest\case.py", line 579, in _callTestMethod
    if method() is not None:
  File "D:\a\buildout.coredev\buildout.coredev\.venv\Lib\site-packages\Products\ZopeVersionControl\tests\testVersionControl.py", line 89, in testIsResourceChanged
    self.assertTrue(repository.isResourceChanged(document))
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\unittest\case.py", line 715, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

  Ran 1961 tests with 17 failures, 4 errors and 1 skipped in 1 minutes 15.319 seconds.
Tearing down left over layers:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
```