[fc] Repository: plone.app.openid Branch: refs/heads/master Date: 2016-05-23T09:07:40+02:00 Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org> Commit: https://github.com/plone/plone.app.openid/commit/456b348693287babddbe0f3d767ddad8f6ca7e03
autopep8safe

Files changed:
M plone/app/openid/portlets/login.py
M plone/app/openid/setuphandlers.py
M plone/app/openid/tests/__init__.py
M setup.py
Repository: plone.app.openid
Branch: refs/heads/master
Date: 2016-05-23T09:12:38+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.openid/commit/bc4d83c8103a89b40b8595fbb4fef49dad7e47f3

pep8/pyflakes

Files changed:
M CHANGES.rst
M plone/app/openid/__init__.py
M plone/app/openid/setuphandlers.py
M plone/app/openid/tests/test_view.py
Repository: plone.app.openid
Branch: refs/heads/master
Date: 2016-05-23T12:05:15+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.openid/commit/825cc4542b2f16d32c8f48cdacdc59324453b538

Fixed more code problems from QA testing.

I added a few `noqa` codes:

- Using a print statement to write to a StringIO is fine I think.

- Using the `@public` decorator instead of `declarePublic` is not
  possible with the PloneMessageFactory, which is not a function.
  So you get an AttributeError: 'MessageFactory' object has no attribute '__name__'

Files changed:
M CHANGES.rst
M plone/__init__.py
M plone/app/__init__.py
M plone/app/openid/__init__.py
M plone/app/openid/config.py
M plone/app/openid/portlets/login.py
M plone/app/openid/setuphandlers.py
M plone/app/openid/testing.py
M plone/app/openid/tests/test_view.py
Repository: plone.app.openid
Branch: refs/heads/master
Date: 2016-05-23T13:50:13+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.openid/commit/f9519884e9f5e6f70a57523b05fe41d7efc05c98

Merge pull request #6 from plone/package-cleanup

Package cleanup (pep8/pyflakes)

Files changed:
M CHANGES.rst
M plone/__init__.py
M plone/app/__init__.py
M plone/app/openid/__init__.py
M plone/app/openid/config.py
M plone/app/openid/portlets/login.py
M plone/app/openid/setuphandlers.py
M plone/app/openid/testing.py
M plone/app/openid/tests/__init__.py
M plone/app/openid/tests/test_view.py
M setup.py