Exclude backports.functools-lru-cache from packages to run tests for.
Causes failure, and we are not interested.
See https://github.com/plone/buildout.coredev/pull/673#issuecomment-676088701

```
Traceback (most recent call last):
  File "/home/jenkins/workspace/plone-5.1-python-2.7/bin/test", line 442, in <module>
    '--test-path', '/home/jenkins/.buildout/eggs/cp27m/zope.globalrequest-1.2-py2.7.egg',
  File "/home/jenkins/.buildout/eggs/cp27m/collective.xmltestreport-1.3.4-py2.7.egg/collective/xmltestreport/runner.py", line 60, in run
    failed = run_internal(defaults, args, script_parts=script_parts)
  File "/home/jenkins/.buildout/eggs/cp27m/collective.xmltestreport-1.3.4-py2.7.egg/collective/xmltestreport/runner.py", line 73, in run_internal
    runner.run()
  File "/home/jenkins/.buildout/eggs/cp27m/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 148, in run
    feature.global_setup()
  File "/home/jenkins/.buildout/eggs/cp27m/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/find.py", line 473, in global_setup
    tests = find_tests(self.runner.options, self.runner.found_suites)
  File "/home/jenkins/.buildout/eggs/cp27m/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/find.py", line 164, in find_tests
    for suite in found_suites:
  File "/home/jenkins/.buildout/eggs/cp27m/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/find.py", line 174, in find_suites
    for fpath, package in find_test_files(options):
  File "/home/jenkins/.buildout/eggs/cp27m/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/find.py", line 234, in find_test_files
    for f, package in find_test_files_(options):
  File "/home/jenkins/.buildout/eggs/cp27m/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/find.py", line 262, in find_test_files_
    for (p, package) in test_dirs(options, {}):
  File "/home/jenkins/.buildout/eggs/cp27m/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/find.py", line 317, in test_dirs
    p = import_name(p)
  File "/home/jenkins/.buildout/eggs/cp27m/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/find.py", line 391, in import_name
    __import__(name)
ImportError: No module named functools-lru-cache
```