Capitalised pin for Jinja2
In https://github.com/plone/buildout.coredev/commit/107a9e8de1af16ea947e69795c36479cb9941cba the version was updatet to 2.10 but lower case.   In ztk-versions  Jinja2=2.5.5 is capitalised, buildout was using 2.5.5 again.

Stumbled upon this when using plone.recipe.varnish 2.2.0 (ecosystem) which requires Jinja2 >= 2.7.3 and buildout gave this interesting version conflict:

Version and requirements information containing jinja2:
  [versions] constraint on jinja2: 2.5.5
  Requirement of plone.recipe.varnish==2.2.0: jinja2>=2.7.3
While:
  Installing.
  Getting section varnishd.
  Initializing section varnishd.
  Installing recipe plone.recipe.varnish.
Error: The requirement ('jinja2>=2.7.3') is not allowed by your [versions] constraint (2.5.5)