[fc] Repository: plone.releaser
Branch: refs/heads/master
Date: 2023-09-19T00:12:49+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/99c840723a4104ba4c1880d98b64f64ac336f208

Add manage command 'versions2constraints'.

Files changed:
M plone/releaser/manage.py
M plone/releaser/utils.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-09-19T00:12:50+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/a2d72e2d592b0e8d8dc09abd2d5fe6c0dbfc764e

Support writing to [versions:pythonx]

Files changed:
M plone/releaser/buildout.py
M plone/releaser/manage.py
M plone/releaser/tests/input/versions.cfg
M plone/releaser/tests/test_buildout.py
M plone/releaser/utils.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-09-19T00:12:50+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/fdad9eb0a2f6092bfb62a58aa5771df7fa66de06

Read 'extends' lines from versions.cfg.

Only local for now.

Files changed:
A plone/releaser/tests/input/versions2.cfg
A plone/releaser/tests/input/versions3.cfg
A plone/releaser/tests/input/versions4.cfg
M plone/releaser/buildout.py
M plone/releaser/tests/test_buildout.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-10-07T20:54:02+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/3d800c3caa7129eea4e671f8d05e25a1a77e230d

Support reading extends (-c) in constraints as well.

Files changed:
A plone/releaser/tests/input/constraints2.txt
A plone/releaser/tests/input/constraints3.txt
A plone/releaser/tests/input/constraints4.txt
M plone/releaser/pip.py
M plone/releaser/tests/input/constraints.txt
M plone/releaser/tests/test_buildout.py
M plone/releaser/tests/test_pip.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-10-07T22:15:36+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/990f64eb555805e3c989d932f7f2c1c09e665e24

Add VersionsFile.rewrite.

This takes the parsed 'extends' and 'versions' and writes them back.
This normalizes some stuff, so it will not be exactly the same.

In the end we want to take versions.cfg and translate it to constraints.txt.
But translating versions.cfg to its own should work as well, and is a good first step.

Files changed:
M plone/releaser/buildout.py
M plone/releaser/tests/test_buildout.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-10-09T12:05:44+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/b41ea5ba8ecc9a9ec5feaf1d25159412d176cc2a

constraints: platform_system is darwin, not macosx.

Files changed:
M plone/releaser/tests/input/constraints4.txt
M plone/releaser/tests/test_pip.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-10-12T20:37:44+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/fb2968b4000c7ad45fade472e1a48d8d66186b3d

Add ConstraintsFile.rewrite.

Files changed:
M plone/releaser/pip.py
M plone/releaser/tests/test_pip.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-10-12T22:45:33+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/a034175da9cfec19ea71132733490ed0d68a81fb

Add CheckoutsFile.rewrite.

Files changed:
M plone/releaser/buildout.py
M plone/releaser/tests/test_buildout.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-10-12T23:30:30+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/6b56b8f44abcdeb5c39cef5aea3f4fd04057a5ee

Add Inifile.rewrite.

Files changed:
M plone/releaser/pip.py
M plone/releaser/tests/test_pip.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-10-27T00:10:23+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/667d09c2be62b6e8fd5dbac06c672bd0b4bf0c05

Fix manage.py to work with argh 0.30+.

Full traceback with info:

```
$ bin/manage -h
Traceback (most recent call last):
  File "/Users/maurits/community/plone-coredev/6.0/bin/manage", line 63, in &lt;module&gt;
    sys.exit(plone.releaser.manage.manage())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.releaser/plone/releaser/manage.py", line 277, in __call__
    parser.add_commands(
  File "/Users/maurits/shared-eggs/cp312/argh-0.30.2-py3.12.egg/argh/helpers.py", line 47, in add_commands
    return add_commands(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurits/shared-eggs/cp312/argh-0.30.2-py3.12.egg/argh/assembling.py", line 592, in add_commands
    set_default_command(
  File "/Users/maurits/shared-eggs/cp312/argh-0.30.2-py3.12.egg/argh/assembling.py", line 331, in set_default_command
    inferred_args: List[ParserAddArgumentSpec] = list(
                                                 ^^^^^
  File "/Users/maurits/shared-eggs/cp312/argh-0.30.2-py3.12.egg/argh/assembling.py", line 155, in infer_argspecs_from_function
    raise ArgumentNameMappingError(
argh.assembling.ArgumentNameMappingError: Argument "path" in function "add_checkout"
is not keyword-only but has a default value.

Please note that since Argh v.0.30 the default name mapping
policy has changed.

More information:
https://argh.readthedocs.io/en/latest/changes.html#version-0-30-0-2023-10-21

You need to upgrade your functions so that the arguments
that have default values become keyword-only:

    f(x=1) -&gt; f(*, x=1)

If you actually want an optional positional argument,
please set the name mapping policy explicitly to `BY_NAME_IF_KWONLY`.

If you choose to postpone the migration, you have two options:

a) set the policy explicitly to `BY_NAME_IF_HAS_DEFAULT`;
b) pin Argh version to 0.29 until you are ready to migrate.

Thank you for understanding!
```

Files changed:
M plone/releaser/manage.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-10-30T10:56:01+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/4f5492cc20279e4ed3a6f76ac4a9afd85ee5aaa9

SourcesFile: use config/data and a raw version without interpolation.

Files changed:
M plone/releaser/buildout.py
M plone/releaser/tests/test_buildout.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-11-16T18:50:15+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/d03ac9a24f9e10058d0df5821255d5f3719d386a

SourcesFile.rewrite: take all non-sources sections.

Files changed:
M plone/releaser/buildout.py
M plone/releaser/tests/test_buildout.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-11-16T19:34:08+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/9a2ba07110ed0d35fe9db4a3617c8373101bb009

Get versions2constraints working for simple cases.

Files changed:
A plone/releaser/tests/test_versions2constraints.py
M plone/releaser/manage.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-11-16T19:59:26+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/b718af04079eff3820bfd2cb1c8a2043379d4d2d

Add BaseBuildoutFile and let the others inherit from it.

Then everything has a config, raw_config, and extends.

Files changed:
M plone/releaser/buildout.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-11-16T23:26:00+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/28983c6c5194a6fa258ba0feac1ce87cee356f9c

Get versions2constraints working

Files changed:
M plone/releaser/buildout.py
M plone/releaser/manage.py
M plone/releaser/pip.py
M plone/releaser/tests/test_utils.py
M plone/releaser/tests/test_versions2constraints.py
M plone/releaser/utils.py
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-11-17T00:24:47+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/004aed8ae276f737fb5d14f9999ddc6698775e5e

Add news snippet: Add bin/manage versions2constraints command.

Files changed:
A news/3670.feature
Repository: plone.releaser

Branch: refs/heads/master
Date: 2023-11-30T20:12:59+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/c59ad3f8766a9d9289f142dd48d637cbc824fca1

Merge pull request #62 from plone/maurits-buildout2pip

Add bin/manage versions2constraints command.

Files changed:
A news/3670.feature
A plone/releaser/tests/input/constraints2.txt
A plone/releaser/tests/input/constraints3.txt
A plone/releaser/tests/input/constraints4.txt
A plone/releaser/tests/input/versions2.cfg
A plone/releaser/tests/input/versions3.cfg
A plone/releaser/tests/input/versions4.cfg
A plone/releaser/tests/test_versions2constraints.py
M plone/releaser/buildout.py
M plone/releaser/manage.py
M plone/releaser/pip.py
M plone/releaser/tests/input/constraints.txt
M plone/releaser/tests/input/versions.cfg
M plone/releaser/tests/test_buildout.py
M plone/releaser/tests/test_pip.py
M plone/releaser/tests/test_utils.py
M plone/releaser/utils.py