[fc] Repository: Products.CMFPlone
Branch: refs/heads/6.0.x
Date: 2024-08-12T15:43:03+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/8b1606cd4e4b2a7a2efc2eef2a621c7656163901

Do not use deprecated base_hasattr in utils.py.

This was moved to plone.base.utils, so utils.py should not be using its own deprecated import.

In fact, this gives a strange error when running the `Products.validation` tests in the coredev 6.0 buildout:

```
$ bin/test -s Products.validation
...
Error in test test_isValidId_plone (Products.validation.tests.test_validation.TestValidation.test_isValidId_plone)
Traceback (most recent call last):
  File "/Users/maurits/.pyenv/versions/3.11.9/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Users/maurits/.pyenv/versions/3.11.9/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "/Users/maurits/.pyenv/versions/3.11.9/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
  File "/Users/maurits/community/plone-coredev/6.0/src/Products.validation/Products/validation/tests/test_validation.py", line 154, in test_isValidId_plone
    self.assertEqual(v('good', obj), 1)
  File "/Users/maurits/community/plone-coredev/6.0/src/Products.validation/Products/validation/validators/IdValidator.py", line 69, in __call__
    result = check_id(instance, id, required=kwargs.get('required'))
  File "/Users/maurits/community/plone-coredev/6.0/src/Products.CMFPlone/Products/CMFPlone/utils.py", line 641, in check_id
    result = _check_for_collision(contained_by, id, **kwargs)
  File "/Users/maurits/community/plone-coredev/6.0/src/Products.CMFPlone/Products/CMFPlone/utils.py", line 684, in _check_for_collision
    if base_hasattr(contained_by, "checkIdAvailable"):
NameError: name 'base_hasattr' is not defined
```

One strange thing here is that the error only shows up when you run these packae tests in isolation.  A full `bin/test` in coredev 6.0 works.

Files changed:
M Products/CMFPlone/utils.py
Repository: Products.CMFPlone

Branch: refs/heads/6.0.x
Date: 2024-08-12T15:51:56+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/654c1e05612e154be1d791456bb3bb5703719bc3

Remove line in tests that checked for Zope2 version 4.

With https://github.com/plone/Products.validation/pull/12 the Zope2 distribution will no longer be pulled in.
We could check the version of the Zope package instead.
But this line in the tests is actually not used.

Files changed:
M Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_maintenance.py
Repository: Products.CMFPlone

Branch: refs/heads/6.0.x
Date: 2024-08-12T15:53:46+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/07ca9910708a14bad344fa8707cc17fb1dea1e60

add news snippet

Files changed:
A news/3998.bugfix
Repository: Products.CMFPlone

Branch: refs/heads/6.0.x
Date: 2024-08-12T22:02:43+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@py76.be>
Commit: https://github.com/plone/Products.CMFPlone/commit/f5464df0bacba5597bf729925746e865b5201a9c

Merge pull request #3998 from plone/maurits-do-not-use-deprecated-base-hasattr-in-utils-60

Do not use deprecated base_hasattr in utils.py. [6.0]

Files changed:
A news/3998.bugfix
M Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_maintenance.py
M Products/CMFPlone/utils.py