[fc] Repository: diazo
Branch: refs/heads/master
Date: 2020-03-31T11:10:31+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/diazo/commit/c934e196625e2f079097b7195036a5f04769754d

Travis: test on 3.8, not 3.8-dev.

Files changed:
M .travis.yml
Repository: diazo

Branch: refs/heads/master
Date: 2020-03-31T11:19:06+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/diazo/commit/0e8375f345137df6a1a7c3ddb34efbd6e1b801cd

Drop support for Python 3.4.  No code changes.

Travis said:
ERROR: This lxml version requires Python 2.7, 3.5 or later.

I see no need to spend time supporting 3.4 anymore.

Files changed:
A news/78.feature
M .travis.yml
M setup.py
M tox.ini
Repository: diazo

Branch: refs/heads/master
Date: 2020-03-31T11:34:25+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/diazo/commit/f425aec03fdae7e00f04103309ccbf23946f0321

Upgrade MarkupSafe==1.1.1 to fix tox lint-py3 error.

Note: most tox envs fail for me locally.  We may need to pin setuptools to an older version.
But Travis seems happy enough.

Files changed:
M constraints.txt
Repository: diazo

Branch: refs/heads/master
Date: 2020-04-02T23:45:28+02:00
Author: Maurits van Rees (mauritsvanrees) <m.van.rees@zestsoftware.nl>
Commit: https://github.com/plone/diazo/commit/3737d0cc3ccefb0dcacccb49c7127b04a29c0486

Merge pull request #78 from plone/maurits/travis-38

Travis: test on 3.8, not 3.8-dev. Drop 3.4

Files changed:
A news/78.feature
M .travis.yml
M constraints.txt
M setup.py
M tox.ini