[fc] Repository: plone.memoize
Branch: refs/heads/master
Date: 2025-09-09T12:12:22+02:00
Author: Gil Forcada Codinachs (gforcada) <gil.gnome@gmail.com>
Commit: https://github.com/plone/plone.memoize/commit/760272be95c20c94e3d703b2b87cdd7b419c03bc

Configuring with plone.meta

Files changed:
A .github/dependabot.yml
A .github/workflows/test-matrix.yml
M .github/workflows/meta.yml
M .meta.toml
M pyproject.toml
M tox.ini
D dependabot.yml
Repository: plone.memoize

Branch: refs/heads/master
Date: 2025-09-09T12:12:30+02:00
Author: Gil Forcada Codinachs (gforcada) <gil.gnome@gmail.com>
Commit: https://github.com/plone/plone.memoize/commit/d972c4ff543fb8a388ba547a6d1d75e9e71cd3d9

move code to src

Files changed:
A src/plone/__init__.py
A src/plone/memoize/README.rst
A src/plone/memoize/__init__.py
A src/plone/memoize/compress.py
A src/plone/memoize/compress.rst
A src/plone/memoize/configure.zcml
A src/plone/memoize/forever.py
A src/plone/memoize/forever.rst
A src/plone/memoize/instance.py
A src/plone/memoize/instance.rst
A src/plone/memoize/interfaces.py
A src/plone/memoize/ram.py
A src/plone/memoize/ram.rst
A src/plone/memoize/request.py
A src/plone/memoize/request.rst
A src/plone/memoize/tests.py
A src/plone/memoize/view.py
A src/plone/memoize/view.rst
A src/plone/memoize/volatile.py
A src/plone/memoize/volatile.rst
D plone/__init__.py
D plone/memoize/README.rst
D plone/memoize/__init__.py
D plone/memoize/compress.py
D plone/memoize/compress.rst
D plone/memoize/configure.zcml
D plone/memoize/forever.py
D plone/memoize/forever.rst
D plone/memoize/instance.py
D plone/memoize/instance.rst
D plone/memoize/interfaces.py
D plone/memoize/ram.py
D plone/memoize/ram.rst
D plone/memoize/request.py
D plone/memoize/request.rst
D plone/memoize/tests.py
D plone/memoize/view.py
D plone/memoize/view.rst
D plone/memoize/volatile.py
D plone/memoize/volatile.rst
Repository: plone.memoize

Branch: refs/heads/master
Date: 2025-09-09T12:12:30+02:00
Author: Gil Forcada Codinachs (gforcada) <gil.gnome@gmail.com>
Commit: https://github.com/plone/plone.memoize/commit/5b99e589b1a3c05c844a8e069fa8eee5b5ddd97e

chore: adjust MANIFEST.in

Files changed:
M MANIFEST.in
Repository: plone.memoize

Branch: refs/heads/master
Date: 2025-09-09T12:12:30+02:00
Author: Gil Forcada Codinachs (gforcada) <gil.gnome@gmail.com>
Commit: https://github.com/plone/plone.memoize/commit/c2815f21f3899c43e7454b97df21bd174c8bb1c6

chore: adjust setup.py

Files changed:
M setup.py
Repository: plone.memoize

Branch: refs/heads/master
Date: 2025-09-09T12:12:55+02:00
Author: Gil Forcada Codinachs (gforcada) <gil.gnome@gmail.com>
Commit: https://github.com/plone/plone.memoize/commit/57505171f658d574acd690c5b35699692dc6f4d8

Configuring with plone.meta

Files changed:
M tox.ini
Repository: plone.memoize

Branch: refs/heads/master
Date: 2025-09-09T12:13:04+02:00
Author: Gil Forcada Codinachs (gforcada) <gil.gnome@gmail.com>
Commit: https://github.com/plone/plone.memoize/commit/6eed9219d0cad323ae0fb330636eb938acb97fc9

Add news entry

Files changed:
A news/4217.internal
Repository: plone.memoize

Branch: refs/heads/master
Date: 2025-09-10T11:02:38+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.memoize/commit/950caf6957161664349ef6a2a6064127acf96885

Restore testing with PyPy.

Files changed:
M .github/workflows/test-matrix.yml
M .meta.toml
M tox.ini
Repository: plone.memoize

Branch: refs/heads/master
Date: 2025-09-10T12:04:02+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.memoize/commit/730cf629fbff6f0067b1a589d3ab397ca9f74cac

Fix testing with PyPy.

Files changed:
M .github/workflows/test-matrix.yml
M tox.ini
Repository: plone.memoize

Branch: refs/heads/master
Date: 2025-09-10T12:09:20+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.memoize/commit/fc3f1464ae4282642146330aeb4b2b5b85379139

Need to specify pypy3 explicitly: pypy3.11.

Otherwise `actions/setup-python` says:

```
Error: Invalid format of Python version for PyPy.
Python version should be specified in format 'x.y'.
See README for examples and documentation.
```

Files changed:
M .github/workflows/test-matrix.yml
M .meta.toml
M tox.ini
Repository: plone.memoize

Branch: refs/heads/master
Date: 2025-09-10T12:16:44+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@py76.be>
Commit: https://github.com/plone/plone.memoize/commit/e44b3bd808e375ad21e75f61ad4230cad76a4e8d

Merge pull request #60 from plone/src-layout

Move to src layout

Files changed:
A .github/dependabot.yml
A .github/workflows/test-matrix.yml
A news/4217.internal
A src/plone/__init__.py
A src/plone/memoize/README.rst
A src/plone/memoize/__init__.py
A src/plone/memoize/compress.py
A src/plone/memoize/compress.rst
A src/plone/memoize/configure.zcml
A src/plone/memoize/forever.py
A src/plone/memoize/forever.rst
A src/plone/memoize/instance.py
A src/plone/memoize/instance.rst
A src/plone/memoize/interfaces.py
A src/plone/memoize/ram.py
A src/plone/memoize/ram.rst
A src/plone/memoize/request.py
A src/plone/memoize/request.rst
A src/plone/memoize/tests.py
A src/plone/memoize/view.py
A src/plone/memoize/view.rst
A src/plone/memoize/volatile.py
A src/plone/memoize/volatile.rst
M .github/workflows/meta.yml
M .meta.toml
M MANIFEST.in
M pyproject.toml
M setup.py
M tox.ini
D dependabot.yml
D plone/__init__.py
D plone/memoize/README.rst
D plone/memoize/__init__.py
D plone/memoize/compress.py
D plone/memoize/compress.rst
D plone/memoize/configure.zcml
D plone/memoize/forever.py
D plone/memoize/forever.rst
D plone/memoize/instance.py
D plone/memoize/instance.rst
D plone/memoize/interfaces.py
D plone/memoize/ram.py
D plone/memoize/ram.rst
D plone/memoize/request.py
D plone/memoize/request.rst
D plone/memoize/tests.py
D plone/memoize/view.py
D plone/memoize/view.rst
D plone/memoize/volatile.py
D plone/memoize/volatile.rst