plipbase.cfg: set CHAMELEON_CACHE directory.
Otherwise when running the plone.app.upgrade tests, I get this error:

```
Traceback (most recent call last):
  File "/Users/maurits/shared-eggs/cp37m/zope.configuration-4.3.1-py3.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/Users/maurits/shared-eggs/cp37m/zope.configuration-4.3.1-py3.7.egg/zope/configuration/config.py", line 703, in end
    self.stack.pop().finish()
  File "/Users/maurits/shared-eggs/cp37m/zope.configuration-4.3.1-py3.7.egg/zope/configuration/config.py", line 867, in finish
    args = toargs(context, *self.argdata)
  File "/Users/maurits/shared-eggs/cp37m/zope.configuration-4.3.1-py3.7.egg/zope/configuration/config.py", line 1686, in toargs
    args[str(name)] = field.fromUnicode(s)
  File "/Users/maurits/shared-eggs/cp37m/zope.configuration-4.3.1-py3.7.egg/zope/configuration/fields.py", line 171, in fromUnicode
    value = self.context.resolve(name)
  File "/Users/maurits/shared-eggs/cp37m/zope.configuration-4.3.1-py3.7.egg/zope/configuration/config.py", line 246, in resolve
    __import__(moname)
  File "/Users/maurits/shared-eggs/cp37m/z3c.pt-3.2.0-py3.7.egg/z3c/pt/__init__.py", line 4, in <module>
    import chameleon.i18n  # noqa: E402
  File "/Users/maurits/shared-eggs/cp37m/Chameleon-3.7.0-py3.7.egg/chameleon/__init__.py", line 1, in <module>
    from .zpt.template import PageTemplate
  File "/Users/maurits/shared-eggs/cp37m/Chameleon-3.7.0-py3.7.egg/chameleon/zpt/template.py", line 10, in <module>
    from ..i18n import simple_translate
  File "/Users/maurits/shared-eggs/cp37m/Chameleon-3.7.0-py3.7.egg/chameleon/i18n.py", line 17, in <module>
    from .exc import CompilationError
  File "/Users/maurits/shared-eggs/cp37m/Chameleon-3.7.0-py3.7.egg/chameleon/exc.py", line 9, in <module>
    from .config import SOURCE_EXPRESSION_MARKER_LENGTH as LENGTH
  File "/Users/maurits/shared-eggs/cp37m/Chameleon-3.7.0-py3.7.egg/chameleon/config.py", line 36, in <module>
    "Cache directory does not exist: %s." % CACHE_DIRECTORY
zope.configuration.xmlconfig.ZopeXMLConfigurationError: Cache directory does not exist: /Users/maurits/community/plone-coredev/6.0/plips/var/cache.
```