[fc] Repository: plone.app.lockingbehavior Branch: refs/heads/master Date: 2016-01-30T14:34:40+01:00 Author: Philip Bauer (pbauer) <bauer@starzel.de> Commit: https://github.com/plone/plone.app.lockingbehavior/commit/e45014cae95c9be96fe210d613e8852d8fd95ba0
transform doctest to python-test
skip in Zope4 due to crazy test-isolation-issues with newest zope.testrunner

Running it leads to:
  File "/Users/philip/workspace/coredev/src/plone.supermodel/plone/supermodel/model.py", line 87, in walk
    for child in schema.dependents.keys():
ConfigurationExecutionError: &lt;type 'exceptions.AttributeError'&gt;: 'VerifyingAdapterLookup' object has no attribute 'dependents'
  in:
  File "/Users/philip/workspace/coredev/src/plone.supermodel/plone/supermodel/configure.zcml", line 9.4-12.10
      &lt;zcml:customAction
          handler=".model.finalizeSchemas"
          order="9999999"
          /&gt;

Files changed:
A plone/app/lockingbehavior/tests/test_locking.py
M plone/app/lockingbehavior/testing.py
D plone/app/lockingbehavior/tests/locking.txt
D plone/app/lockingbehavior/tests/test_doctests.py
Repository: plone.app.lockingbehavior
Branch: refs/heads/master
Date: 2016-02-02T10:46:39+01:00
Author: Johannes Raggam (thet) <thetetet@gmail.com>
Commit: https://github.com/plone/plone.app.lockingbehavior/commit/1bc875e7bc8d2719add6faed5b06760b38bc4504

changelog missing

Files changed:
M CHANGES.rst
M plone/app/lockingbehavior/tests/test_locking.py
Repository: plone.app.lockingbehavior
Branch: refs/heads/master
Date: 2016-02-03T09:56:25+01:00
Author: Philip Bauer (pbauer) <bauer@starzel.de>
Commit: https://github.com/plone/plone.app.lockingbehavior/commit/e2a7baafa7c424245600a56695bef1c843aa492c

Merge pull request #5 from plone/thet-zope4

Zope4

Files changed:
A plone/app/lockingbehavior/tests/test_locking.py
M CHANGES.rst
M plone/app/lockingbehavior/testing.py
D plone/app/lockingbehavior/tests/locking.txt
D plone/app/lockingbehavior/tests/test_doctests.py