[fc] Repository: mockup Branch: refs/heads/master Date: 2015-09-19T14:45:37+02:00 Author: JC Brand (jcbrand) <jc@opkode.com> Commit: https://github.com/plone/mockup/commit/2f725065919c4bbda5071026fc23a2d394ff280b
Use pat-base instead of mockup-patterns-base

Files changed:
M mockup/js/bundles/filemanager.js
M mockup/js/bundles/plone.js
M mockup/js/bundles/structure.js
M mockup/js/bundles/widgets.js
M mockup/js/config.js
M mockup/patterns/autotoc/pattern.js
M mockup/patterns/backdrop/pattern.js
M mockup/patterns/contentloader/pattern.js
M mockup/patterns/cookietrigger/pattern.js
M mockup/patterns/eventedit/pattern.js
M mockup/patterns/filemanager/pattern.js
M mockup/patterns/formautofocus/pattern.js
M mockup/patterns/formunloadalert/pattern.js
M mockup/patterns/inlinevalidation/pattern.js
M mockup/patterns/livesearch/pattern.js
M mockup/patterns/markspeciallinks/pattern.js
M mockup/patterns/modal/pattern.js
M mockup/patterns/moment/pattern.js
M mockup/patterns/passwordstrength/pattern.js
M mockup/patterns/pickadate/pattern.js
M mockup/patterns/preventdoublesubmit/pattern.js
M mockup/patterns/querystring/pattern.js
M mockup/patterns/recurrence/pattern.js
M mockup/patterns/relateditems/pattern.js
M mockup/patterns/resourceregistry/pattern.js
M mockup/patterns/select2/pattern.js
M mockup/patterns/sortable/pattern.js
M mockup/patterns/structure/pattern.js
M mockup/patterns/textareamimetypeselector/pattern.js
M mockup/patterns/texteditor/pattern.js
M mockup/patterns/thememapper/pattern.js
M mockup/patterns/tinymce/js/links.js
M mockup/patterns/tinymce/pattern.js
M mockup/patterns/toggle/pattern.js
M mockup/patterns/tooltip/pattern.js
M mockup/patterns/tree/pattern.js
M mockup/patterns/upload/pattern.js
M mockup/tests/fakeserver.js
Repository: mockup
Branch: refs/heads/master
Date: 2015-09-19T14:54:27+02:00
Author: JC Brand (jcbrand) <jc@opkode.com>
Commit: https://github.com/plone/mockup/commit/562a9107a3ed67d68b9936cbb60c49c7df39ad6d

Explicitly declare that the mockup parser should be used.

By default the Patternslib parser will be used, unless overridden.

Files changed:
M mockup/patterns/autotoc/pattern.js
M mockup/patterns/backdrop/pattern.js
M mockup/patterns/contentloader/pattern.js
M mockup/patterns/cookietrigger/pattern.js
M mockup/patterns/eventedit/pattern.js
M mockup/patterns/filemanager/pattern.js
M mockup/patterns/formautofocus/pattern.js
M mockup/patterns/formunloadalert/pattern.js
M mockup/patterns/inlinevalidation/pattern.js
M mockup/patterns/livesearch/pattern.js
M mockup/patterns/markspeciallinks/pattern.js
M mockup/patterns/modal/pattern.js
M mockup/patterns/moment/pattern.js
M mockup/patterns/passwordstrength/pattern.js
M mockup/patterns/pickadate/pattern.js
M mockup/patterns/preventdoublesubmit/pattern.js
M mockup/patterns/querystring/pattern.js
M mockup/patterns/recurrence/pattern.js
M mockup/patterns/relateditems/pattern.js
M mockup/patterns/resourceregistry/pattern.js
M mockup/patterns/select2/pattern.js
M mockup/patterns/sortable/pattern.js
M mockup/patterns/structure/pattern.js
M mockup/patterns/textareamimetypeselector/pattern.js
M mockup/patterns/texteditor/pattern.js
M mockup/patterns/thememapper/pattern.js
M mockup/patterns/tinymce/pattern.js
M mockup/patterns/toggle/pattern.js
M mockup/patterns/tooltip/pattern.js
M mockup/patterns/tree/pattern.js
M mockup/patterns/upload/pattern.js
Repository: mockup
Branch: refs/heads/master
Date: 2015-09-19T17:12:48+02:00
Author: JC Brand (jcbrand) <jc@opkode.com>
Commit: https://github.com/plone/mockup/commit/105199103ea243d6d7c755fbc22256f48b47284f

Bump to latest Patternslib

which contains the mockup parser and an updated Base pattern.

Files changed:
M bower.json
Repository: mockup
Branch: refs/heads/master
Date: 2015-09-19T17:15:38+02:00
Author: JC Brand (jcbrand) <jc@opkode.com>
Commit: https://github.com/plone/mockup/commit/8503f222c4c2fd266f9bb8c3184b47cbcd3e4e3f

Updated JS config

- Remove mockup-parser and add pat-mockup-parser (from Patternslib)
- Add lodash and let underscore point to underscore pulled in from Patternslib.
    Looks like the lodash version from mockup is quite old and incompatible
    with the underscore version from Patternslib, so we need both for now :(

Files changed:
M mockup/js/config.js
Repository: mockup
Branch: refs/heads/master
Date: 2015-09-19T17:18:08+02:00
Author: JC Brand (jcbrand) <jc@opkode.com>
Commit: https://github.com/plone/mockup/commit/55f0526c48081f621bdd1488f1924f1e0782d296

Fix test for toggle, now that we use Patternslib Base obj

Files changed:
M mockup/tests/pattern-toggle-test.js
Repository: mockup
Branch: refs/heads/master
Date: 2015-09-19T17:18:51+02:00
Author: JC Brand (jcbrand) <jc@opkode.com>
Commit: https://github.com/plone/mockup/commit/90d28eab975178b3664be0eeb10b764de1fc1f2a

Explicitly use lodash instead of underscore.

This fixed a lot of broken tests because the version of lodash used by Mockup
is older and not compatible with the version of underscore required by
Patternslib.

Files changed:
M mockup/patterns/contentloader/pattern.js
M mockup/patterns/filemanager/js/addnew.js
M mockup/patterns/filemanager/js/basepopover.js
M mockup/patterns/filemanager/js/customize.js
M mockup/patterns/filemanager/js/delete.js
M mockup/patterns/filemanager/js/newfolder.js
M mockup/patterns/filemanager/js/rename.js
M mockup/patterns/filemanager/js/upload.js
M mockup/patterns/filemanager/pattern.js
M mockup/patterns/livesearch/pattern.js
M mockup/patterns/modal/pattern.js
M mockup/patterns/querystring/pattern.js
M mockup/patterns/relateditems/pattern.js
M mockup/patterns/resourceregistry/js/builder.js
M mockup/patterns/resourceregistry/js/fields.js
M mockup/patterns/resourceregistry/js/less.js
M mockup/patterns/resourceregistry/js/overrides.js
M mockup/patterns/resourceregistry/js/patternoptions.js
M mockup/patterns/resourceregistry/js/registry.js
M mockup/patterns/resourceregistry/pattern.js
M mockup/patterns/structure/js/collections/result.js
M mockup/patterns/structure/js/views/actionmenu.js
M mockup/patterns/structure/js/views/addmenu.js
M mockup/patterns/structure/js/views/app.js
M mockup/patterns/structure/js/views/columns.js
M mockup/patterns/structure/js/views/generic-popover.js
M mockup/patterns/structure/js/views/paging.js
M mockup/patterns/structure/js/views/rearrange.js
M mockup/patterns/structure/js/views/selectionbutton.js
M mockup/patterns/structure/js/views/selectionwell.js
M mockup/patterns/structure/js/views/table.js
M mockup/patterns/structure/js/views/tablerow.js
M mockup/patterns/structure/js/views/textfilter.js
M mockup/patterns/structure/js/views/upload.js
M mockup/patterns/thememapper/js/cacheview.js
M mockup/patterns/thememapper/js/lessbuilderview.js
M mockup/patterns/thememapper/js/rulebuilder.js
M mockup/patterns/thememapper/js/rulebuilderview.js
M mockup/patterns/thememapper/pattern.js
M mockup/patterns/tinymce/js/links.js
M mockup/patterns/tinymce/pattern.js
M mockup/patterns/tree/pattern.js
M mockup/patterns/upload/pattern.js
Repository: mockup
Branch: refs/heads/master
Date: 2015-09-19T18:23:42+02:00
Author: JC Brand (jcbrand) <jc@opkode.com>
Commit: https://github.com/plone/mockup/commit/0b4fd8fe3263a504ad7c6cdaa26fb7ba1c6efaa6

Pin parsley.js version.

Files changed:
M bower.json
M mockup/patterns/pickadate/pattern.js
Repository: mockup
Branch: refs/heads/master
Date: 2015-09-19T18:49:51+02:00
Author: JC Brand (jcbrand) <jc@opkode.com>
Commit: https://github.com/plone/mockup/commit/262de2459a8581116b706ac6488269d278a10b60

Move last files from mockup-core so that we can finally remove it.

Files changed:
A mockup/js/grunt.js
M mockup/Gruntfile.js
M mockup/js/config.js
M mockup/less/docs.less
Repository: mockup
Branch: refs/heads/master
Date: 2015-09-19T19:07:53+02:00
Author: JC Brand (jcbrand) <jc@opkode.com>
Commit: https://github.com/plone/mockup/commit/9b96758f5014b8df63793379acb38d51d8a254d4

Update changelog. Remove mockup-core from bower.json

Files changed:
M CHANGES.rst
M bower.json
Repository: mockup
Branch: refs/heads/master
Date: 2015-09-19T19:10:01+02:00
Author: JC Brand (jcbrand) <jc@opkode.com>
Commit: https://github.com/plone/mockup/commit/018f5abff4d8bcfb22c68d95d8f803381416d1ba

Remove reference to mockup-core in getting started docs.

Files changed:
M mockup/GETTING_STARTED.md
Repository: mockup
Branch: refs/heads/master
Date: 2015-09-20T00:38:03+02:00
Author: JC Brand (jcbrand) <jc@opkode.com>
Commit: https://github.com/plone/mockup/commit/c1eab5b1116448de012c54a6bb2aa7d8a6f1782b

Figured out how to use only one version of underscore.

Same version used by Patternslib and means we don't need to load both lodash
and underscore.

Files changed:
M bower.json
M mockup/LEARN.md
M mockup/js/config.js
M mockup/patterns/contentloader/pattern.js
M mockup/patterns/filemanager/js/addnew.js
M mockup/patterns/filemanager/js/basepopover.js
M mockup/patterns/filemanager/js/customize.js
M mockup/patterns/filemanager/js/delete.js
M mockup/patterns/filemanager/js/newfolder.js
M mockup/patterns/filemanager/js/rename.js
M mockup/patterns/filemanager/js/upload.js
M mockup/patterns/filemanager/pattern.js
M mockup/patterns/livesearch/pattern.js
M mockup/patterns/modal/pattern.js
M mockup/patterns/querystring/pattern.js
M mockup/patterns/relateditems/pattern.js
M mockup/patterns/resourceregistry/js/builder.js
M mockup/patterns/resourceregistry/js/fields.js
M mockup/patterns/resourceregistry/js/less.js
M mockup/patterns/resourceregistry/js/overrides.js
M mockup/patterns/resourceregistry/js/patternoptions.js
M mockup/patterns/resourceregistry/js/registry.js
M mockup/patterns/resourceregistry/pattern.js
M mockup/patterns/structure/js/collections/result.js
M mockup/patterns/structure/js/views/actionmenu.js
M mockup/patterns/structure/js/views/addmenu.js
M mockup/patterns/structure/js/views/app.js
M mockup/patterns/structure/js/views/columns.js
M mockup/patterns/structure/js/views/generic-popover.js
M mockup/patterns/structure/js/views/paging.js
M mockup/patterns/structure/js/views/rearrange.js
M mockup/patterns/structure/js/views/selectionbutton.js
M mockup/patterns/structure/js/views/selectionwell.js
M mockup/patterns/structure/js/views/table.js
M mockup/patterns/structure/js/views/tablerow.js
M mockup/patterns/structure/js/views/textfilter.js
M mockup/patterns/structure/js/views/upload.js
M mockup/patterns/thememapper/js/cacheview.js
M mockup/patterns/thememapper/js/lessbuilderview.js
M mockup/patterns/thememapper/js/rulebuilder.js
M mockup/patterns/thememapper/js/rulebuilderview.js
M mockup/patterns/thememapper/pattern.js
M mockup/patterns/tinymce/js/links.js
M mockup/patterns/tinymce/pattern.js
M mockup/patterns/tree/pattern.js
M mockup/patterns/upload/pattern.js
Repository: mockup
Branch: refs/heads/master
Date: 2015-09-20T00:43:40+02:00
Author: JC Brand (jcbrand) <jc@opkode.com>
Commit: https://github.com/plone/mockup/commit/c8bceda978053fb0a0f72da9ef79169e2bb97ff6

Use pat-base in the docs.

Files changed:
M mockup/GETTING_STARTED.md
M mockup/LEARN.md
Repository: mockup
Branch: refs/heads/master
Date: 2015-09-20T00:58:55+02:00
Author: JC Brand (jcbrand) <jc@opkode.com>
Commit: https://github.com/plone/mockup/commit/b9405c97202552956d02981419db623fdf979f41

Pin the Patternslib version to the current latest commit.

Files changed:
M bower.json
Repository: mockup
Branch: refs/heads/master
Date: 2015-09-20T01:45:40+02:00
Author: JC Brand (jcbrand) <jc@opkode.com>
Commit: https://github.com/plone/mockup/commit/3dba9535b15ab30b8ac34763b19bf6844cabc477

Try to fix the TinyMCE heisenbug.

It happens in the afterEach method when $('body').empty() is called and
apparently has to do with TinyMCE itself not being properly cleared.

TypeError: 'undefined' is not an object (evaluating 'doc.createRange')
(/home/jc/buildout.coredev/src/mockup/mockup/bower_components/tinymce-builded/js/tinymce/tinymce.js

Files changed:
M mockup/tests/pattern-tinymce-test.js
Repository: mockup
Branch: refs/heads/master
Date: 2015-09-21T22:23:04+02:00
Author: JC Brand (jcbrand) <jc@opkode.com>
Commit: https://github.com/plone/mockup/commit/8d616f966c016c7d26223d6c8d3d3aa70e8aaa56

Add a shim for the Patterns Base pattern.

This shim automatically sets the 'parser' attribute to 'mockup' and it is
configured to have the name of the old mockup-core base pattern
"mockup-patterns-base".

Added a deprecation warning to inform users to change to pat-base.

Files changed:
A mockup/patterns/base/pattern.js
M mockup/js/config.js
Repository: mockup
Branch: refs/heads/master
Date: 2015-09-21T23:12:25+02:00
Author: JC Brand (jcbrand) <jc@opkode.com>
Commit: https://github.com/plone/mockup/commit/76cff4318c3647902f09f019055256942f6530f8

Bump the version number and note changes required.

Files changed:
M CHANGES.rst
Repository: mockup
Branch: refs/heads/master
Date: 2015-09-21T23:15:48+02:00
Author: JC Brand (jcbrand) <jc@opkode.com>
Commit: https://github.com/plone/mockup/commit/f24f8ee573b2a79a59628db810395efd8966bdd2

Merge branch 'master' into remove-mockup-core

Conflicts:
	CHANGES.rst

Files changed:
M CHANGES.rst
M MANIFEST.in
M mockup/patterns/moment/pattern.js
M mockup/patterns/recurrence/pattern.recurrence.less
M mockup/patterns/relateditems/pattern.relateditems.less
M package.json
Repository: mockup
Branch: refs/heads/master
Date: 2015-09-21T21:04:48-05:00
Author: Nathan Van Gheem (vangheem) <vangheem@gmail.com>
Commit: https://github.com/plone/mockup/commit/f7687d5d6fa5bfd91f981e08b1ca2a60ea8a6482

Merge pull request #585 from plone/remove-mockup-core

Remove mockup-core

Files changed:
A mockup/js/grunt.js
A mockup/patterns/base/pattern.js
M CHANGES.rst
M bower.json
M mockup/GETTING_STARTED.md
M mockup/Gruntfile.js
M mockup/LEARN.md
M mockup/js/bundles/filemanager.js
M mockup/js/bundles/plone.js
M mockup/js/bundles/structure.js
M mockup/js/bundles/widgets.js
M mockup/js/config.js
M mockup/less/docs.less
M mockup/patterns/autotoc/pattern.js
M mockup/patterns/backdrop/pattern.js
M mockup/patterns/contentloader/pattern.js
M mockup/patterns/cookietrigger/pattern.js
M mockup/patterns/eventedit/pattern.js
M mockup/patterns/filemanager/pattern.js
M mockup/patterns/formautofocus/pattern.js
M mockup/patterns/formunloadalert/pattern.js
M mockup/patterns/inlinevalidation/pattern.js
M mockup/patterns/livesearch/pattern.js
M mockup/patterns/markspeciallinks/pattern.js
M mockup/patterns/modal/pattern.js
M mockup/patterns/moment/pattern.js
M mockup/patterns/passwordstrength/pattern.js
M mockup/patterns/pickadate/pattern.js
M mockup/patterns/preventdoublesubmit/pattern.js
M mockup/patterns/querystring/pattern.js
M mockup/patterns/recurrence/pattern.js
M mockup/patterns/relateditems/pattern.js
M mockup/patterns/resourceregistry/js/builder.js
M mockup/patterns/resourceregistry/pattern.js
M mockup/patterns/select2/pattern.js
M mockup/patterns/sortable/pattern.js
M mockup/patterns/structure/js/views/generic-popover.js
M mockup/patterns/structure/pattern.js
M mockup/patterns/textareamimetypeselector/pattern.js
M mockup/patterns/texteditor/pattern.js
M mockup/patterns/thememapper/pattern.js
M mockup/patterns/tinymce/js/links.js
M mockup/patterns/tinymce/pattern.js
M mockup/patterns/toggle/pattern.js
M mockup/patterns/tooltip/pattern.js
M mockup/patterns/tree/pattern.js
M mockup/patterns/upload/pattern.js
M mockup/tests/fakeserver.js
M mockup/tests/pattern-tinymce-test.js
M mockup/tests/pattern-toggle-test.js