Don't run tests parallel in multiple threads.
This can work, and is a bit faster (though not much), but it can lead to a strange error:

```
  Set up .EmptyLayer Running Products.CMFPlone.tests.testSearch.Search:Integration tests:
  Running in a subprocess.
  Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
  Set up plone.testing.zope.Startup in 0.238 seconds.
  Set up plone.app.testing.layers.PloneFixture Traceback (most recent call last):
  File "/home/runner/work/buildout.coredev/buildout.coredev/.venv/lib/python3.14/site-packages/zope/configuration/xmlconfig.py", line 448, in endElementNS
    self.context.end()
  File "/home/runner/work/buildout.coredev/buildout.coredev/.venv/lib/python3.14/site-packages/zope/configuration/config.py", line 748, in end
    self.stack.pop().finish()
  File "/home/runner/work/buildout.coredev/buildout.coredev/.venv/lib/python3.14/site-packages/zope/configuration/config.py", line 918, in finish
    actions = self.handler(context, **args)
  File "/home/runner/work/buildout.coredev/buildout.coredev/.venv/lib/python3.14/site-packages/zope/i18n/zcml.py", line 119, in registerTranslations
    catalogs.append(GettextMessageCatalog(lang, name, file))
  File "/home/runner/work/buildout.coredev/buildout.coredev/.venv/lib/python3.14/site-packages/zope/i18n/gettextmessagecatalog.py", line 70, in __init__
    self.reload()
  File "/home/runner/work/buildout.coredev/buildout.coredev/.venv/lib/python3.14/site-packages/zope/i18n/gettextmessagecatalog.py", line 81, in reload
    self._catalog = GNUTranslations(fp)
  File "/opt/hostedtoolcache/Python/3.14.2/x64/lib/python3.14/gettext.py", line 279, in __init__
    self._parse(fp)
  File "/opt/hostedtoolcache/Python/3.14.2/x64/lib/python3.14/gettext.py", line 362, in _parse
    magic = unpack('<I', buf[:4])[0]
struct.error: unpack requires a buffer of 4 bytes
```

See [this failed test run](https://github.com/plone/buildout.coredev/actions/runs/22403246578/job/64855625539#step:9:42).
I suppose this is because two threads are reading from the same `.po` file, or writing to the same `.mo` file.