Pin wheel to 0.36.2 in requirements.txt, instead of leaving the version open.
This version is in the Zope versions.
Version 0.37.0 was released yesterday (2021-08-09).
So when you pip install the requirements, you would get the new version.
And then on Python2.7, bin/buildout would try to get the previous version, which fails for me:

```
Installing releaser.
Getting distribution for 'wheel==0.36.2'.
WARNING: The easy_install command is deprecated and will be removed in a future version.
warning: no files found matching '*.dynlib' under directory 'tests'
no previously-included directories found matching 'tests/testdata/*/build'
no previously-included directories found matching 'tests/testdata/*/dist'
no previously-included directories found matching 'tests/testdata/*/*.egg-info'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/maurits/community/plone-coredev/5.2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 2321, in main
...
  File "/Users/maurits/community/plone-coredev/5.2/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 321, in copy_metadata_to
    if path.startswith(prefix):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 40: ordinal not in range(128)
An error occurred when trying to install /Users/maurits/cached-downloads/dist/wheel-0.36.2.tar.gz. Look above this message for any errors that were output by easy_install.
While:
  Installing releaser.
  Getting distribution for 'wheel==0.36.2'.
```

With the same version installed by pip, buildout should not complain anymore.