[fc] Repository: plone.batching Branch: refs/heads/master Date: 2015-07-09T15:35:45+02:00 Author: Gauthier Bastien (gbastien) <g.bastien@imio.be> Commit: https://github.com/plone/plone.batching/commit/62737b7c917226e99627458f6c52b34401ce9b9f
PEP8

Files changed:
M plone/batching/tests.py
Repository: plone.batching
Branch: refs/heads/master
Date: 2015-07-09T15:37:27+02:00
Author: Gauthier Bastien (gbastien) <g.bastien@imio.be>
Commit: https://github.com/plone/plone.batching/commit/fd08400d954fb25b45a501fbe8c14530ec68b6c7

PEP8

Files changed:
M plone/batching/tests.py
Repository: plone.batching
Branch: refs/heads/master
Date: 2015-07-09T16:59:39+02:00
Author: Gauthier Bastien (gbastien) <g.bastien@imio.be>
Commit: https://github.com/plone/plone.batching/commit/760cf783456e4d1985b238f16379932fce06ef63

Avoid
Module plone.batching.batch, line 232, in previous_pages
ValueError: XXX is not in list
that can happen if b_start is too high and using orphan
See https://github.com/plone/Products.CMFPlone/issues/639

Files changed:
M CHANGES.rst
M plone/batching/batch.py
M plone/batching/tests.py
Repository: plone.batching
Branch: refs/heads/master
Date: 2015-07-09T17:07:55+02:00
Author: Gauthier Bastien (gbastien) <g.bastien@imio.be>
Commit: https://github.com/plone/plone.batching/commit/18cc2b779b4885f59019a11633544b0d10baa8e7

Really need to compute _pagenumber when using orphan

Files changed:
M plone/batching/batch.py
M plone/batching/tests.py
Repository: plone.batching
Branch: refs/heads/master
Date: 2015-07-15T13:10:07+02:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/plone.batching/commit/46590330f90f1439bcca2948bb672fd12e5a97bd

Merge pull request #8 from gbastien/master

fix for "plone.batching fails if b_start is too high" see plone/Products.CMFPlone#639

Files changed:
M CHANGES.rst
M plone/batching/batch.py
M plone/batching/tests.py