[fc] Repository: Products.CMFPlone
Branch: refs/heads/master
Date: 2019-03-19T09:47:51+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/f62aab2d0ff9e7917e25b41e211ab67f1b7a83f5

Add alternative urls with manual=True.

Files changed:
M Products/CMFPlone/controlpanel/browser/redirects.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:55+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/22a944683c21933218a434aa7432a4cbdcae93c2

Redirects control panel: added Download button.

Files changed:
M Products/CMFPlone/controlpanel/browser/redirects-controlpanel.pt
M Products/CMFPlone/controlpanel/browser/redirects.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:55+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/cffc600c05c668e548dcc4fe9f2c83e7bc933bf4

Redirects control panel: download as a stream.

Files changed:
M Products/CMFPlone/controlpanel/browser/redirects.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:55+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/229a28153432efb1bca6676cf084c48b8037f9d6

Redirects control panel: test the download.

Files changed:
M Products/CMFPlone/controlpanel/browser/redirects.py
M Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_redirection.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:55+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/d24ee6f0ad95d3b3fdb7c18a5c1536b5284aeeff

Redirects control panel: test the upload.

Files changed:
M Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_redirection.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:55+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/c2a519e83572247d8030cdd3fcf61acdf7c4075c

Redirects control panel: test uploading with various columns.

And in case of errors, always report the detected delimiter.
I was getting delimiter 'w' in tests...

Files changed:
M Products/CMFPlone/controlpanel/browser/redirects.py
M Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_redirection.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:55+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/8631e15d419916a023ba598bd53a3c0d407277b8

Redirects: test uploading a download and downloading an upload.

This actually fails, because the download contains /plone/bar/0 and the upload should contain only /bar/0.

Files changed:
M Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_redirection.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:55+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/4848615d0079bf62340c39c90dd8d44930fc1387

Redirects: let the download strip the portal path.

Then you can use the download as upload.

Files changed:
M Products/CMFPlone/controlpanel/browser/redirects.py
M Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_redirection.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:55+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/c23700dd571cb2b1c686458a44553c7f35302687

Redirects: update the example bulk upload to contain datetime and manual boolean.

Files changed:
M Products/CMFPlone/controlpanel/browser/redirects-controlpanel.pt
M Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_redirection.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:55+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/45ad431cda0b79f907fad068b7fe39c57a7d21f8

Redirects: explain more on redirects control panel and view.

Text taken from comment by @djay:
https://github.com/plone/Products.CMFPlone/issues/1486#issuecomment-463072762

Files changed:
M Products/CMFPlone/controlpanel/browser/redirects-controlpanel.pt
M Products/CMFPlone/controlpanel/browser/redirects-manage.pt
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:55+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/5f21e71911a44904c89ba4dfa6005c8e909209de

Test removing aliases from context and from control panel.

Files changed:
M Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_redirection.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:55+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/1bf80b69900d40f1e4334cdb8d98987383e6685c

Redirects: button for removing all that match the filter.

Files changed:
M Products/CMFPlone/controlpanel/browser/redirects-controlpanel.pt
M Products/CMFPlone/controlpanel/browser/redirects.py
M Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_redirection.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:55+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/53edd8c96b0b5f7ed31180b3d2ab364a39c80793

Redirects: show datetime and manual in control panel.

Files changed:
M Products/CMFPlone/controlpanel/browser/redirects-controlpanel.pt
M Products/CMFPlone/controlpanel/browser/redirects.py
M Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_redirection.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:55+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/ae00d6cbc71e10d505a23d635eaa7e88a10cb23d

Redirects: allow filtering on manual or automatic.

Files changed:
M Products/CMFPlone/controlpanel/browser/redirects-controlpanel.pt
M Products/CMFPlone/controlpanel/browser/redirects.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:55+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/fa1f70d0cb6ba8835cb807db350d83303503bfbd

Redirects: allow filtering on created date.

Files changed:
M Products/CMFPlone/controlpanel/browser/redirects-controlpanel.pt
M Products/CMFPlone/controlpanel/browser/redirects.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:55+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/0df1da88ba3f3efab8501ba652a1ee8f7eb8c98d

Redirects: test filtering on manual yes/no.

Files changed:
M Products/CMFPlone/controlpanel/browser/redirects.py
M Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_redirection.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:55+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/db7a431ebda1a579179fc1a7297e9c36195a04b6

Redirects: test filtering on date.

Files changed:
M Products/CMFPlone/controlpanel/browser/redirects.py
M Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_redirection.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:56+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/90aac13d52918a0efbee7a411eec2640890a603a

Redirects: added test_controlpanel_redirection.robot.

Basic test for adding a redirect and checking that you end up at the new location.

Files changed:
A Products/CMFPlone/tests/robot/test_controlpanel_redirection.robot
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:56+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/316966a805be48c5913b96d0848cbbf29036cd0a

test_controlpanel_redirection.robot: figure out how to accept arguments in keywords.

I was looking at the wrong examples.

Files changed:
M Products/CMFPlone/tests/robot/test_controlpanel_redirection.robot
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:56+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/3b994e067dc9b03b39e2953331bab32ced9a343e

Redirects: added robot test for removing a redirect.

Files changed:
M Products/CMFPlone/tests/robot/test_controlpanel_redirection.robot
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:56+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/0bbd76cdaeed43d8259ae364f4c95bc09d9b89f2

Redirects: added robot test for removing matching redirects.

Files changed:
M Products/CMFPlone/tests/robot/test_controlpanel_redirection.robot
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:56+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/87f0ae9b36133e84c0dfdb3135f9af047d04deee

test_controlpanel_redirection.robot: Less Capital Letters.

Files changed:
M Products/CMFPlone/tests/robot/test_controlpanel_redirection.robot
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:56+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/8f23ddf38c5785c0273f1082b2c725fc48bd5412

test_controlpanel_redirection.robot: basic download csv test.

I don't know how to get the contents of the downloaded file,
so this only tests that there is no error.

Files changed:
M Products/CMFPlone/tests/robot/test_controlpanel_redirection.robot
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:56+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/c191669c33a26988dba56c62f7fe18b8af22e465

Redirects: fixed uploading a file in the test browser in Python 2.

Sample traceback:

Traceback (most recent call last):
  File "/usr/local/py27/parts/opt/lib/python2.7/unittest/case.py", line 398, in debug
    getattr(self, self._testMethodName)()
  File "/Users/maurits/community/plone-coredev/5.2/src/Products.CMFPlone/Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_redirection.py", line 653, in test_upload_two_columns
    self.browser.getControl(name='file').value.filename = 'redirects.csv'
  File "/Users/maurits/shared-eggs/cp27m/zope.testbrowser-5.3.2-py2.7.egg/zope/testbrowser/browser.py", line 698, in value
    return self.browser.toStr(val)
  File "/Users/maurits/shared-eggs/cp27m/zope.testbrowser-5.3.2-py2.7.egg/zope/testbrowser/browser.py", line 541, in toStr
    return s.encode(self._response.charset)
AttributeError: 'Upload' object has no attribute 'encode'

Solution: get the file control and call the add_file method on it.
Found in the documentation:
https://zopetestbrowser.readthedocs.io/en/latest/narrative.html#file-control

Files changed:
M Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_redirection.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:56+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/d84fc67720de0a7c02ef0af2557dfc8e797ee547

Added news snippets for feature 2799.

Files changed:
A news/2799.feature.1
A news/2799.feature.2
A news/2799.feature.3
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:56+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/044bad53ef8788e7dd4477bb52e949067241e7b4

Redirects: edit so these asserts are on one line.

Makes it easier to spot which one goes wrong.

Files changed:
M Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_redirection.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:56+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/71ae51fa6d9f632e61f14a30775ac35a03999eba

Redirects: be lenient in tests where non-naive timezones are used.

Files changed:
M Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_redirection.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-03-19T09:47:56+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/bc96b0d899812588d8193b39f152e4364c6cf090

Redirects: removed writing of html file to /tmp in tests.

This was an accidental left-over from local debugging.
It actually failed on Jenkins.

Files changed:
M Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_redirection.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-04-11T11:03:46+02:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/Products.CMFPlone/commit/92e0fd282bfb1748f23f06a9d5b127aa82cf20f2

Merge branch 'master' into maurits-extend-paths

Files changed:
A news/2809.bugfix
A news/2821.bugfix
A news/2828.bugfix
M CHANGES.rst
M Products/CMFPlone/browser/navigation.py
M Products/CMFPlone/controlpanel/browser/redirects.py
M Products/CMFPlone/interfaces/resources.py
M Products/CMFPlone/tests/robot/test_actionmenu.robot
M Products/CMFPlone/tests/robot/test_controlpanel_actions.robot
M Products/CMFPlone/tests/robot/test_controlpanel_editing.robot
M Products/CMFPlone/tests/robot/test_controlpanel_filter.robot
M Products/CMFPlone/tests/robot/test_controlpanel_language.robot
M Products/CMFPlone/tests/robot/test_controlpanel_markup.robot
M Products/CMFPlone/tests/robot/test_controlpanel_navigation.robot
M Products/CMFPlone/tests/robot/test_controlpanel_search.robot
M Products/CMFPlone/tests/robot/test_controlpanel_security.robot
M Products/CMFPlone/tests/robot/test_controlpanel_site.robot
M Products/CMFPlone/tests/robot/test_controlpanel_social.robot
M Products/CMFPlone/tests/robot/test_controlpanel_types.robot
M Products/CMFPlone/tests/robot/test_controlpanel_usergroups.robot
M Products/CMFPlone/tests/robot/test_edit.robot
M Products/CMFPlone/tests/robot/test_edit_user_schema.robot
M Products/CMFPlone/tests/robot/test_linkintegrity.robot
M Products/CMFPlone/tests/robot/test_overlays.robot
M Products/CMFPlone/tests/robot/test_portlets.robot
M Products/CMFPlone/tests/robot/test_querystring.robot
M Products/CMFPlone/tests/robot/test_thememapper.robot
M Products/CMFPlone/tests/robot/test_tinymce.robot
M Products/CMFPlone/tests/testNavigationView.py
M setup.py
D news/2516.bugfix
D news/2689.bugfix
D news/2788.bugfix
D news/2792.bugfix
D news/2798.bugfix
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2019-04-11T11:04:55+02:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/Products.CMFPlone/commit/705d0eaf0cb6d1ffaff73e1d35968c82000b00b8

Merge pull request #2801 from plone/maurits-extend-paths

Implement redirections features: store date and manual, export, bulk remove

Files changed:
A Products/CMFPlone/tests/robot/test_controlpanel_redirection.robot
A news/2799.feature.1
A news/2799.feature.2
A news/2799.feature.3
M Products/CMFPlone/controlpanel/browser/redirects-controlpanel.pt
M Products/CMFPlone/controlpanel/browser/redirects-manage.pt
M Products/CMFPlone/controlpanel/browser/redirects.py
M Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_redirection.py