Do not run the tests on Windows.
Too many failures for too many reasons.
See https://github.com/plone/buildout.coredev/runs/6234408039?check_suite_focus=true

Just the first one:

```
Error in test test_transform_filename (diazo.tests.test_wsgi.TestXSLTMiddleware)
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "d:\a\buildout.coredev\buildout.coredev\eggs\diazo-1.4.2-py3.8.egg\diazo\tests\test_wsgi.py", line 178, in test_transform_filename
    os.unlink(filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmpi5sjiamu'
```

Also, I should not be trying this out on a release branch. :-)