Python 2.7: pin twine back to 1.15.0.
2.0.0 is incompatible because it uses f-strings, which means at least Python 3.6.
Traceback:

```
Upload to pypi (Y/n)?
Traceback (most recent call last):
  File "/Users/maurits/bin/plonefullrelease", line 61, in <module>
    sys.exit(zest.releaser.fullrelease.main())
  File "/Users/maurits/shared-eggs/cp27m/zest.releaser-6.19.1-py2.7.egg/zest/releaser/fullrelease.py", line 27, in main
    releaser.run()
  File "/Users/maurits/shared-eggs/cp27m/zest.releaser-6.19.1-py2.7.egg/zest/releaser/baserelease.py", line 419, in run
    self.execute()
  File "/Users/maurits/shared-eggs/cp27m/zest.releaser-6.19.1-py2.7.egg/zest/releaser/release.py", line 83, in execute
    self._release()
  File "/Users/maurits/shared-eggs/cp27m/zest.releaser-6.19.1-py2.7.egg/zest/releaser/release.py", line 292, in _release
    self._upload_distributions(package)
  File "/Users/maurits/shared-eggs/cp27m/zest.releaser-6.19.1-py2.7.egg/zest/releaser/release.py", line 177, in _upload_distributions
    self._retry_twine('upload', server, files_in_dist)
  File "/Users/maurits/shared-eggs/cp27m/zest.releaser-6.19.1-py2.7.egg/zest/releaser/release.py", line 190, in _retry_twine
    twine_dispatch(twine_args)
  File "/Users/maurits/shared-eggs/cp27m/twine-2.0.0-py2.7.egg/twine/cli.py", line 72, in dispatch
    main = registered_commands[args.command].load()
  File "/Users/maurits/community/plone-coredev/5.2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Users/maurits/community/plone-coredev/5.2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/maurits/shared-eggs/cp27m/twine-2.0.0-py2.7.egg/twine/commands/upload.py", line 28
    f'A file named "{filename}" already exists for',
                                                  ^
SyntaxError: invalid syntax
```