[fc] Repository: plone.rest
Branch: refs/heads/main
Date: 2025-09-08T16:37:55+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.rest/commit/e015c959d589a2d5108a1b5d9530209ccfbe1129

Configuring with plone.meta

Files changed:
A .github/dependabot.yml
A .github/workflows/test-matrix.yml
A news/+meta.internal
M .editorconfig
M .flake8
M .github/workflows/meta.yml
M .gitignore
M .meta.toml
M .pre-commit-config.yaml
M pyproject.toml
M tox.ini
Repository: plone.rest

Branch: refs/heads/main
Date: 2025-09-08T16:41:57+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.rest/commit/30ba7a9c9d8d804b46fb58633559618b6adcd990

Fix codespell error: re-used -&gt; reused

Files changed:
M CHANGES.rst
Repository: plone.rest

Branch: refs/heads/main
Date: 2025-09-08T16:47:02+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.rest/commit/b87e371a9a8ad49d9ad0e9b469b91bf358847e7e

requirements and buildout configs: use Plone 6.0.15 and 6.1.2.

Files changed:
M plone-6.0.x.cfg
M plone-6.1.x.cfg
M requirements-6.0.txt
M requirements-6.1.txt
Repository: plone.rest

Branch: refs/heads/main
Date: 2025-09-08T16:57:04+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.rest/commit/1f6555defc53a7d6862c2dffa32e89077e5d7033

Removed versions.cfg and Makefile.

The versions.cfg was only used in the Makefile to get a version for 'black'.
This failed because the command was wrong, trying to install a package called `install`:

```
bin/pip install pip install black==$(awk '/^black =/{print $NF}' versions.cfg)
Requirement already satisfied: pip in ./lib/python3.13/site-packages (25.1.1)
ERROR: Could not find a version that satisfies the requirement install (from versions: none)
```

Also, the Makefile was using Python 3.9, which is not supported on Plone 6.

Files changed:
D Makefile
D versions.cfg
Repository: plone.rest

Branch: refs/heads/main
Date: 2025-09-08T10:54:42-07:00
Author: David Glick (davisagli) <david@glicksoftware.com>
Commit: https://github.com/plone/plone.rest/commit/ab723c18302d1271bbc9f71abe9068b409241970

Remove old buildout and non-meta CI workflow

Files changed:
M MANIFEST.in
D .github/workflows/tests.yml
D base.cfg
D buildout.cfg
D plone-6.0.x.cfg
D plone-6.1.x.cfg
D requirements-6.0.txt
D requirements-6.1.txt
D requirements.txt
Repository: plone.rest

Branch: refs/heads/main
Date: 2025-09-08T10:57:10-07:00
Author: David Glick (davisagli) <david@glicksoftware.com>
Commit: https://github.com/plone/plone.rest/commit/22494477576644e747029cfe65c756e0c8ae13d5

Merge pull request #188 from plone/config-with-default-template-2.0.1.dev0

Update with plone.meta to fix gh-actions

Files changed:
A .github/dependabot.yml
A .github/workflows/test-matrix.yml
A news/+meta.internal
M .editorconfig
M .flake8
M .github/workflows/meta.yml
M .gitignore
M .meta.toml
M .pre-commit-config.yaml
M CHANGES.rst
M MANIFEST.in
M pyproject.toml
M tox.ini
D .github/workflows/tests.yml
D Makefile
D base.cfg
D buildout.cfg
D plone-6.0.x.cfg
D plone-6.1.x.cfg
D requirements-6.0.txt
D requirements-6.1.txt
D requirements.txt
D versions.cfg