[fc] Repository: plone.autoinclude
Branch: refs/heads/main
Date: 2022-01-05T22:32:09+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.autoinclude/commit/ebf95e72f22687fef00c27d24cf7551d0f4365be

Tests buildout3: Add '-U' to force upgrading pip and setuptools.

Files changed:
M tox.ini
Repository: plone.autoinclude

Branch: refs/heads/main
Date: 2022-01-05T22:36:13+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.autoinclude/commit/b311f9f9b92d37cda6c6e363587847afe2212051

Test buildout3: list the versions installed with pip.

Files changed:
M tox.ini
Repository: plone.autoinclude

Branch: refs/heads/main
Date: 2022-01-05T22:54:07+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.autoinclude/commit/44930b6bbf05a7b75394d43211b150cc54d8686d

Test buildout3: let setuptools use distutils from the standard lib.

Since version 60 it uses its own copy.
Let me add the traceback I am trying to fix on GHA:

```
While:
  Installing.
  Getting section test-unit.
  Initializing section test-unit.
  Installing recipe zc.recipe.testrunner.
  Getting distribution for 'zc.recipe.testrunner'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/runner/work/plone.autoinclude/plone.autoinclude/.tox/buildout3/lib/python3.8/site-packages/zc/buildout/buildout.py", line 2250, in main
    getattr(buildout, command)(args)
  File "/home/runner/work/plone.autoinclude/plone.autoinclude/.tox/buildout3/lib/python3.8/site-packages/zc/buildout/buildout.py", line 739, in install
    [self[part]['recipe'] for part in install_parts]
  File "/home/runner/work/plone.autoinclude/plone.autoinclude/.tox/buildout3/lib/python3.8/site-packages/zc/buildout/buildout.py", line 739, in &lt;listcomp&gt;
    [self[part]['recipe'] for part in install_parts]
  File "/home/runner/work/plone.autoinclude/plone.autoinclude/.tox/buildout3/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1372, in __getitem__
    options._initialize()
  File "/home/runner/work/plone.autoinclude/plone.autoinclude/.tox/buildout3/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1480, in _initialize
    self.initialize()
  File "/home/runner/work/plone.autoinclude/plone.autoinclude/.tox/buildout3/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1486, in initialize
    recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)
  File "/home/runner/work/plone.autoinclude/plone.autoinclude/.tox/buildout3/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1429, in _install_and_load
    zc.buildout.easy_install.install(
  File "/home/runner/work/plone.autoinclude/plone.autoinclude/.tox/buildout3/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 965, in install
    return installer.install(specs, working_set)
  File "/home/runner/work/plone.autoinclude/plone.autoinclude/.tox/buildout3/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 690, in install
    for dist in self._get_dist(requirement, ws):
  File "/home/runner/work/plone.autoinclude/plone.autoinclude/.tox/buildout3/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 581, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/home/runner/work/plone.autoinclude/plone.autoinclude/.tox/buildout3/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 1905, in _move_to_eggs_dir_and_compile
    unpacker(dist.location, tmp_dest)
  File "/home/runner/work/plone.autoinclude/plone.autoinclude/.tox/buildout3/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 1839, in unpack_wheel
    wheel.install_as_egg(os.path.join(dest, wheel.egg_name()))
  File "/home/runner/work/plone.autoinclude/plone.autoinclude/.tox/buildout3/lib/python3.8/site-packages/setuptools/wheel.py", line 95, in install_as_egg
    self._install_as_egg(destination_eggdir, zf)
  File "/home/runner/work/plone.autoinclude/plone.autoinclude/.tox/buildout3/lib/python3.8/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
    self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
  File "/home/runner/work/plone.autoinclude/plone.autoinclude/.tox/buildout3/lib/python3.8/site-packages/setuptools/wheel.py", line 164, in _convert_metadata
    setup_dist.get_command_obj('egg_info'),
  File "/home/runner/work/plone.autoinclude/plone.autoinclude/.tox/buildout3/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 859, in get_command_obj
    cmd_obj = self.command_obj[command] = klass(self)
  File "/home/runner/work/plone.autoinclude/plone.autoinclude/.tox/buildout3/lib/python3.8/site-packages/setuptools/__init__.py", line 174, in __init__
    _Command.__init__(self, dist)
  File "/home/runner/work/plone.autoinclude/plone.autoinclude/.tox/buildout3/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
```

setuptools 60.0.0 has this breaking change:

```
2896: Setuptools once again makes its local copy of distutils the default. To override, set SETUPTOOLS_USE_DISTUTILS=stdlib.
```

This may be tripping us up.  Locally on Mac (10.15) it works fine though.

Files changed:
M tox.ini