[fc] Repository: plone.app.event
Branch: refs/heads/master
Date: 2026-03-11T22:37:12+01:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/plone.app.event/commit/403d12023a19caf40a891dabe328c0fa388f3de2

fix(robot): Use element-agnostic XPath for riedit selector

The recurrence widget's 'Add rules' button was changed from &lt;a&gt; to
&lt;button&gt; in plone/mockup#1533 for accessibility. Use //*[@name="riedit"]
instead of //a[@name="riedit"] so the test works with both old and new
mockup versions.

Files changed:
M src/plone/app/event/tests/robot/test_event_roundtrip.robot
Repository: plone.app.event

Branch: refs/heads/master
Date: 2026-03-11T22:38:31+01:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/plone.app.event/commit/3db6648c8fa55c7d6b5558c6204123328e9f9840

Add towncrier news entry for #432

Files changed:
A news/432.tests
Repository: plone.app.event

Branch: refs/heads/master
Date: 2026-03-11T22:47:37+01:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/plone.app.event/commit/d60dc9682e1593356c4658606952ba1f3c87e897

Update configuration via plone/meta 2.x

Adds setuptools&lt;82.0.0 to dependencies tox env to fix
ModuleNotFoundError: No module named 'pkg_resources'.
Also updates isort, black, pyupgrade targets and setuptools
version constraint.

Files changed:
A news/+meta.internal
M .github/workflows/test-matrix.yml
M .meta.toml
M .pre-commit-config.yaml
M pyproject.toml
M tox.ini
Repository: plone.app.event

Branch: refs/heads/master
Date: 2026-03-11T22:50:04+01:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/plone.app.event/commit/17abd267f06f45a26b23c68c9084d81ef4740772

Apply isort 8 import ordering fixes

Files changed:
M docs/conf.py
M setup.py
M src/plone/app/event/__init__.py
M src/plone/app/event/base.py
M src/plone/app/event/dx/behaviors.py
M src/plone/app/event/ical/exporter.py
M src/plone/app/event/interfaces.py
M src/plone/app/event/portlets/portlet_calendar.py
M src/plone/app/event/setuphandlers.py
M src/plone/app/event/tests/base_setup.py
M src/plone/app/event/tests/robot/variables.py
M src/plone/app/event/tests/test_dx_behaviors.py
M src/plone/app/event/tests/test_icalendar.py
M src/plone/app/event/tests/test_portlet_calendar.py
M src/plone/app/event/tests/test_portlet_events.py
M src/plone/app/event/tests/test_recurrence.py
M src/plone/app/event/upgrades/upgrades.py
Repository: plone.app.event

Branch: refs/heads/master
Date: 2026-03-12T07:19:32+01:00
Author: Peter Mathis (petschki) <petschki@users.noreply.github.com>
Commit: https://github.com/plone/plone.app.event/commit/ffc29bbfe8a7461da0b72b8b7af844a2871be7b2

Merge pull request #433 from plone/config-with-default-template-2.5.1

Update configuration via plone/meta 2.x

Files changed:
A news/+meta.internal
A news/432.tests
M .github/workflows/test-matrix.yml
M .meta.toml
M .pre-commit-config.yaml
M docs/conf.py
M pyproject.toml
M setup.py
M src/plone/app/event/__init__.py
M src/plone/app/event/base.py
M src/plone/app/event/dx/behaviors.py
M src/plone/app/event/ical/exporter.py
M src/plone/app/event/interfaces.py
M src/plone/app/event/portlets/portlet_calendar.py
M src/plone/app/event/setuphandlers.py
M src/plone/app/event/tests/base_setup.py
M src/plone/app/event/tests/robot/test_event_roundtrip.robot
M src/plone/app/event/tests/robot/variables.py
M src/plone/app/event/tests/test_dx_behaviors.py
M src/plone/app/event/tests/test_icalendar.py
M src/plone/app/event/tests/test_portlet_calendar.py
M src/plone/app/event/tests/test_portlet_events.py
M src/plone/app/event/tests/test_recurrence.py
M src/plone/app/event/upgrades/upgrades.py
M tox.ini