[fc] Repository: plone.app.upgrade
Branch: refs/heads/master
Date: 2026-02-23T13:53:26+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.upgrade/commit/ebea77e9164edce3f4510d5acd58a5ff4071fbb6

Update cleanup_mimetypes_registry tests to pass on Python 3.14 as well.

This fixes https://github.com/plone/plone.app.upgrade/issues/361

Mostly for myself, let me try to follow what is going on here and what the original problem was that the `cleanup_mimetypes_registry` upgrade step is solving.
This is described in [issue 333](https://github.com/plone/plone.app.upgrade/issues/333).
When a glob is registered in the mimetypes registry, a compiled regular expression is stored in the DB, see the [`register_glob` method](https://github.com/plone/Products.MimetypesRegistry/blob/4.0.0a1/src/Products/MimetypesRegistry/MimeTypesRegistry.py#L159):

```
pattern = re.compile(fnmatch.translate(glob))
```

With glob `foo`, this gives different output depending on your Python version:

* Python 2.7: `foo\\Z(?ms)`
* Python 3.11: `(?s:foo)\\Z`
* Python 3.14: `(?s:foo)\\z`

The special sequence `\\Z` or `\\z` matches only at the end of the string.
The compiled pattern from 2.7 gives a warning when you load it in Python 3.10:

```
&gt;&gt;&gt; re.compile("\\Z(?ms)")
&lt;stdin&gt;:1: DeprecationWarning: Flags not at the start of the expression '\\Z(?ms)' but at position 2
re.compile('\\Z(?ms)', re.MULTILINE|re.DOTALL)
```

On Python 3.11+ it cannot be loaded at all:

```
&gt;&gt;&gt; re.compile("\\Z(?ms)")
Traceback (most recent call last):
...
re.error: global flags not at the start of the expression at position 2
```

This is what was solved by adding this upgrade step in [PR 334](https://github.com/plone/plone.app.upgrade/pull/334).
Basically, if a pattern cannot be loaded, the exception is caught, and the pattern is regenerated by effectively calling the same code again:

```
pattern = re.compile(fnmatch.translate(glob))
```

Problem now is that on Python 3.14 this gives a slightly different pattern that makes the tests fail:
Python 3.14 prefers to create the pattern with underscore `\z` instead of uppercase `\Z`.
These mean the same.  Underscore `\z` was added in 3.14, and `\Z` is kept for backwards compatibility.
See the [reasoning here](https://docs.python.org/3.14/whatsnew/3.14.html#re):
"It is interpreted unambiguously in many other regular expression engines, unlike `\Z`, which has subtly different behavior."

Solution (now that I understand it) is to update the expectations in the tests.

Note that this means that if you would create a Plone 6.2 site with Python 3.14, and then downgrade to 3.13, you would get a similar error:

```
&gt;&gt;&gt; re.compile("foo\\z")
Traceback (most recent call last):
...
re.PatternError: bad escape \z at position 3
```

I don't think we need to handle that anywhere though.

Files changed:
A news/361.tests.rst
M src/plone/app/upgrade/v60/tests.py
Repository: plone.app.upgrade

Branch: refs/heads/master
Date: 2026-02-23T16:28:17+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@py76.be>
Commit: https://github.com/plone/plone.app.upgrade/commit/cecc9b1b90f4261c3ce0de08db7d2a2e56039d08

Merge pull request #362 from plone/maurits-mimetypes-pattern-314

Update cleanup_mimetypes_registry tests to pass on Python 3.14 as well.

Files changed:
A news/361.tests.rst
M src/plone/app/upgrade/v60/tests.py