[fc] Repository: plone.app.upgrade
Branch: refs/heads/master
Date: 2023-09-19T16:04:59+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.upgrade/commit/c8cd2b7cd95a80b021b1295552c6b6824aa3f1fc

Fix error in site syndication settings when upgrading.

Fixes https://github.com/plone/plone.app.upgrade/issues/315

Files changed:
A news/315.bugfix
M plone/app/upgrade/v60/final.py
Repository: plone.app.upgrade

Branch: refs/heads/master
Date: 2023-09-19T16:38:40+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.upgrade/commit/e7877a7a29b719ad2b369b215f0598ba5cce8e6b

site syndication: fix TypeError when site_rss_items value is None.

I ran `black` as well.  The real change is on this line:

    items = list(record.value) if record.value else ()

Traceback:

```
Traceback (most recent call last):
  File "/Users/maurits/shared-eggs/cp310/Products.CMFPlone-6.0.7rc1-py3.10.egg/Products/CMFPlone/MigrationTool.py", line 289, in upgrade
    step["step"].doStep(setup)
  File "/Users/maurits/shared-eggs/cp310/Products.GenericSetup-3.0.1-py3.10.egg/Products/GenericSetup/upgrade.py", line 193, in doStep
    self.handler(tool)
  File "/Users/maurits/shared-eggs/cp310/plone.app.upgrade-3.0.7-py3.10.egg/plone/app/upgrade/v60/final.py", line 183, in fix_syndication_settings
    items = list(record.value)
TypeError: 'NoneType' object is not iterable
```

Files changed:
M plone/app/upgrade/v60/final.py
Repository: plone.app.upgrade

Branch: refs/heads/master
Date: 2023-09-19T17:28:32+02:00
Author: Maurits van Rees (mauritsvanrees) <m.van.rees@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.upgrade/commit/bbdc8d7384d010957cf6916b44265b8e0b9bc9f2

Merge pull request #318 from plone/maurits-syndication

Fix error in site syndication settings when upgrading.

Files changed:
A news/315.bugfix
M plone/app/upgrade/v60/final.py