[fc] Repository: Products.PlonePAS
Branch: refs/heads/master
Date: 2021-12-27T20:37:49-08:00
Author: Ross Patterson (rpatterson) <me@rpatterson.net>
Commit: https://github.com/plone/Products.PlonePAS/commit/0bc883209116766ac66fea07dc661a63a104af34

test(setup): Cover Zope root default challenge

Files changed:
A src/Products/PlonePAS/tests/test_setup.py
Repository: Products.PlonePAS

Branch: refs/heads/master
Date: 2021-12-28T10:24:18-08:00
Author: Ross Patterson (rpatterson) <me@rpatterson.net>
Commit: https://github.com/plone/Products.PlonePAS/commit/17deb979ea4a7c6047cee1cd2a2accdbf7046384

fix(setup): Zope root cookie auth and login form

The GenericSetup "various" import step that originally installs PAS into a Plone portal
also migrates the Zope root `/acl_users`.  Probably an accident over time, but it
results in a cookie auth plugin that doesn't work outside of the Plone portal:

    2021-12-27 11:12:02,243 ERROR   [Zope.SiteErrorLog:22][waitress-0] ComponentLookupError: http://localhost:49080/api/acl_users/credentials_cookie_auth/login
    Traceback (innermost last):
      Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
      Module ZPublisher.WSGIPublisher, line 372, in publish_module
      Module ZPublisher.WSGIPublisher, line 266, in publish
      Module ZPublisher.mapply, line 85, in mapply
      Module ZPublisher.WSGIPublisher, line 63, in call_object
      Module Products.PlonePAS.plugins.cookie_handler, line 106, in login
      Module Products.PluggableAuthService.PluggableAuthService, line 1153, in updateCredentials
      Module Products.PlonePAS.plugins.cookie_handler, line 74, in updateCredentials
      Module zope.component._api, line 165, in getUtility
    zope.interface.interfaces.ComponentLookupError: (&lt;InterfaceClass plone.registry.interfaces.IRegistry&gt;, '')

This import step also removes the `login_form` template which breaks the challenge
response.

Add an interface check to decide whether to install Plone's `ExtendedCookieAuthHelper`
or PAS's vanilla `CookieAuthHelper`.

Files changed:
A news/65.bugfix
M src/Products/PlonePAS/setuphandlers.py
M src/Products/PlonePAS/tests/test_setup.py
Repository: Products.PlonePAS

Branch: refs/heads/master
Date: 2021-12-29T21:42:42+01:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/Products.PlonePAS/commit/7eb180236c3cfdf52a56e1b64b322dcc86325f3a

Merge pull request #65 from plone/fix-zope-root-cookie-auth

fix(setup): Zope root cookie auth and login form

Files changed:
A news/65.bugfix
A src/Products/PlonePAS/tests/test_setup.py
M src/Products/PlonePAS/setuphandlers.py