[fc] Repository: plone.app.upgrade
Branch: refs/heads/master
Date: 2020-10-02T16:32:46+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.upgrade/commit/5a3ff31214a5c6c3ba9f9a740dc103cbe058c2ec

6.0 alpha 1: remove the portal_quickinstaller tool.

See PLIP 1775: https://github.com/plone/Products.CMFPlone/issues/1775

Files changed:
A news/1775.breaking
A plone/app/upgrade/v60/profiles/to_alpha1/toolset.xml
Repository: plone.app.upgrade

Branch: refs/heads/master
Date: 2020-10-02T16:32:46+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.upgrade/commit/47bff6264185a5ec90b859747c6b2819c02b12d0

Try out some BBB code for CMFQuickInstallerTool.

Files changed:
A plone/app/upgrade/bbb_qi/InstalledProduct.py
A plone/app/upgrade/bbb_qi/QuickInstallerTool.py
A plone/app/upgrade/bbb_qi/__init__.py
A plone/app/upgrade/bbb_qi/interfaces/__init__.py
A plone/app/upgrade/bbb_qi/interfaces/installable.py
A plone/app/upgrade/bbb_qi/interfaces/portal_quickinstaller.py
M plone/app/upgrade/__init__.py
Repository: plone.app.upgrade

Branch: refs/heads/master
Date: 2020-10-02T16:32:46+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.upgrade/commit/0bfc3f6339b320c98f63fd2706186a9f5ae48c57

Add BBB for Products.CMFPlone.QuickInstallerTool

Files changed:
M plone/app/upgrade/__init__.py
Repository: plone.app.upgrade

Branch: refs/heads/master
Date: 2020-10-02T16:32:46+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.upgrade/commit/5ce7c2e2644ebb37559445447acc773c9c31aef1

On Python 3 in testDoUpgrades only test upgrade from Plone 5.2.

You cannot upgrade a Plone 4.0 or 5.1 site to 5.2 or higher when you are on Python 3.
You must first migrate to 5.2 with Python 2.7.
Also, this avoids a test failure on 6.0 because the 5.0alpha upgrade calls qi.isProductInstalled, which has been removed.

Files changed:
M plone/app/upgrade/tests/test_upgrade.py
Repository: plone.app.upgrade

Branch: refs/heads/master
Date: 2020-10-02T16:32:46+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.upgrade/commit/e12629081a5be5fe231e33d68e9fd46642ec6c66

Fix AttributeError: 'InstallerView' object has no attribute 'isProductInstalled'

Files changed:
M plone/app/upgrade/tests/base.py
Repository: plone.app.upgrade

Branch: refs/heads/master
Date: 2020-10-02T22:10:04+02:00
Author: Maurits van Rees (mauritsvanrees) <m.van.rees@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.upgrade/commit/30eb0fbf4e79f496be48ca597fca155648cf7d08

Merge pull request #248 from plone/maurits/no-qi

Plone 6: remove quick installer code

Files changed:
A news/1775.breaking
A plone/app/upgrade/bbb_qi/InstalledProduct.py
A plone/app/upgrade/bbb_qi/QuickInstallerTool.py
A plone/app/upgrade/bbb_qi/__init__.py
A plone/app/upgrade/bbb_qi/interfaces/__init__.py
A plone/app/upgrade/bbb_qi/interfaces/installable.py
A plone/app/upgrade/bbb_qi/interfaces/portal_quickinstaller.py
A plone/app/upgrade/v60/profiles/to_alpha1/toolset.xml
M plone/app/upgrade/__init__.py
M plone/app/upgrade/tests/base.py
M plone/app/upgrade/tests/test_upgrade.py