[fc] Repository: plone.namedfile
Branch: refs/heads/master
Date: 2022-05-15T18:39:23+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/691114dae307bc29786da1ede46ba4cd6384de4c

Call new pre_scale and get_or_generate from plone.scale.

See branch pre-scale of plone.scale.

Files changed:
M plone/namedfile/scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-05-16T17:09:07+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/7de488efa143f16c367afc3d83c784a756b8c128

Use 'pre' at the right places.

Files changed:
M plone/namedfile/scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-05-17T10:42:09+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/a5f1338bcfe0cae236f7f744cd471501a5596345

Do not include old-style srcset when requesting a scale via a url.

Only do this when pre=True, so when generating a tag.
You can override the standard behavior by explicitly passing new boolean parameter include_srcset.

Files changed:
M plone/namedfile/scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-05-17T11:13:33+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/340c41188a55c2b94e6a411c83396dc8593ad703

Merge branch 'master' into pre-scale

Files changed:
M tox.ini
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-05-17T15:57:55+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/ce07e8de5c46706651410548c1a34466c6162226

Add images-test view, only for Editors.

Show some versions of the image with different directions.
Show stored scales.
Add button for clearing the scales.

Currently only works when the fieldname is 'image' and there is an actual image.

Files changed:
A plone/namedfile/test.pt
M plone/namedfile/scaling.py
M plone/namedfile/scaling.zcml
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-05-17T16:15:40+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/ce1cf5fd02e99d9d7c7816436ab377e3b152eb54

From Products.CMFCore only load permissions.zcml.

Avoids a weird undefined genericsetup:importStep in CMFCore/exportimport/configure.zcml

Files changed:
M plone/namedfile/scaling.zcml
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-05-17T18:11:23+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/de6903d0b7cc9eb8808467b22bff4de2a90a8cca

mxdev: use the pre-scale branch of plone.scale.

Files changed:
M sources-52.ini
M sources-60.ini
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-05-17T22:45:25+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/3fda001ffbf589aef9870593d5b6156aaf0c4f46

Start fixing tests.

Files changed:
M .gitignore
M plone/namedfile/tests/test_scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-05-17T22:46:00+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/4e3d3b9935465af34c82a5291f9186dd4160c8e5

Merge branch 'master' into pre-scale

Files changed:
A news/114.bugfix
M plone/namedfile/scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-05-18T10:21:51+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/4a262a387f195cb6e0ba77ce7793c053c5be06fa

We need to pass include_srcset=True in tests.

Otherwise the scale method thinks we only want the current actual image scale, and then the srcset info would be useless so it does not include it.

Files changed:
M plone/namedfile/tests/test_scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-05-18T10:23:04+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/ec3cd655ed03b3fdeb7bc8b7c3a4183969738ee7

Fixed the tests for srcsets.

This shows we do not get the generated scale for the srcsets anymore.

Files changed:
M plone/namedfile/tests/test_scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-05-18T16:11:45+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/6a2f4511c56695b9bda1236126b7e2f244a0a80b

Added news snippets

Files changed:
A news/113.feature.1
A news/113.feature.2
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-05-18T16:24:50+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/6b90fa02b99ddd925d267ea5244d4752c6fc1d1b

images-test: sort the scales nicely

Files changed:
M plone/namedfile/scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-05-18T17:11:45+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/291b85e24bdb361b47338b0a413b4c89d12d6446

images-test: add link to open image scale in new tab.

Files changed:
M plone/namedfile/test.pt
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-05-20T17:03:41+03:00
Author: MrTango (MrTango) <md@derico.de>
Commit: https://github.com/plone/plone.namedfile/commit/50aa9b4ea11a48e87abc6e258063877b13a16389

prevent unknown keyword parameter modified

Files changed:
M plone/namedfile/scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-05-23T21:53:11+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/e0ce960b249bc8cea8eeef160905d6d082757f23

Catch TypeError when getting IPrimaryFieldInfo.

For example when adapting a Folder:

```
TypeError: http://localhost:8080/Plone/@@ajax-search
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 167, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 376, in publish_module
  Module ZPublisher.WSGIPublisher, line 271, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 68, in call_object
  Module Products.CMFPlone.browser.search, line 288, in __call__
  Module Products.CMFPlone.browser.search, line 303, in get_image_tag
  Module plone.memoize.volatile, line 74, in replacement
  Module plone.namedfile.scaling, line 600, in tag
  Module plone.namedfile.scaling, line 582, in tag
  Module plone.namedfile.scaling, line 510, in scale
  Module plone.scale.storage, line 220, in pre_scale
  Module plone.namedfile.scaling, line 200, in get_original_value
  Module zope.component.hooks, line 135, in adapter_hook
  Module plone.dexterity.primary, line 24, in __init__
TypeError: ('Could not adapt', &lt;Folder at /Plone/news&gt;, &lt;InterfaceClass plone.rfc822.interfaces.IPrimaryFieldInfo&gt;)
```

Files changed:
M plone/namedfile/scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-05-23T22:29:30+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/25d08144ec1811c6fbc2528d1c4cc09a4bad06ab

Do call IPrimaryFieldInfo with self.context and None, like before.

This does actually return None in some cases.

Files changed:
M plone/namedfile/scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-05-23T22:32:38+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/af46d750c3f618f44c13c6318b27646964239401

get_original_value: return IPrimaryFieldInfo.value

Files changed:
M plone/namedfile/scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-05-23T22:33:21+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/070740f23c136cf567c8be701066563fe192cdac

calculate_srcset: if scale_src is None, do not treat it as dictionary.

Files changed:
M plone/namedfile/scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-05-23T22:49:35+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/06a0a5c3effa77a38e3e3c291662b760a2ef966d

Register adapter for primary field info in tests.

Files changed:
M plone/namedfile/tests/test_scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-05-24T00:13:46+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/22f5a8aee13b43e81608d7214665246ad572d2eb

Fix undefined names in primary field code.

Files changed:
M plone/namedfile/scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-05-24T08:47:53+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/9ef547e7f39220a8477fd9fd87de0ac966a6f842

Merge branch 'master' into pre-scale

Files changed:
A news/118.bugfix
M plone/namedfile/scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-05-24T09:09:10+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/369d46816a96ef0eccfffd505ea6d938d956db9a

Accept fieldname in get_original_value.

Otherwise it depends on having self.fieldname, which is not set here.
Then it falls back to IPrimaryFieldInfo.
In case of a news item with lead image, this does not find anything.

Do not register adapter for IPrimaryFieldInfo in functional tests, only in the integration tests.
I added this registration yesterday to fix some test failures.
I did not see that the test failures were problems that actually needed fixing.
I do that in this commit, plus one in plone.scale.

Files changed:
M plone/namedfile/scaling.py
M plone/namedfile/tests/test_scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-06-01T21:04:54+03:00
Author: MrTango (MrTango) <md@derico.de>
Commit: https://github.com/plone/plone.namedfile/commit/163ae3476f5cc0ed46f93e824668ac4ca67dbe6c

black formating

Files changed:
M plone/namedfile/scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-06-01T21:06:01+03:00
Author: MrTango (MrTango) <md@derico.de>
Commit: https://github.com/plone/plone.namedfile/commit/0b2dd7be9f39b0a0e77f2249dfc7a7db36730891

Add picture method to ImageScaling and include it in test.pt

Files changed:
M plone/namedfile/scaling.py
M plone/namedfile/test.pt
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-06-02T10:34:30+03:00
Author: MrTango (MrTango) <md@derico.de>
Commit: https://github.com/plone/plone.namedfile/commit/e085b96d608abcbb4db6222ce5ea97e6b5222c13

Set width and height in picture method, update examples in test.pt

Files changed:
M plone/namedfile/scaling.py
M plone/namedfile/test.pt
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-06-02T11:10:36+03:00
Author: MrTango (MrTango) <md@derico.de>
Commit: https://github.com/plone/plone.namedfile/commit/d75880a6369b227d25fc19aa7cb7bda7d8bd0cc0

Add title and alt attributes, add changelog entry

Files changed:
A news/113.feature.3
M plone/namedfile/scaling.py
M plone/namedfile/test.pt
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-06-03T19:42:26+03:00
Author: MrTango (MrTango) <md@derico.de>
Commit: https://github.com/plone/plone.namedfile/commit/430b5957fdc3c0b7af912e684b09b07451e4c2a8

move utils.Img2PictureTag from outputfilter to namedfile.picture

Files changed:
A plone/namedfile/picture.py
M plone/namedfile/scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-06-03T19:43:03+03:00
Author: MrTango (MrTango) <md@derico.de>
Commit: https://github.com/plone/plone.namedfile/commit/cc1036c4ff4ec8c3d59875d0a36d4e339f71d662

use PloneSandboxLayer for testing

Files changed:
M plone/namedfile/testing.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-06-03T19:43:40+03:00
Author: MrTango (MrTango) <md@derico.de>
Commit: https://github.com/plone/plone.namedfile/commit/87649137a1731acba98d68d211c4a0a7e0008e86

use resolve_urls and uid params for create_picture_tag

Files changed:
M plone/namedfile/scaling.py
M plone/namedfile/tests/test_scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-06-04T00:11:13+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/3bd293cc0803c0c47e3a6802c8d2c8442a90f9e8

Tests: add UID to DummyContent and patch uuidToObject.

This does a very small start for fixing the tests.

Files changed:
M plone/namedfile/tests/test_scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-06-07T14:44:40+03:00
Author: MrTango (MrTango) <md@derico.de>
Commit: https://github.com/plone/plone.namedfile/commit/fe0850c9c67e2cd48eca69552dd4984de810088d

Revert "use PloneSandboxLayer for testing"

This reverts commit cc1036c4ff4ec8c3d59875d0a36d4e339f71d662.

Files changed:
M plone/namedfile/testing.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-06-07T17:24:39+03:00
Author: MrTango (MrTango) <md@derico.de>
Commit: https://github.com/plone/plone.namedfile/commit/8d0567ee3cdd194316fe81dc26fc6610173b956c

rename image_srcsets to picture_variants, fix captioning

Files changed:
M plone/namedfile/picture.py
M plone/namedfile/scaling.py
M plone/namedfile/tests/test_scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-06-08T16:08:10+03:00
Author: MrTango (MrTango) <md@derico.de>
Commit: https://github.com/plone/plone.namedfile/commit/bddd88ad56665019e9d869e154597cf70dfc01ad

refacture picture.py and fix tests

Files changed:
M plone/namedfile/picture.py
M plone/namedfile/scaling.py
M plone/namedfile/tests/test_scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-06-08T16:08:20+03:00
Author: MrTango (MrTango) <md@derico.de>
Commit: https://github.com/plone/plone.namedfile/commit/aafadf83d63e8386e9ff9677827c0a4f29416185

black fixes

Files changed:
M plone/namedfile/tests/test_scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-06-08T16:08:49+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/112b0e361fd4aa6680949e23a7604f2ab78f08a2

Fixed import for Plone 5.2.

We do not have plone.base there.
The picture method is not supported on 5.2, but it would be nice if the rest of the code still works.
I think get_picture_variants is mocked away in all tests, and this helps us.

Files changed:
M plone/namedfile/picture.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-06-08T16:13:22+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/1c2ce5e8832dceb452950d023711b798c20def8f

black picture

Files changed:
M plone/namedfile/picture.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-06-08T16:57:01+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/b1818528a1cf5abfc20503d91b409f62a9000afd

Let picture method return an img tag if the picture variant is not found.

When a template calls the picture method, it seems nicer to return a normal img tag in case of problems.
This also helps for Plone 5.2.

Files changed:
M plone/namedfile/picture.py
M plone/namedfile/scaling.py
M plone/namedfile/tests/test_scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-06-08T17:58:19+03:00
Author: MrTango (MrTango) <md@derico.de>
Commit: https://github.com/plone/plone.namedfile/commit/b64457cd101e2a63658abecd3afbf6dc1e0ab7e7

use plone.app.uuid.utils.uuidToObject

Files changed:
M plone/namedfile/picture.py
M plone/namedfile/scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-06-08T17:59:05+03:00
Author: MrTango (MrTango) <md@derico.de>
Commit: https://github.com/plone/plone.namedfile/commit/0833abae6403b4eb616f14790b22ccc5508a358a

Merge branch 'pre-scale-picture-tag' of https://github.com/plone/plone.namedfile into pre-scale-picture-tag

Files changed:
M plone/namedfile/picture.py
M plone/namedfile/scaling.py
M plone/namedfile/tests/test_scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-06-08T17:03:04+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/5983331f737bb3e1ea68b5f53a3b19b10ac916d4

Add dependency on plone.app.uuid

Files changed:
M setup.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-06-08T18:14:39+03:00
Author: MrTango (MrTango) <md@derico.de>
Commit: https://github.com/plone/plone.namedfile/commit/c4c68a6429fe9dfb648dd6b92e894248fed16f89

cleanup print statements

Files changed:
M plone/namedfile/scaling.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-06-08T18:14:47+03:00
Author: MrTango (MrTango) <md@derico.de>
Commit: https://github.com/plone/plone.namedfile/commit/74ea17c1140751e134babe8c96228ff911494fbf

Merge branch 'pre-scale-picture-tag' of https://github.com/plone/plone.namedfile into pre-scale-picture-tag

Files changed:
M setup.py
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-06-08T18:07:08+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/8613ff2cbf7e23914ba20c5aa1c05f1762c6cb30

Update test.pt

Files changed:
M plone/namedfile/test.pt
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-06-08T21:58:35+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/8660d4ed36e90e52031c5e8c1574eabf4677efc8

Update news snippet.

Files changed:
M news/113.feature.3
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-06-08T21:59:15+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/26ce3a877d8c06dd11c20b7606204ba189984be9

Merge branch 'master' into pre-scale

Files changed:
M CHANGES.rst
M setup.py
D news/114.bugfix
D news/118.bugfix
Repository: plone.namedfile

Branch: refs/heads/master
Date: 2022-06-09T13:18:36+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.namedfile/commit/30f59c59cc37a64bf438235b1e288879b1126737

Merge pull request #113 from plone/pre-scale

Call new pre_scale and get_or_generate from plone.scale.

Files changed:
A news/113.feature.1
A news/113.feature.2
A news/113.feature.3
A plone/namedfile/picture.py
A plone/namedfile/test.pt
M .gitignore
M plone/namedfile/scaling.py
M plone/namedfile/scaling.zcml
M plone/namedfile/tests/test_scaling.py
M setup.py
M sources-52.ini
M sources-60.ini