[fc] Repository: plone.app.robotframework
Branch: refs/heads/master
Date: 2022-05-02T10:04:04+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.robotframework/commit/d1ff29dd118faad27d9d85362cd33c67e2fe6911

Removed unused files.

Files changed:
M README.rst
M setup.cfg
D Gemfile
D buildout-varnish.cfg
D templates/varnish.vcl.in
D travis.cfg
D versions.cfg
Repository: plone.app.robotframework

Branch: refs/heads/master
Date: 2022-05-02T10:04:27+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.robotframework/commit/0ea272b63118591f6f49bcd41713da52188d165c

isort

Files changed:
M docs/source/conf.py
M setup.py
M src/plone/app/robotframework/__init__.py
M src/plone/app/robotframework/autologin.py
M src/plone/app/robotframework/config.py
M src/plone/app/robotframework/content.py
M src/plone/app/robotframework/patches.py
M src/plone/app/robotframework/quickinstaller.py
M src/plone/app/robotframework/remote.py
M src/plone/app/robotframework/robotentrypoints.py
M src/plone/app/robotframework/server.py
M src/plone/app/robotframework/tests/test_robot.py
M src/plone/app/robotframework/utils.py
M src/plone/app/robotframework/variables.py
Repository: plone.app.robotframework

Branch: refs/heads/master
Date: 2022-05-02T10:04:51+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.robotframework/commit/212001c70e985771cff0bd64656164e0be7fd467

black

Files changed:
M docs/source/conf.py
M setup.py
M src/plone/__init__.py
M src/plone/app/__init__.py
M src/plone/app/robotframework/__init__.py
M src/plone/app/robotframework/annotate.py
M src/plone/app/robotframework/autologin.py
M src/plone/app/robotframework/config.py
M src/plone/app/robotframework/content.py
M src/plone/app/robotframework/genericsetup.py
M src/plone/app/robotframework/i18n.py
M src/plone/app/robotframework/keywords.py
M src/plone/app/robotframework/mailhost.py
M src/plone/app/robotframework/pybabel.py
M src/plone/app/robotframework/quickinstaller.py
M src/plone/app/robotframework/reload.py
M src/plone/app/robotframework/remote.py
M src/plone/app/robotframework/robotentrypoints.py
M src/plone/app/robotframework/saucelabs.py
M src/plone/app/robotframework/server.py
M src/plone/app/robotframework/testing.py
M src/plone/app/robotframework/tests/test_content.py
M src/plone/app/robotframework/tests/test_robot.py
M src/plone/app/robotframework/tests/test_robotfixture.py
M src/plone/app/robotframework/users.py
M src/plone/app/robotframework/utils.py
M src/plone/app/robotframework/variables.py
Repository: plone.app.robotframework

Branch: refs/heads/master
Date: 2022-05-02T10:06:14+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.robotframework/commit/4211e0f2df7064b107dbce0fb52d3de7b11f26d0

pyupgrade --py36-plus

I kept 3.6 compatibility, because we might need this to test plone.restapi on Plone 5.2-Py3.

Files changed:
M docs/source/conf.py
M src/plone/app/robotframework/__init__.py
M src/plone/app/robotframework/annotate.py
M src/plone/app/robotframework/autologin.py
M src/plone/app/robotframework/config.py
M src/plone/app/robotframework/content.py
M src/plone/app/robotframework/genericsetup.py
M src/plone/app/robotframework/i18n.py
M src/plone/app/robotframework/keywords.py
M src/plone/app/robotframework/mailhost.py
M src/plone/app/robotframework/patches.py
M src/plone/app/robotframework/pybabel.py
M src/plone/app/robotframework/quickinstaller.py
M src/plone/app/robotframework/reload.py
M src/plone/app/robotframework/remote.py
M src/plone/app/robotframework/robotentrypoints.py
M src/plone/app/robotframework/saucelabs.py
M src/plone/app/robotframework/server.py
M src/plone/app/robotframework/testing.py
M src/plone/app/robotframework/tests/test_robot.py
M src/plone/app/robotframework/tests/test_robotfixture.py
M src/plone/app/robotframework/users.py
M src/plone/app/robotframework/variables.py
Repository: plone.app.robotframework

Branch: refs/heads/master
Date: 2022-05-02T10:09:17+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.robotframework/commit/957ccee9a66bd034c32ffd41ac90c76534ad5d99

isort/black

Files changed:
M setup.cfg
M src/plone/app/robotframework/content.py
M src/plone/app/robotframework/quickinstaller.py
M src/plone/app/robotframework/reload.py
M src/plone/app/robotframework/server.py
M src/plone/app/robotframework/tests/test_robot.py
Repository: plone.app.robotframework

Branch: refs/heads/master
Date: 2022-05-02T10:10:13+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.robotframework/commit/97466277a4bb9a04cf9f79ebb1b4ed82277f2a48

Removed sys.version_info check froms setup.py

Files changed:
M setup.cfg
M setup.py
Repository: plone.app.robotframework

Branch: refs/heads/master
Date: 2022-05-02T10:14:28+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.robotframework/commit/75e3c883c8afe3c8b7bb2b33b44c7fb63d0609ab

Removed six.

Files changed:
M setup.py
M src/plone/app/robotframework/content.py
M src/plone/app/robotframework/pybabel.py
M src/plone/app/robotframework/saucelabs.py
M src/plone/app/robotframework/server.py
M src/plone/app/robotframework/testing.py
Repository: plone.app.robotframework

Branch: refs/heads/master
Date: 2022-05-02T10:27:16+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.robotframework/commit/268fe893d418d7c84dadc96a1b12380a3374dcb1

Removed backwards compatibility code for older Plone versions.

We always have dexterity.

Files changed:
M src/plone/app/robotframework/config.py
M src/plone/app/robotframework/content.py
M src/plone/app/robotframework/i18n.py
M src/plone/app/robotframework/saucelabs.py
M src/plone/app/robotframework/server.py
M src/plone/app/robotframework/testing.py
M src/plone/app/robotframework/tests/test_robotfixture.py
M src/plone/app/robotframework/utils.py
Repository: plone.app.robotframework

Branch: refs/heads/master
Date: 2022-05-02T10:35:26+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.robotframework/commit/e11ff67b9393e338d07f79023ce0ebf7fd320099

Removed Archetypes from code, include reference browser.

Note: `content.rst` in the docs still points to a field with archetypes in the css.
The documentation may need a more thorough overhaul in a different PR.

Files changed:
M docs/source/index.rst
M docs/source/plone-keywords/index.rst
M src/plone/app/robotframework/content.py
M src/plone/app/robotframework/keywords.robot
D docs/source/plone-keywords/reference-browser-widget.rst
Repository: plone.app.robotframework

Branch: refs/heads/master
Date: 2022-05-02T10:55:41+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.robotframework/commit/dffa1b81dcb13f12172ae48e24cf5d448acc6489

flake8

Files changed:
M src/plone/app/robotframework/pybabel.py
M src/plone/app/robotframework/remote.py
M src/plone/app/robotframework/robotentrypoints.py
M src/plone/app/robotframework/server.py
M src/plone/app/robotframework/testing.py
M src/plone/app/robotframework/tests/test_robot.py
Repository: plone.app.robotframework

Branch: refs/heads/master
Date: 2022-05-02T11:10:43+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.robotframework/commit/36f0bcc2a5faa14df72897529ba8e0cedcb2ece7

news snippet

Files changed:
A news/129.breaking
Repository: plone.app.robotframework

Branch: refs/heads/master
Date: 2022-05-02T12:30:43+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.robotframework/commit/087c1005aeaa4d402fb39a564d0bca286c95b8a9

random_image: return the bytes, not the BytesIO object.

The `NamedImage` class that was accidentally used before  could handle this.
But with `NamedBlobImage` it resulted in a few test failures like this:

```
Failure in test Scenario A page is opened to edit in TinyMCE (test_tinymce.robot)
Traceback (most recent call last):
  File "/Users/maurits/.pyenv/versions/3.9.9/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/maurits/.pyenv/versions/3.9.9/lib/python3.9/unittest/case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "/Users/maurits/.pyenv/versions/3.9.9/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/Users/maurits/community/plone-coredev/6.0/src/robotsuite/src/robotsuite/__init__.py", line 514, in runTest
    assert last_status == 'PASS', last_message
AssertionError: (&lt;InterfaceClass plone.namedfile.interfaces.IStorage&gt;, '_io.BytesIO')
```

Files changed:
M src/plone/app/robotframework/content.py
Repository: plone.app.robotframework

Branch: refs/heads/master
Date: 2022-05-02T22:56:03+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.robotframework/commit/30ba1bc6d6e76a38807589e49a065a78cd723834

Make compatible with robotframework 3-5.

Files changed:
A news/5.bugfix
M src/plone/app/robotframework/saucelabs.py
Repository: plone.app.robotframework

Branch: refs/heads/master
Date: 2022-05-03T01:14:03+02:00
Author: Gil Forcada Codinachs (gforcada) <gil.gnome@gmail.com>
Commit: https://github.com/plone/plone.app.robotframework/commit/3591014b0a753927adaaea46dfb35d1ddb113e53

Merge pull request #130 from plone/robotframework5

Make compatible with robotframework 3-5

Files changed:
A news/129.breaking
A news/5.bugfix
M README.rst
M docs/source/conf.py
M docs/source/index.rst
M docs/source/plone-keywords/index.rst
M setup.cfg
M setup.py
M src/plone/__init__.py
M src/plone/app/__init__.py
M src/plone/app/robotframework/__init__.py
M src/plone/app/robotframework/annotate.py
M src/plone/app/robotframework/autologin.py
M src/plone/app/robotframework/config.py
M src/plone/app/robotframework/content.py
M src/plone/app/robotframework/genericsetup.py
M src/plone/app/robotframework/i18n.py
M src/plone/app/robotframework/keywords.py
M src/plone/app/robotframework/keywords.robot
M src/plone/app/robotframework/mailhost.py
M src/plone/app/robotframework/patches.py
M src/plone/app/robotframework/pybabel.py
M src/plone/app/robotframework/quickinstaller.py
M src/plone/app/robotframework/reload.py
M src/plone/app/robotframework/remote.py
M src/plone/app/robotframework/robotentrypoints.py
M src/plone/app/robotframework/saucelabs.py
M src/plone/app/robotframework/server.py
M src/plone/app/robotframework/testing.py
M src/plone/app/robotframework/tests/test_content.py
M src/plone/app/robotframework/tests/test_robot.py
M src/plone/app/robotframework/tests/test_robotfixture.py
M src/plone/app/robotframework/users.py
M src/plone/app/robotframework/utils.py
M src/plone/app/robotframework/variables.py
D Gemfile
D buildout-varnish.cfg
D docs/source/plone-keywords/reference-browser-widget.rst
D templates/varnish.vcl.in
D travis.cfg
D versions.cfg