[fc] Repository: plone.app.ldap
Branch: refs/heads/master
Date: 2019-09-18T15:50:04+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.ldap/commit/bad73d5734c207669486284bf4023aa6c5432300

Simplified test buildout and Travis setup.

There is no need for code-analysis (which will just fail to be installed, most likely).
And i18ndude is not used.
And let's just use a setuptools and zc.buildout from this year.
I triggered a build today and it completely failed:
https://travis-ci.org/plone/plone.app.ldap/builds/586513573

Files changed:
A buildout.cfg
A requirements.txt
M .travis.yml
D bootstrap.py
D travis.cfg
Repository: plone.app.ldap

Branch: refs/heads/master
Date: 2019-09-18T16:03:17+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.ldap/commit/6314b63346c031fa2224d0f5f975ff4b1a125e5c

Added dependencies so Plone 5 can start.

Note that these dependencies {zope,five}.formlib and plone.app.form,
are in Plon 4.2 and 4.3 by default, so nothing changes there.

Removed the Plone 5 classifiers, because there is a test failure,
and it can't have worked before.

Also removed the Python 2.6 classifier, because we really do not test with that anymore.

Files changed:
M .travis.yml
M CHANGES.rst
M setup.py
Repository: plone.app.ldap

Branch: refs/heads/master
Date: 2019-09-18T16:34:03+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.ldap/commit/32d435f6bd27360fcd7a7d6ec7a22c7335c8b088

Use older zc.buildout and setuptools versions, so Plone 4.2 still works.

Files changed:
M requirements.txt
Repository: plone.app.ldap

Branch: refs/heads/master
Date: 2019-09-18T22:10:37+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.ldap/commit/e52343782bd3fc8b3f1ad48c5db1dc98166aa8c8

We need more version pins so the buildout succeeds for 4.2-5.0.

In Plone 5.0 you do get a ComponentLookupError in one test.
We are already allowing test failures on 5.0 in Travis.
But now the buildout at least finishes, and five of the six tests pass.

Error in test test_controlpanel_has_view (plone.app.ldap.tests.test_controlpanel.ControlPanelTestCase)
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/maurits/clients/vmm/hoofdsite-9151/checkouts/plone.app.ldap/plone/app/ldap/tests/test_controlpanel.py", line 22, in test_controlpanel_has_view
    self.assertTrue(view())
  File "/Users/maurits/shared-eggs/cp27m/zope.formlib-4.3.0-py2.7.egg/zope/formlib/form.py", line 868, in __call__
    self.update()
  File "/Users/maurits/shared-eggs/cp27m/five.formlib-1.0.4-py2.7.egg/five/formlib/formbase.py", line 50, in update
    super(FiveFormlibMixin, self).update()
  File "/Users/maurits/shared-eggs/cp27m/zope.formlib-4.3.0-py2.7.egg/zope/formlib/form.py", line 831, in update
    self.setUpWidgets()
  File "/Users/maurits/shared-eggs/cp27m/zope.formlib-4.3.0-py2.7.egg/zope/formlib/form.py", line 906, in setUpWidgets
    adapters=self.adapters, ignore_request=ignore_request
  File "/Users/maurits/shared-eggs/cp27m/zope.formlib-4.3.0-py2.7.egg/zope/formlib/form.py", line 407, in setUpEditWidgets
    widget = _createWidget(form_field, field, request, iface)
  File "/Users/maurits/shared-eggs/cp27m/zope.formlib-4.3.0-py2.7.egg/zope/formlib/form.py", line 337, in _createWidget
    return component.getMultiAdapter((field, request), iface)
  File "/Users/maurits/shared-eggs/cp27m/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 109, in getMultiAdapter
    raise ComponentLookupError(objects, interface, name)
ComponentLookupError: ((&lt;zope.schema._field.Choice object at 0x10f669f10&gt;, &lt;HTTPRequest, URL=http://nohost&gt;), &lt;InterfaceClass zope.formlib.interfaces.IInputWidget&gt;, u'')

Files changed:
M buildout.cfg
Repository: plone.app.ldap

Branch: refs/heads/master
Date: 2019-09-18T22:41:48+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.ldap/commit/fa490dcd44f16d064a27b2f5cafbb1c9bd841857

Added find-links to find elementtree on Plone 4.2.

Files changed:
M buildout.cfg
Repository: plone.app.ldap

Branch: refs/heads/master
Date: 2019-09-19T16:11:41+02:00
Author: Maurits van Rees (mauritsvanrees) <m.van.rees@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.ldap/commit/050b647d5c86c89ee66cf94c0fe5f2ae4e45abba

Merge pull request #36 from plone/maurits/fix-travis

Fix Travis.

Files changed:
A buildout.cfg
A requirements.txt
M .travis.yml
M CHANGES.rst
M setup.py
D bootstrap.py
D travis.cfg