[fc] Repository: Products.CMFPlone
Branch: refs/heads/master
Date: 2026-02-19T13:16:30+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/e161621c5da88a37e8c8740fd4ca48356ca94702

Skip security tests for `string._re` on Python 3.14.

It does not exist anymore

Up until Python 3.13, the `string` module imported the `re` module and made it available as `_re`.  Some tests check that this cannot be abused.
But in 3.14 this is no longer the case, so you get three test failures like this:

```
$ bin/test -s Products.CMFPlone -m test_expressions -t test_traverse_function_string
...
Error in test test_traverse_function_string (Products.CMFPlone.tests.test_expressions.TestDirectAttackVector.test_traverse_function_string)
Traceback (most recent call last):
  File "/Users/maurits/.pyenv/versions/3.14.2/lib/python3.14/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/Users/maurits/.pyenv/versions/3.14.2/lib/python3.14/unittest/case.py", line 669, in run
    self._callTestMethod(testMethod)
  File "/Users/maurits/.pyenv/versions/3.14.2/lib/python3.14/unittest/case.py", line 615, in _callTestMethod
    result = method()
  File "/Users/maurits/community/plone-coredev/6.2/src/Products.CMFPlone/src/Products/CMFPlone/tests/test_expressions.py", line 143, in test_traverse_function_string
    traverse_function(string, ("_re", "purge"), None)
  File "/Users/maurits/shared-eggs/v5/cp314/Zope-6.0b2-py3.14-macosx-26.2-arm64.egg/Products/PageTemplates/Expressions.py", line 87, in boboAwareZopeTraverse
    found = traversePathElement(object, name, path_items,
  File "/Users/maurits/shared-eggs/v5/cp314/zope.traversing-6.0-py3.14-macosx-26.2-arm64.egg/zope/traversing/adapters.py", line 149, in traversePathElement
    return traversable.traverse(nm, further_path)
  File "/Users/maurits/shared-eggs/v5/cp314/zope.traversing-6.0-py3.14-macosx-26.2-arm64.egg/zope/traversing/adapters.py", line 54, in traverse
    raise LocationError(subject, name)
zope.location.interfaces.LocationError: (&lt;module 'string' from '/Users/maurits/.pyenv/versions/3.14.2/lib/python3.14/string/__init__.py'&gt;, '_re')
```

At first I wanted to patch `string` on 3.14 so we still test similar situations:
even if a module is trusted (like `string`), any module/function/class within this module that starts with an underscore must NOT be available in untrusted code.

But we already test this same vulnerability for `random._os`, which is still there on 3.14, so we don't need a hacked up test case.

For the record, this was the patch that I created, to be used in three tests in `test_expressions.py`:

```
from contextlib import contextmanager

@contextmanager
def _patch_string_re():
    """Make sure string._re exists."""
    need_string_patch = not hasattr(string, "_re")
    if need_string_patch:
        string._re = re
    try:
        yield
    finally:
        if need_string_patch:
            del string._re
```

Files changed:
A news/+a8d631d0.tests.md
M src/Products/CMFPlone/tests/test_expressions.py
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2026-02-19T13:36:54+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/454adf3502b0bf88185d64b23342d7745229e557

Configuring with plone.meta: fix dependencies tox env.

Files changed:
M .meta.toml
M tox.ini
Repository: Products.CMFPlone

Branch: refs/heads/master
Date: 2026-02-20T12:37:19+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@py76.be>
Commit: https://github.com/plone/Products.CMFPlone/commit/7b41666352d81edc4ad155400673234b2b8435cf

Merge pull request #4280 from plone/maurits-skip-string-re-tests-on-314

Skip security tests for `string._re` on Python 3.14.

Files changed:
A news/+a8d631d0.tests.md
M .meta.toml
M src/Products/CMFPlone/tests/test_expressions.py
M tox.ini