Downgrade prompt-toolkit to earlier version to fix conflict.
```
Version and requirements information containing prompt-toolkit:
  [versions] constraint on prompt-toolkit: 2.0.10
  Requirement of robotframework-debuglibrary: prompt-toolkit<2
While:
  Installing test.
Error: The requirement ('prompt-toolkit<2') is not allowed by your [versions] constraint (2.0.10)
```