[fc] Repository: plone.app.layout
Branch: refs/heads/master
Date: 2024-03-26T11:39:03Z
Author: Jean-Paul Ladage (jladage) <j.ladage@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.layout/commit/4b3cfef6116f8ded1816619c87977a9184932f5a

Allow including js in head section

Files changed:
A news/3931.feature
A plone/app/layout/analytics/view_head.pt
M plone/app/layout/analytics/configure.zcml
M plone/app/layout/analytics/tests/analytics.txt
M plone/app/layout/analytics/view.py
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-03-26T16:34:20+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.layout/commit/be96cd27aa58c34164611ffda93a5ac9d30d9ea2

Prevent KeyError getting ISiteSchema when not all records exist yet.

We need to run an upgrade step to define the new `webstats_head_js` field, but it would be nice if the UI looks reasonable before this.
Various viewlets give:

KeyError: 'Interface `plone.base.interfaces.controlpanel.ISiteSchema` defines a field `webstats_head_js`, for which there is no record.'

Files changed:
M plone/app/layout/links/viewlets.py
M plone/app/layout/viewlets/content.py
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-03-26T16:34:20+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.layout/commit/9a0c1b6e8bfa49f945f6f470839a338ed3d21ea8

Improve news snippet.

Files changed:
M news/3931.feature
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-03-26T17:03:58+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.layout/commit/cdffe7cdb8025e6d29bc305fbc180e5729844a98

Let the AnalyticsHeadViewlet inherit from the AnalyticsViewlet so we have shorter code.

Files changed:
M plone/app/layout/analytics/tests/analytics.txt
M plone/app/layout/analytics/view.py
M plone/app/layout/analytics/view_head.pt
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-03-28T11:48:05+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.layout/commit/105bef7ff142d50a85c746cb6fbf0b96f1c5a777

zpretty

Files changed:
M plone/app/layout/viewlets/document_byline.pt
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-03-28T11:14:46Z
Author: Jean-Paul Ladage (jladage) <j.ladage@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.layout/commit/276c66ec0e80c7f9875dcdcb3dc72d4c445703c0

Use IHtmlHeadLinks viewlet provider to assure being the last script tag in the head section.

Files changed:
M plone/app/layout/analytics/configure.zcml
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-03-28T11:22:32Z
Author: Jean-Paul Ladage (jladage) <j.ladage@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.layout/commit/4bd740e0a890702692ec842150cf5268d82a134c

Fix tests

Files changed:
M plone/app/layout/analytics/tests/analytics.txt
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-03-28T13:15:24Z
Author: Jean-Paul Ladage (jladage) <j.ladage@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.layout/commit/f1fdfa9cbaef2689cbac0785f59ef96186a872e1

Update changelog entry to refer to correct viewlet manager.

Files changed:
M news/3931.feature
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-03-28T13:25:02Z
Author: Jean-Paul Ladage (jladage) <j.ladage@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.layout/commit/677fccab1dd96758a60a468cfb8fb7d86d8db2e4

Fix tests

Files changed:
M plone/app/layout/analytics/tests/analytics.txt
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-03-28T19:57:29Z
Author: Jean-Paul Ladage (jladage) <j.ladage@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.layout/commit/70283a21732c25f390d4aa651313218d78a978fc

Fix tests

Files changed:
M plone/app/layout/analytics/tests/analytics.txt
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-03-28T20:04:53Z
Author: Jean-Paul Ladage (jladage) <j.ladage@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.layout/commit/63e1655977df317126a43cb51905afec10a2342f

Fix tests, hopefully ci likes it now.

Files changed:
M plone/app/layout/analytics/tests/analytics.txt
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-03-30T14:04:51Z
Author: Jean-Paul Ladage (jladage) <j.ladage@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.layout/commit/a95f03dadb171004a74c621be236a77a308da072

Improve security by filtering all but script tags.

Files changed:
M news/3931.feature
M plone/app/layout/analytics/tests/analytics.txt
M plone/app/layout/analytics/view.py
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-03-30T14:16:44Z
Author: Jean-Paul Ladage (jladage) <j.ladage@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.layout/commit/89f8167b60b7956a604af089625eec68f96336a1

Black fixes

Files changed:
M plone/app/layout/analytics/view.py
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-03-30T14:24:13Z
Author: Jean-Paul Ladage (jladage) <j.ladage@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.layout/commit/15858c3cdc94e0aa590935648320931d10d96bcf

Change import to see it that fixes the dependencies problem

Files changed:
M plone/app/layout/analytics/view.py
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-03-30T14:33:40Z
Author: Jean-Paul Ladage (jladage) <j.ladage@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.layout/commit/222066ac8d4f9a519b2eaaa6948acc6fb52adba1

Black fixes

Files changed:
M plone/app/layout/analytics/view.py
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-03-30T14:36:01Z
Author: Jean-Paul Ladage (jladage) <j.ladage@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.layout/commit/6fa0c7d51a70d9a80ea802853054eb0f6b1b876b

Add lxml to install_requires

Files changed:
M setup.py
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-03-30T14:39:37Z
Author: Jean-Paul Ladage (jladage) <j.ladage@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.layout/commit/1bf6c5a328891f0b9c7c3c3bed2dc50b1d2b329f

Add trailing comma to list, just to make black happy.

Files changed:
M setup.py
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-03-30T17:13:21Z
Author: Jean-Paul Ladage (jladage) <j.ladage@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.layout/commit/7bbd28a41b60d656bceff0aff5741677b94fc024

Use try/except in case someone puts in anything other than &lt;script&gt;-tags.

Files changed:
M plone/app/layout/analytics/view.py
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-03-30T17:50:19Z
Author: Jean-Paul Ladage (jladage) <j.ladage@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.layout/commit/71178e4213e1e7cd1e314870f35eae64f47965cc

Position script even before all other javascripts.
Now using IHtmlHead viewlet manager.

Files changed:
M plone/app/layout/analytics/configure.zcml
M plone/app/layout/analytics/tests/analytics.txt
M plone/app/layout/analytics/view.py
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-04-02T19:22:16+01:00
Author: Jean-Paul Ladage (jladage) <j.ladage@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.layout/commit/5880d2ed9fc58dbcd1220ecc95af5d11985e13f4

Instead of returning only script tags, it now filters base and title tags and renders up the remaining tags.

Files changed:
M plone/app/layout/analytics/tests/analytics.txt
M plone/app/layout/analytics/view.py
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-04-02T23:14:32+01:00
Author: Jean-Paul Ladage (jladage) <j.ladage@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.layout/commit/fc9b432d6307c2c4b5f926417a362ed71568e702

Black and spelling fixes

Files changed:
M plone/app/layout/analytics/tests/analytics.txt
M plone/app/layout/analytics/view.py
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-04-04T18:19:17+01:00
Author: Jean-Paul Ladage (jladage) <j.ladage@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.layout/commit/c240ea1b2585aee585a87d1bf24c5ce0866028a9

Update Changlog entry to reflect new changes.

Files changed:
M news/3931.feature
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-04-04T18:43:14+01:00
Author: Jean-Paul Ladage (jladage) <j.ladage@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.layout/commit/82da26978b1bfc1a0317fbbf8d712b1a42b3b95a

Reduce number of xpath queries.

Files changed:
M plone/app/layout/analytics/view.py
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-04-04T18:49:01+01:00
Author: Jean-Paul Ladage (jladage) <j.ladage@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.layout/commit/a3f6c8a73bc1d4517bac3f80ec3a1088dc3c3238

Black code fixes

Files changed:
M plone/app/layout/analytics/view.py
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-04-23T09:49:19+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.layout/commit/c060d884da38ff6e13ad42c57d059c7d46a6319b

Do not filter webstats code with lxml.

Nice idea, but it would be better in a validator so it is done once.
We have not done that until now, so there is no hurry, but I do want this merged for a Plone release this week.

Files changed:
M news/3931.feature
M plone/app/layout/analytics/tests/analytics.txt
M plone/app/layout/analytics/view.py
M setup.py
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-04-23T09:51:29+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.layout/commit/a1fe14a2163a4dd53626b40966fc0f35b53e559c

Merge remote-tracking branch 'origin/master' into 3931.feature

Files changed:
M .pre-commit-config.yaml
Repository: plone.app.layout

Branch: refs/heads/master
Date: 2024-04-23T16:59:08+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.layout/commit/91585c725e79f0c66f1c37d19ab082817dc19905

Merge pull request #361 from plone/3931.feature

3931.feature allow javascript to be inserted in head-section or at bottom of page.

Files changed:
A news/3931.feature
A plone/app/layout/analytics/view_head.pt
M plone/app/layout/analytics/configure.zcml
M plone/app/layout/analytics/tests/analytics.txt
M plone/app/layout/analytics/view.py
M plone/app/layout/links/viewlets.py
M plone/app/layout/viewlets/content.py