On Python 2.7 pin markdown back to 3.1.1.
That is the last compatible version.
On Python 2.7, version 3.2.1 cannot be installed by pip.
Buildout can install it, but when you try to use it, it fails:

```
>>> import markdown
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/maurits/shared-eggs/cp27m/Markdown-3.2.1-py2.7.egg/markdown/__init__.py", line 27, in <module>
    raise ImportError('A recent version of Python 3 is required.')
ImportError: A recent version of Python 3 is required.
```