[fc] Repository: plone.autoinclude
Branch: refs/heads/main
Date: 2022-05-06T19:55:00+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.autoinclude/commit/936ff40e254b16efd2623f9affd06dc2ccf44e03

Raise an exception when a module cannot be imported.

When environment variable `AUTOINCLUDE_ALLOW_MODULE_NOT_FOUND_ERROR=1` is set, we log an error and continue.
Fixes https://github.com/plone/plone.autoinclude/issues/19

Work in progress: the tests fail with this.

Files changed:
A news/19.feature
M src/plone/autoinclude/loader.py
Repository: plone.autoinclude

Branch: refs/heads/main
Date: 2022-05-09T13:09:49+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.autoinclude/commit/0756119203ad82542af7e8dd6d02abe56badedbb

Allow ModuleNotFoundErrors in tests.

Files changed:
M src/plone/autoinclude/tests/test_loader.py
M test-packages/example.basetestpackage/src/example/basetestpackage/package_base.py
M test-packages/example.basetestpackage/src/example/basetestpackage/utils.py
Repository: plone.autoinclude

Branch: refs/heads/main
Date: 2022-05-09T16:50:13+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.autoinclude/commit/68c6c7813c6825ba2c1041ea1e9758be760298b3

AUTOINCLUDE_ALLOW_MODULE_NOT_FOUND_ERROR: allow comma-separated list.

Fix tests.
Add documentation.

Files changed:
M README.rst
M news/19.feature
M src/plone/autoinclude/loader.py
M src/plone/autoinclude/tests/test_loader.py
M test-packages/example.basetestpackage/src/example/basetestpackage/package_base.py
M test-packages/example.basetestpackage/src/example/basetestpackage/utils.py
Repository: plone.autoinclude

Branch: refs/heads/main
Date: 2022-05-13T15:52:18+02:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/plone.autoinclude/commit/e01ebaa3633ac435cc909e1f5b54d2a8b62c938c

Merge pull request #20 from plone/maurits-env-allow-module-not-found

Raise an exception when a module cannot be imported.

Files changed:
A news/19.feature
M README.rst
M src/plone/autoinclude/loader.py
M src/plone/autoinclude/tests/test_loader.py
M test-packages/example.basetestpackage/src/example/basetestpackage/package_base.py
M test-packages/example.basetestpackage/src/example/basetestpackage/utils.py