[fc] Repository: plone.autoinclude
Branch: refs/heads/main
Date: 2025-02-26T15:46:22+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.autoinclude/commit/3a7e049de9f3d22d234f4b0f07101164c44c50b4

Support Plone 6.0, 6.1, 6.2, Python 3.9-3.13, and Buildout 4.

Drop support for older Plone, Python and Buildout versions.

This is needed because the tests are failing.
See https://github.com/plone/plone.autoinclude/issues/24

Files changed:
A news/24.breaking
M .github/workflows/tests.yml
M setup.py
M tox.ini
Repository: plone.autoinclude

Branch: refs/heads/main
Date: 2025-02-26T15:47:41+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.autoinclude/commit/10d78d5c69c053f3c012a79fdf7e8ff2e208d952

gha: use tox &gt;= 4.

I am guessing that the temporary pin to less than 4 is no longer needed.

Files changed:
M .github/workflows/tests.yml
Repository: plone.autoinclude

Branch: refs/heads/main
Date: 2025-02-26T15:48:45+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.autoinclude/commit/a720f9f4224458fc665ec0a4abf5577e601387a4

Update GitHub Actions versions

Files changed:
M .github/workflows/tests.yml
Repository: plone.autoinclude

Branch: refs/heads/main
Date: 2025-02-26T15:51:12+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.autoinclude/commit/ce553d4d4988b52db9e99e165c4cff1d053c720d

Removed example package and tox envs that were using z3c.autoinclude.

This was only added for comparison, and is not needed anymore.

Files changed:
M tox.ini
D buildoutz3c.cfg
D test-packages/example.z3cintegration/MANIFEST.in
D test-packages/example.z3cintegration/setup.py
D test-packages/example.z3cintegration/src/example/__init__.py
D test-packages/example.z3cintegration/src/example/z3cintegration/__init__.py
D test-packages/example.z3cintegration/src/example/z3cintegration/configure.zcml
D test-packages/example.z3cintegration/src/example/z3cintegration/dummy_plone/__init__.py
D test-packages/example.z3cintegration/src/example/z3cintegration/meta.zcml
D test-packages/example.z3cintegration/src/example/z3cintegration/overrides.zcml
D test-packages/example.z3cintegration/src/example/z3cintegration/tests.py
Repository: plone.autoinclude

Branch: refs/heads/main
Date: 2025-02-26T16:02:07+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.autoinclude/commit/998ccf7df58457815597b27b8bd12a4454e496e6

All test-path arguments now need to be on one line, apparently.

Sample test run without this:

```
$ tox -e py39-integration
py39-integration: commands[0]&gt; zope-testrunner --test-path=test-packages/example.addon/src
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
  Ran 8 tests with 0 failures, 0 errors and 1 skipped in 0.014 seconds.
Tearing down left over layers:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
py39-integration: commands[1]&gt; -test-path=test-packages/example.different/src
py39-integration: Exception running subprocess [Errno 2] No such file or directory: '-test-path=test-packages/example.different/src'
py39-integration: exit 2 (0.00 seconds) /Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude&gt; -test-path=test-packages/example.different/src
py39-integration: command failed but is marked ignore outcome so handling it as success
py39-integration: commands[2]&gt; -test-path=test-packages/example.different2/src
py39-integration: Exception running subprocess [Errno 2] No such file or directory: '-test-path=test-packages/example.different2/src'
py39-integration: exit 2 (0.00 seconds) /Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude&gt; -test-path=test-packages/example.different2/src
py39-integration: command failed but is marked ignore outcome so handling it as success
py39-integration: commands[3]&gt; -test-path=test-packages/example.metaoverrides/src
py39-integration: Exception running subprocess [Errno 2] No such file or directory: '-test-path=test-packages/example.metaoverrides/src'
py39-integration: exit 2 (0.00 seconds) /Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude&gt; -test-path=test-packages/example.metaoverrides/src
py39-integration: command failed but is marked ignore outcome so handling it as success
py39-integration: commands[4]&gt; -test-path=test-packages/example.ploneaddon/src
py39-integration: Exception running subprocess [Errno 2] No such file or directory: '-test-path=test-packages/example.ploneaddon/src'
py39-integration: exit 2 (0.00 seconds) /Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude&gt; -test-path=test-packages/example.ploneaddon/src
py39-integration: command failed but is marked ignore outcome so handling it as success
py39-integration: commands[5]&gt; -test-path=test-packages/example.ploneintegration/src
py39-integration: Exception running subprocess [Errno 2] No such file or directory: '-test-path=test-packages/example.ploneintegration/src'
py39-integration: exit 2 (0.01 seconds) /Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude&gt; -test-path=test-packages/example.ploneintegration/src
py39-integration: command failed but is marked ignore outcome so handling it as success
py39-integration: commands[6]&gt; -test-path=test-packages/example.zopeaddon/src
py39-integration: Exception running subprocess [Errno 2] No such file or directory: '-test-path=test-packages/example.zopeaddon/src'
py39-integration: exit 2 (0.00 seconds) /Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude&gt; -test-path=test-packages/example.zopeaddon/src
py39-integration: command failed but is marked ignore outcome so handling it as success
py39-integration: commands[7]&gt; -test-path=test-packages/example.zopeintegration/src
py39-integration: Exception running subprocess [Errno 2] No such file or directory: '-test-path=test-packages/example.zopeintegration/src'
py39-integration: exit 2 (0.00 seconds) /Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude&gt; -test-path=test-packages/example.zopeintegration/src
py39-integration: command failed but is marked ignore outcome so handling it as success
py39-integration: commands[8]&gt; -test-path=test-packages/example.multipleeps/src
py39-integration: Exception running subprocess [Errno 2] No such file or directory: '-test-path=test-packages/example.multipleeps/src'
py39-integration: exit 2 (0.00 seconds) /Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude&gt; -test-path=test-packages/example.multipleeps/src
py39-integration: command failed but is marked ignore outcome so handling it as success
py39-integration: commands[9]&gt; -test-path=test-packages/namespaceexample.native/src
py39-integration: Exception running subprocess [Errno 2] No such file or directory: '-test-path=test-packages/namespaceexample.native/src'
py39-integration: exit 2 (0.00 seconds) /Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude&gt; -test-path=test-packages/namespaceexample.native/src
py39-integration: command failed but is marked ignore outcome so handling it as success
py39-integration: commands[10]&gt; -test-path=test-packages/namespaceexample.pkgutilns/src
py39-integration: Exception running subprocess [Errno 2] No such file or directory: '-test-path=test-packages/namespaceexample.pkgutilns/src'
py39-integration: exit 2 (0.00 seconds) /Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude&gt; -test-path=test-packages/namespaceexample.pkgutilns/src
py39-integration: command failed but is marked ignore outcome so handling it as success
  py39-integration: OK (0.37=setup[0.03]+cmd[0.30,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00] seconds)
  congratulations :) (0.52 seconds)
```

The missing test paths are ignored, so it looks like a success, but really isn't.

Files changed:
M tox.ini
Repository: plone.autoinclude

Branch: refs/heads/main
Date: 2025-02-26T16:38:00+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.autoinclude/commit/241087b88c8776710101d4cf162ee7c4ed1f8672

Drop support for PyPy.

Technically it may still work, but we no longer test it.  It is irrelevant for Plone.

Main reason for dropping it now, is that this needs an update to our gha setup.
The setup-python action [fails](https://github.com/plone/plone.autoinclude/actions/runs/13547585011/job/37862942913?pr=27):

Error: Invalid format of Python version for PyPy. Python version should be specified in format 'x.y'.

Files changed:
M .github/workflows/tests.yml
M news/24.breaking
M setup.py
M tox.ini
Repository: plone.autoinclude

Branch: refs/heads/main
Date: 2025-02-26T16:51:36+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.autoinclude/commit/f5de104b9eea467225dd3f41a3cae72b8c8bc471

Add pyproject.toml to test-packages to use at most setuptools 75.8.0.

This prevents the filename of the the editable install from having a different mix of dots, dashes or underscores than before.

Without this upper bound, setuptools 75.8.1 would be used, which would then result in test failures like this:

```
Error in test test_load_packages (namespaceexample.native.tests.TestPackage.test_load_packages)
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/local/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "/usr/local/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 589, in _callTestMethod
    if method() is not None:
  File "/Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude/test-packages/example.basetestpackage/src/example/basetestpackage/package_base.py", line 84, in test_load_packages
    packages = load_packages()
  File "/Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude/src/plone/autoinclude/loader.py", line 139, in load_packages
    z3c_dists = load_z3c_packages(target=target)
  File "/Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude/src/plone/autoinclude/loader.py", line 50, in load_z3c_packages
    dist = importlib.import_module(module_name)
  File "/usr/local/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "&lt;frozen importlib._bootstrap&gt;", line 1387, in _gcd_import
  File "&lt;frozen importlib._bootstrap&gt;", line 1360, in _find_and_load
  File "&lt;frozen importlib._bootstrap&gt;", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'example_addon'
```

Strangely, Python 3.11 and lower seem not to be affected.

Files changed:
A test-packages/ExampleCamelCase/pyproject.toml
A test-packages/example.addon/pyproject.toml
A test-packages/example.basetestpackage/pyproject.toml
A test-packages/example.different/pyproject.toml
A test-packages/example.different2/pyproject.toml
A test-packages/example.metaoverrides/pyproject.toml
A test-packages/example.multipleeps/pyproject.toml
A test-packages/example.plone-dash-addon/pyproject.toml
A test-packages/example.ploneaddon/pyproject.toml
A test-packages/example.ploneintegration/pyproject.toml
A test-packages/example.zopeaddon/pyproject.toml
A test-packages/example.zopeintegration/pyproject.toml
A test-packages/namespaceexample.native/pyproject.toml
A test-packages/namespaceexample.pkgutilns/pyproject.toml
Repository: plone.autoinclude

Branch: refs/heads/main
Date: 2025-02-26T18:54:04+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.autoinclude/commit/ce9124678836e25395c35e2eea84d69d055a33e1

Merge pull request #27 from plone/maurits-drop-old-plone-python-buildout-versions

Drop old Plone, Python, and Buildout versions

Files changed:
A news/24.breaking
A test-packages/ExampleCamelCase/pyproject.toml
A test-packages/example.addon/pyproject.toml
A test-packages/example.basetestpackage/pyproject.toml
A test-packages/example.different/pyproject.toml
A test-packages/example.different2/pyproject.toml
A test-packages/example.metaoverrides/pyproject.toml
A test-packages/example.multipleeps/pyproject.toml
A test-packages/example.plone-dash-addon/pyproject.toml
A test-packages/example.ploneaddon/pyproject.toml
A test-packages/example.ploneintegration/pyproject.toml
A test-packages/example.zopeaddon/pyproject.toml
A test-packages/example.zopeintegration/pyproject.toml
A test-packages/namespaceexample.native/pyproject.toml
A test-packages/namespaceexample.pkgutilns/pyproject.toml
M .github/workflows/tests.yml
M setup.py
M tox.ini
D buildoutz3c.cfg
D test-packages/example.z3cintegration/MANIFEST.in
D test-packages/example.z3cintegration/setup.py
D test-packages/example.z3cintegration/src/example/__init__.py
D test-packages/example.z3cintegration/src/example/z3cintegration/__init__.py
D test-packages/example.z3cintegration/src/example/z3cintegration/configure.zcml
D test-packages/example.z3cintegration/src/example/z3cintegration/dummy_plone/__init__.py
D test-packages/example.z3cintegration/src/example/z3cintegration/meta.zcml
D test-packages/example.z3cintegration/src/example/z3cintegration/overrides.zcml
D test-packages/example.z3cintegration/src/example/z3cintegration/tests.py