[fc] Repository: plone.app.theming Branch: refs/heads/1.1.x Date: 2015-07-14T14:50:21-04:00 Author: Sune Broendum Woeller (sunew) <sune@woeller.dk> Commit: https://github.com/plone/plone.app.theming/commit/472b83883b23a35d4d4ff802ab6f5d350d131d56
fix AttributeError: 'NoneType' object has no attribute 'getroottree' when the result is not html / is empty.

Files changed:
M src/plone/app/theming/transform.py
Repository: plone.app.theming
Branch: refs/heads/1.1.x
Date: 2015-07-14T14:52:24-04:00
Author: Sune Broendum Woeller (sunew) <sune@woeller.dk>
Commit: https://github.com/plone/plone.app.theming/commit/965424a2891ef188370e8f691b7a9ac2fb9d7b6f

changelog

# Conflicts:
#	docs/HISTORY.txt

Files changed:
M docs/HISTORY.txt