Revert "remove manual Zope"
This reverts commit 89bae82fbf30ef70725e634d3822f8f22d6e4da7.

We extend versions.cfg from Zope master, so we use a Zope checkout.
Otherwise this fails (as on Jenkins) with:

    Error: Picked: Zope = 4.2.1