Revert "plone.z3cform 1.1.0"
This reverts commit f302db645a476a4235087e682efcca09a7971f6d.

This breaks the build.
See https://jenkins.plone.org/job/plone-5.1-python-2.7/8/

```
Version and requirements information containing zexceptions:
  [versions] constraint on zexceptions: 2.13.0
  Requirement of plone.app.event[test]==3.2.3: zExceptions
  Requirement of Zope2: zExceptions
  Requirement of AccessControl>=3.0.0Acquisition: zExceptions
  Requirement of Products.ZCatalog: zExceptions
  Requirement of Zope: zExceptions>=3.4
  Requirement of zExceptions: zope.security
  Requirement of zExceptions: zope.publisher
  Requirement of zExceptions: zope.interface
  Requirement of zExceptions: setuptools
  Requirement of DocumentTemplate: zExceptions
  Requirement of Products.ZCTextIndex: zExceptions
  Requirement of Products.PythonScripts: zExceptions
While:
  Installing robot.
Error: The requirement ('zExceptions>=3.4') is not allowed by your [versions] constraint (2.13.0)
```