build(versions): Fix local devel buildout error
    $ bin/buildout
    ...
    While:
      Installing.
      Uninstalling plonesite-volto.
      Installing recipe collective.recipe.plonesite.
      Getting distribution for 'collective.recipe.plonesite'.
    Error: Picked: collective.recipe.plonesite = 1.12.0

    The `collective.recipe.plonesite` egg does not have a version pin and `allow-picked-versions = false`.

    To resolve this, add

        collective.recipe.plonesite = 1.12.0

    to the [versions] section,

    OR set `allow-picked-versions = true`.