[fc] Repository: Products.CMFPlone Branch: refs/heads/master Date: 2016-03-07T12:25:56+01:00 Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org> Commit: https://github.com/plone/Products.CMFPlone/commit/240cbaaed3ffc3964f24953c8be17d1c5f9c73cd
Fixed displaying the body text of a feed item.

This is when render_body is switched on in the Syndication settings.

We were overwriting the definition of the `view` variable, which made
it fail:
AttributeError: 'str' object has no attribute 'context'

Strangely, this does not fail in the tests.

Note that we caught the error so no error was visible to a visitor.

Also note that getting the content-core macro may fail anyway, for
example for a Folder, because its default view does not have this
macro.

Files changed:
M CHANGES.rst
M Products/CMFPlone/browser/syndication/templates/content_core.pt
Repository: Products.CMFPlone
Branch: refs/heads/master
Date: 2016-03-11T10:17:32+01:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/Products.CMFPlone/commit/463c045b3b98bd561833a2db061aed528df0bb4e

Merge pull request #1443 from plone/maurits-fix-feed-item-content-core

Fixed displaying the body text of a feed item.

Files changed:
M CHANGES.rst
M Products/CMFPlone/browser/syndication/templates/content_core.pt