[fc] Repository: plone.app.caching
Branch: refs/heads/master
Date: 2024-09-12T01:18:47+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.caching/commit/0dbafff29f3a07d7a7f3cac6aa5d2125ba376469

Add uninstall profile.

Part of https://github.com/plone/plone.app.caching/issues/139

Files changed:
A news/139.breaking.1
A plone/app/caching/profiles/uninstall/controlpanel.xml
A plone/app/caching/profiles/uninstall/registry/basesettings.xml
A plone/app/caching/profiles/uninstall/registry/moderate.xml
A plone/app/caching/profiles/uninstall/registry/strong.xml
A plone/app/caching/profiles/uninstall/registry/terse.xml
A plone/app/caching/profiles/uninstall/registry/weak.xml
M plone/app/caching/profiles.zcml
M plone/app/caching/setuphandlers.py
Repository: plone.app.caching

Branch: refs/heads/master
Date: 2024-09-12T01:18:47+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.caching/commit/399b64bedfef23ed0cc124c86c352bd661ad1e92

Replace plone.app.caching import step with a post handler.

Removed the `plone.app.caching.txt` Generic Setup flag file that was needed by the import step.

This is part of https://github.com/plone/plone.app.caching/issues/139

Files changed:
A news/139.breaking.2
M plone/app/caching/profiles.zcml
M plone/app/caching/setuphandlers.py
D plone/app/caching/profiles/default/plone.app.caching.txt
Repository: plone.app.caching

Branch: refs/heads/master
Date: 2024-09-12T01:25:24+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.caching/commit/f9cf730e50016038ed869e658049729e665b7e34

Renamed importVarious to post_handler.

The previous code gave an error:

```
...
  File ".../plone/app/caching/setuphandlers.py", line 28, in importVarious
    site = context.getSite()
AttributeError: 'RequestContainer' object has no attribute 'getSite'
```

The code needed more changes when going from import step to post handler.

Since it can no longer be used as import step, anyone using this will need to change their code, so it feels safe to rename the function without leaving a backwards compatibility layer.
The import step was meant for internal use only anyway.

Files changed:
M plone/app/caching/profiles.zcml
M plone/app/caching/setuphandlers.py
Repository: plone.app.caching

Branch: refs/heads/master
Date: 2024-09-12T10:11:18+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.caching/commit/c5165d44e973c53682f0e5864c1f4423f16091fd

Merge pull request #142 from plone/maurits-uninstall-profile

Add uninstall profile

Files changed:
A news/139.breaking.1
A news/139.breaking.2
A plone/app/caching/profiles/uninstall/controlpanel.xml
A plone/app/caching/profiles/uninstall/registry/basesettings.xml
A plone/app/caching/profiles/uninstall/registry/moderate.xml
A plone/app/caching/profiles/uninstall/registry/strong.xml
A plone/app/caching/profiles/uninstall/registry/terse.xml
A plone/app/caching/profiles/uninstall/registry/weak.xml
M plone/app/caching/profiles.zcml
M plone/app/caching/setuphandlers.py
D plone/app/caching/profiles/default/plone.app.caching.txt