Run mxmake update.
Use latest mxmake for this.
Important change: this no longer runs `mxdev -o`, but `mxdev -f`.
This fixes the following error that I started seeing, [for example on gha](https://github.com/plone/buildout.coredev/actions/runs/18780517910/job/53585253701):

```
RuntimeError: Offline mode:
HTTP reference 'https://zopefoundation.github.io/Zope/releases/5.13/constraints.txt'
not found in cache. Run mxdev in online mode first to populate the cache at .mxdev_cache
```